### ISSUE TITLE
Link to transcoder campaigns on /transcoders view of explorer

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#100]
**What's the problem? (required)**
There is currently no link between a transcoder and their social transcoding campaign accessible to users on http://explorer.livepeer.org/transcoders.

**What's the current behavior? (required)**
There is no link. Users have to browse through the forum and visually parse addresses to determine which campaign is for which transcoder.

**Do you have any personal experiences dealing with this problem? (optional)**
Yes, it's very difficult to remember which transcoder address is which user.

**Describe a possible solution you've considered (optional)**
1. Transcoder campaign links are maintained in this repo: https://github.com/dob/livepeer-lists/tree/master/transcoders. Programmatically request the file by address, and display the link. Or import the files into the build when building, and read the list locally.

or

2. Use an on chain transcoder registry.

**Additional context (optional)**
I think the most useful place for these links would be via an icon or small text link on the /transcoders view itself so they're all accessible across transcoders from one page without having to dig into the transcoder profile view for each one. Though I also think it would be useful to include on the transcoder profile view as well. See the "witness thread" link here: https://steemit.com/~witnesses

**Comment by jozanza** [comment]
@dob Great idea. We absolutely need this. Do we have some smart contracts deployed for this registry and some ABIs I can use? I'd much rather take that approach.

**edit**: If not, I'd be happy to create a tiny smart contract for managing this :)

**Comment by ericxtang** [comment]
This feels related to https://github.com/livepeer/LIPs/issues/6, which I know @yondonfu is working on.  Any chance we can satisfy both requirements in the same change?

**Comment by jozanza** [comment]
@ericxtang I don't know if it's the greatest idea to tie social smart contracts with business-logic token/network related smart contracts. I'd like the flexibility to upgrade social contracts without risk to critical ones that affect token balances and may require auditing.

**Comment by yondonfu** [comment]
This discussion in https://github.com/livepeer/LIPs/issues/6 is centered around an address to metadata registry focused on off-chain informational use cases. The registry would be completely separate from existing contracts that handle LPT/ETH related state accounting - the only thing the registry would be responsible for would be setting and returning metadata fields for an address. I think a campaign URL (in addition to the service URI already discussed in that thread) can be a good fit for this type of registry - in a follow up comment I described an interface that includes a setter/getter for a campaign URL.

**Comment by jozanza** [comment]
@yondonfu I'm thinking the underlying need for this issue is not "transcoder meta data" but rather "social meta data", primarily for DApps (not networking protocols) that exist today and could also in the future. For example, "social smart contracts" that fall into this category would need to include broadcaster-related things in the future as well. So these contracts would likely expand to hold more information over time as more social UX enhancements are warranted.

I'd think it best not to convolute your proposal with meta data that is yet-to-be settled on and includes more than just transcoder data. So imho, it's definitely better to just consider these completely separate, unless you want to do down that rabbit hole and couple networking meta data with social meta data.

**Comment by dob** [comment]
One thing to keep in mind is that it's very expensive to put (and maintain) a lot of metadata on chain, and it's often not necessary to have it on chain in the first place. For example, there's no reason all this data needs to live on chain: https://github.com/dob/livepeer-lists/blob/master/transcoders/0xfb9849b0b53f66b747bfa47396964a3fa22400a0.json

If you really want to tie authoriziation that this is the correct data, to the transcoder/user themselves, then a simple attestation could live in an on chain registry: a transaction submitted by the transcoder with the git commit hash, or sha3 of that metadata file which could be verified. That way you would get both the confidence that the transcoder authorized that data about themselves, and the ease of use + cost effectiveness of submitting a single hash on chain rather than multiple KB of data.

**Comment by yondonfu** [comment]
@jozanza Good point! I had originally been just thinking of a generic Livepeer identity centric metadata registry, but I agree that there should be a distinction between networking protocol metadata and social metadata. In fact, I would consider the orchestrator service URI more generally as core protocol metadata that is crucial for the operations of the core Livepeer protocol. Meanwhile, something like the campaign URL is not strictly necessary for the operations of the core Livepeer protocol and as a result likely does not need to be associated with a contract that is a part of the core protocol smart contracts. Where this type of the data is stored and how it is managed can be defined separately perhaps even as a non-core protocol standard that Livepeer applications adhere by using ideas along the lines of the suggestion by @dob

**Comment by jozanza** [comment]
Made a related comment: https://github.com/livepeer/livepeerjs/issues/101#issuecomment-394553589

Basically, it seems like we need to settle on a decentralized approach to persist data that is not core protocol data. We can do something limited with smart contracts fairly easily. This is the most expensive for the user but the easiest for us to maintain, although it won't scale as well when we need  to persist new data points. Or we can make things faster and less expensive with IPFS/OrbitDB, but we'd need to run a few services to pin data, etc.

I'm personally more in favor of the latter approach as it will work the best for any DApps we decide to create, and I don't think the services will be expensive or particularly hard to run. And it's definitely a great thing to build to attract more developers to the project. We could get a lot of of mileage in terms of blog posts and talks about how we built it.

**Comment by adamsoffer** [comment]
Ended going with 3box ([which will soon become IDX](https://blog.ceramic.network/migrating-from-3box-to-ceramic-and-idx/)).
