### ISSUE TITLE
bug: fee sorting is not working correctly

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-monorepo#1008]
**Describe the bug (required)**
When sorting by fees, the column appears alphabetically sorted rather than numerically. 

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/555740/124395336-8efaaa80-dcd1-11eb-9a7f-b374fb4927b8.png)

**Comment by 0xVires** [comment]
@adamsoffer is there an update on this? It sucks to be somewhere on the second page if sorted by fees despite being the top earner. It also is an important metric for potential stakers so I'd appreciate if this could be fixed soon.

**Comment by adamsoffer** [comment]
@0xVires Apologies this fell through the cracks. Deploying the fix now...

**Comment by adamsoffer** [comment]
The fix has been deployed.
