### ISSUE TITLE
Add an asterisk under "Stake" button that states "Enter 0 to Move Stake"

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/livepeer-monorepo#1014]
Add instructions under the stake button to direct delegators how to Move Stake
`* Enter 0 to Move Stake`

Or

Change Stake button to read
`Stake/Move Stake`

This is a very simple fix that will help new comers and has been a sore spot for many people looking to change Orchestrators that end up Unstaking by accident.

**Comment by adamsoffer** [comment]
Nice suggestions 👍 I can submit a PR with a fix.

**Comment by adamsoffer** [comment]
@Titan-Node - feel free to leave feedback on [this PR](#1016).

Preview/staging URL with update -> https://explorer-mainnet-git-as-move-stake-footnotes-livepeerorg.vercel.app

**Comment by Titan-Node** [comment]
@adamsoffer Looks great!

Really like the Unstake notice too which will stop people from Unstaking if they are looking to move stake.

I guess the only improvements (which are really picky) is to remove the asterisk `*` from the statement and remove the `(amount of LPT)` in the statement.

After seeing it on the explorer I think keeping it clean and less to read is nice and elegant, just like the `You're not staked to this orchestrator.` statement.

Great job

**Comment by yondonfu** [comment]
Closed by #1016
