### ISSUE TITLE
Livepeer Explorer: Call history to exclude current round

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/livepeer-monorepo#1020]
**What's the problem? (required)** 
Currently the call history in the Explorer includes the current round, if an Orchestrator waits for lower gas fees during the round the call history shows 29/30 until it is called.

This is misleading because the O could still call every round and still be redeeming 30/30 when it shows 29/30.
This can confuse delegators and hinder Os from receiving stake because they do not call reward immediately each round.

**Solution**
Do not include the current round in the trailing 30 day history.

**Comment by Titan-Node** [comment]
Any update on this? 

Would love to see the implementation of this while gas fees are high.

Sitting at 29/30 when calling every round may put good operating Os at a disadvantage to Os with deep pockets that call at the beginning of each round regardless of price.

Cheers!

**Comment by adamsoffer** [comment]
Thanks for flagging @Titan-Node! A fix has been deployed 🚀. Call history now excludes the current round.
