### ISSUE TITLE
I want to select the resolution of my livestream playback

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#103]
**What's the problem? (required)**

The problem is that I am unable, as a user, to choose the resolution of the livestream to fit my bandwidth, and to fit with the power of my playback device.

For example, if I am connecting using a very slow internet connection, with a low-powered device, I would like to be able to e.g. select the lowest available resolution e.g. 144p (256x144).

**What's the current behavior? (required)**

Currently, the player defaults to playing the stream in the resolution that it is being broadcast in, i.e. without any transcoding during the process of 

**Do you have any personal experiences dealing with this problem? (optional)**

Yes, there have been many occasions when I have been able to successfully load a stream on e.g. a powerful laptop wifi, but not able to load on a iPhone 5s using the same wifi. This makes me wonder whether the device is not powerful enough to play.

**Describe a possible solution you've considered (optional)**

An initial solution could be to provide the user with the option of selecting to vary the resolution of the stream. Even if there is only one option (e.g. 1920x1080) then it would at least allow a user to understand a) that this is currently the only option, and b) what the resolution is, and c) to start to demand transcoded services (i.e. the core of Livepeer's current value driver :) )

Then, as more options for different resolutions become available from Livepeer, users would be able to select from the options that are made available.

An ideal solution to this, would be to allow a user to choose their own resolution (and possibly even their own bitrate) - and for this to trigger a transcoding job, paid for by the viewer, which could generate a transaction in MetaMask to pay into Livepeer?

**Additional context (optional)**

Perhaps something like this can be included in the design of the next phase of Livepeer's transcoding marketplace @f1l1b0x ?

**Comment by chrishobcroft** [comment]
Closing because this functionality is better defined in https://github.com/livepeer/livepeerjs/issues/122 and there is the start of a discussion there also.

**Comment by ericxtang** [comment]
Duplicate to https://github.com/livepeer/livepeerjs/issues/183
