### ISSUE TITLE
Scout page not working properly

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/livepeer-monorepo#1032]
The scout webpage is not working properly - https://scout.cool/livepeer/mainnet/

Errors such as "No data is available in the selected date range" on the main page.
Boxes that are not working include "Current LPT Total Bonded" "Current Inflation Per Round" etc.

And (most importantly)

The filter function on the Transactions page does not recognize any string searches - https://scout.cool/livepeer/mainnet/transactions

ie. seach "0" in search box, which should return a list of transactions including "0", results in "No results found"

**Comment by papabear99** [comment]
I thought it was just me not knowing how to properly use the filter.  Thanks for reporting.

**Comment by adamsoffer** [comment]
I'm not sure if Scout Cool plans on maintaining that explorer. I'd consider reaching out to them on their site.
