### ISSUE TITLE
Add a CTA for users who are not logged in with MetaMask

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#105]
**What's the problem? (required)**

Users who are not logged in with MetaMask are not aware of some of the opportunities available to them if they were a) to log in, or b) to install MetaMask, or c) to have Ethereum / crypto in general.

Opportunities such as:

- having "MY ACCOUNT" with Livepeer.
- contributing directly to broadcasters (in media)
- bonding (in explorer)
- others we haven't even dreamed of yet.

**What's the current behavior? (required)**

For example, if I am logged in with MetaMask, the player shows me this:

![image](https://user-images.githubusercontent.com/2212651/40891818-ab0619f2-678c-11e8-8a84-2e97a6138bde.png)

If I am not logged in with MetaMask, the player doesn't show anything to prompt a user to either a) log in to MetaMask, or b) get MetaMask

**Do you have any personal experiences dealing with this problem? (optional)**

I tend to forget that the "Tip the broadcaster" thing exists because I'm not always logged in to my MetaMask, and I am its biggest fan.

**Describe a possible solution you've considered (optional)**

If user has MetaMask but is not logged in, can say "Log in to MetaMask to tip the broadcaster"

If user does not have MetaMask, can say "Install [MetaMask](http://metamask.io) to tip the broadcaster directly"

I want a little bit for users to be intrigued by "what is this thing, Web 3.0", because right now they really don't know.

**Additional context (optional)**

Keep up the great work on livepeerjs! We love you @jozanza

**Comment by jozanza** [comment]
Right. Users may not have a clue about how to participate in any protocol txns with the UI as it is today. While, currently, the player does not have a concept of "My Account", the fact still remains that you may want to give the broadcaster some ETH (or maybe even tokens???). You'd need to be authenticated with an Ethereum account to do this. Any you can't play the delegation game at all if you aren't authenticated.

Clearly, we should prompt users to authenticate, however, there are a lot of options for doing this: Mist, Parity, MetaMask. And then on mobile, we have a totally different set: Cipher, Toshi, Status. So we would need to make some decisions about what we recommend and perhaps create external resources (in the wiki, forum, or website) to help guide newcomers with clear steps, in greater detail. This is where the bulk of the work lies.

Once we have that, it's just a matter of figuring out where to place the prompt in the UI of both DApps. Here's my recommendation:

- For the player, we leave the tip button visible at all times and show the prompt to users who click on it and are not logged in.
- For the explorer, we leave the "My Account" nav link visible and show the prompt to users who click on it and are not logged in.

Once we know the copy of the prompts and any necessary external resources, these updates can be made easily. I think they'll be really good gitcoin candidates too! :3

And of course, we can continue to monitor user feedback and analytics afterward to see if there are other ways we can let users know about why they may want to log in. We can make separate issues for such enhancements as needed 👍

**Comment by Randy1Burrell** [comment]
@jozanza and @chrishobcroft this issue have been worked on in the explorer. When a user visits the explorer and is logged out of their wallet or doesn't have web3 installed a bar pops up on the transcoder page asking the to login to web3 when it's installed or install web3 to so that they can use the full feature of the explorer. You can test it out [here](http://explorer-staging.livepeer.org.s3-website-us-east-1.amazonaws.com/transcoders) and let me know what you think. We could implement this in the player too.

**Comment by ericxtang** [comment]
Closing since it's been addressed.
