### ISSUE TITLE
Rename "tip" to "contribute"

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#106]
**What's the problem? (required)**

The concept of "tipping" isn't really common parlance outside North America. It's maybe the kind of thing that 

**What's the current behavior? (required)**

The text currently reads as follow:

![image](https://user-images.githubusercontent.com/2212651/40891929-42c27d10-678f-11e8-9b60-b0e923f9b806.png)

**Do you have any personal experiences dealing with this problem? (optional)**

People have asked me "what does it mean 'tip'"?

**Describe a possible solution you've considered (optional)**

Text could say: "Contribute directly to the broadcaster [<3 CONTRIBUTE]"

**Additional context (optional)**

If the creators and broadcasters are always considered as people to "tip", it might make them feel less valued compared to other members of community who might be "paid" or "funded" or "bountied". Just a thought.

**Comment by jozanza** [comment]
Cool, yeah we definitely need to phrase things differently based on nationalities/locales. In developer parlance, this is known as "internationalization" or i18n. At some point, to be inclusive of a decentralized community, we'd need to internationalize all of the copy in both the explorer and player (as well as the website).

I suggest we approach this larger issue by identifying all of the messages in both DApps. Once we have a list, it shouldn't be too bad to get the messages translated. After that, it's just a matter of replacing all of the text in each app. Internationalizing a codebase can be annoying, but I don't think we're too deep in the woods yet. We could probably get both DApps internationalized within a sprint, if that were the focus.

Thoughts @chrishobcroft ?
