### ISSUE TITLE
Can Livepeer have a Little Brother? Only Audio Streaming

### ISSUE THREAD

**Issue by Matlemad** [livepeer/livepeer-monorepo#107]
**What's the problem? (required)**
Livepeer is purely video-streaming and doesn't offer the alternative of an audio-only layer
which could have an easier UX 
1) it would be easier in terms of bandwidth 
2) it's not tech-exclusive, even cheaper smartphones could run it without using too much cpu.

**What's the current behavior? (required)**
we use Spotify/AppleMusic for Audio and YT for videos.
In a decentralised world, I see these two things working under the same shared standard.

**Do you have any personal experiences dealing with this problem? (optional)**
Audio is definitely lighter to stream. Also transcoder can manage a higher number of streamings.

**Describe a possible solution you've considered (optional)**
an Audio Layer for Smartphone that doesn't require a sign in.
It only install Livepeer Little Brother. and creates an ETH account.
Little Brother could run a liter version of LP and sync to the audio files on the phone and audio I/O of the phone, making it a small radio station.

**Additional context (optional)**
Add any other context or screenshots about the enhancement or feature request here.

**Comment by jozanza** [comment]
Good question! I'd love to see some folks in the community try something like this. They could certainly fork this repo or any of its packages and use that as a starting point. However, the Livepeer node transcodes to HLS, so I'm not sure what kind of bandwidth / performance benefits audio-only would create. Anyways, I'll just leave this issue open for anyone who wants to discuss 👍

**Comment by f1l1b0x** [comment]
Audio only streaming is noted and in most cases would not require a transcoding just a transmuxing/repacking to a hls stream 

We currently do not have a concept for passthrough streams but should add it

**Comment by Randy1Burrell** [comment]
@Matlemad, @f1l1b0x and @jozanza has this issue been resolved? I would love to close this.

**Comment by j0sh** [comment]
It's not resolved yet, but it's a [LPMS issue](https://github.com/livepeer/lpms/issues/60); livepeerjs isn't involved at that level. Once goclient supports audio-only streams, then the JS player should be able to handle it without issues.

**Comment by Randy1Burrell** [comment]
Ok, @j0sh so I guess this can be closed then?

**Comment by Matlemad** [comment]
Yes it has been moved to a feature request I guess.
I had a few additional meetings regarding this topic, and the general impression was very enthusiastic, although it raised some concerns, the biggest one being that a purely Audio Livepeer protocol would deal with way lower bit rate that would make the transcoding price even cheaper than the txn itself. So it's definitely something to start to talk about once Ethereum has solved gas issues. On the other side, a P2P lite app where users can broadcast audio from their phones, make it visible to their contacts, and allowing those contacts to "rebounce" the signal to their contacts (in a pyramidal structure) could trigger some further popularity for the main project.

**Comment by Randy1Burrell** [comment]
@jozanza, @f1l1b0x, @Matlemad and @j0sh Thanks! @Matlemad please link back to this issue from the feature request issue. Closing this now.
