### ISSUE TITLE
998 rounds to claim

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#109]
**Describe the bug (required)**

When trying to claim my remaining earnings on mainnet, it shows that I have 998 rounds to claim, but the network hasn't been active that long.

I'm hesitant to go ahead with this transaction. I don't want to inadvertently submit an excessive range and lose the gas, since I believe there are actually less than 20 rounds left to claim.

**Expected behavior (required)**

Should show the correct number of rounds that are left to claim.

**To Reproduce (required)**

0. Claim some earnings (I did 20 rounds worth last week)
1. Try to claim for the remaining rounds
2. Shows an incorrect number of remaining rounds

**Device (required):**

MacOS Chrome
 
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/292510/41122197-a00f80c2-6a4f-11e8-8913-a21c19bfc629.png)

**Console logs (optional)**

Don't think these are related, but in case it helps:

```
main.d4107792.js:1 Unhandled GraphQL subscription error Error: Subscription field must return Async Iterable. Received: [object Object]
    at main.d4107792.js:1
    at a (main.d4107792.js:1)
    at main.d4107792.js:1
    at MutationObserver.c (main.d4107792.js:1)
```

**Comment by Randy1Burrell** [comment]
@j0sh are you still experiencing this issue?

**Comment by j0sh** [comment]
Haven't seen the issue lately, we can probably close this one.
