### ISSUE TITLE
Channel Player Buffering?

### ISSUE THREAD

**Issue by rayj00** [livepeer/livepeer-monorepo#11]
It seems that when a broadcast is concluded, the player goes into a buffering mode, meaning the rotating graphic stays active like forever?

![image](https://user-images.githubusercontent.com/6609523/34071723-a45a3cce-e248-11e7-8081-517ee9390db8.png)

You can see the rotating circle in the center of the video.

**Comment by jozanza** [comment]
@rayj00 Thanks for creating this issue. It seems this happening because old segments are being cached by our nodes. Issue #9 is where we'll continue the discussion. 👍
