### ISSUE TITLE
Broadcaster channel name

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#110]
**What's the problem? (required)**

I am unable to configure a human-readable name as the Broadcaster in media.livepeer.org, which means that my viewers are unable to build awareness of my name and brand, as a broadcaster.

**What's the current behavior? (required)**

When a viewer loads up a stream, e.g. [Livepeer TV](https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014), they are told that the Broadcaster is `0x0dDB225031cCB58fF42866f82D907F7766899014`. My conjecture is that this information has limited meaning or relevance to a viewer.

See below.

![image](https://user-images.githubusercontent.com/2212651/41156940-3ef6b532-6b24-11e8-8a3f-8096ad1a5803.png)

**Do you have any personal experiences dealing with this problem? (optional)**

I have the problem that I don't feel like my viewers "get it" as well as they might.

**Describe a possible solution you've considered (optional)**

Create a mechanism to store a "channel name" associated with the broadcaster address, with this information signed and stored in the Blockchain.

It's unlikely that it will change often, although the solution ought to allow unlimited changes by the key holder(s).

Then, when the channel is loaded by the viewer, it should show the "human-readable" name instead of the hex code. Like so:

![image](https://user-images.githubusercontent.com/2212651/41157217-3aa05afa-6b25-11e8-8243-de7c59c88e4a.png)

**Additional context (optional)**

Keep up the good work, it's very nice.

**Comment by yondonfu** [comment]
One way to accomplish is via ENS name resolution - if the broadcaster `0x0dDB225031cCB58fF42866f82D907F7766899014` owns the ENS name `livepeertv.eth`, livepeer.tv could redirect to https://media.livepeer.org/channels/livepeertv.eth and the player could resolve `livepeertv.eth` to `0x0dDB225031cCB58fF42866f82D907F7766899014` under the hood
