### ISSUE TITLE
Explorer to show more "overall metrics"

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#111]
**What's the problem? (required)**

I am unable to easily access information about the overall network in terms of tokens, bonding, reward amounts, meaning that as a token holder, I don't have much context about the bigger picture and how I fit into it.

**What's the current behavior? (required)**

Currently, the explorer shows a whole heap of information at the level of an individual address. But limited information which puts that address in context in the bigger picture.

**Do you have any personal experiences dealing with this problem? (optional)**

When explaining to people about the token mechanics, it isn't easy for them to understand the bigger picture of the overall network, and how they fit in.

**Describe a possible solution you've considered (optional)**

Show some of the following metrics in the explorer

- total LPT bonded to all nodes
- total LPT "in circulation" (this would need to be defined)
- total LPT minted
- how many new LPT are minted per round

Furthermore, this could lead to showing things like:

- Node's total stake as % of overall network stake
- My LPT holding as a % of total LPT

**Additional context (optional)**

Perhaps this can tie in with Yondon's work reporting protocol level metrics?

**Comment by jozanza** [comment]
This is pretty similar to what's being discussed in livepeer/explorer#73 . There are a lot of stats mentioned in that issue. So I'm going to close this issue. But for clarity, here is what the process for getting these metrics into the explorer looks like:

- Step 1 is to add them into the SDK.
- Step 2 is to model in GraphQL (probably in the `Protocol` type, but there are a lot of requested data points that may deserve separate type definitions).
- Step 3 is to put them into the explorer UI

Step 3 is easier said than done. Plopping even more unfamiliar metrics into a dApp already filled with them can have a really bad effect on UX. We'll at least need some tooltip text to help guide users. But more importantly, it probably doesn't make sense to put everything on a single page. Information requires context to be understood, and this means we need to consider which of these numbers belong in existing views and which may require some new page entirely.

That being said, let's keep the conversation going on livepeer/explorer#73. I'd like to make some choices about which metrics we need, where they live in the explorer, and potentially break out that issue into several smaller ones so the updates can be smaller and released incrementally 👍
