### ISSUE TITLE
Removing Transfer Allowance Pop Up

### ISSUE THREAD

**Issue by RaffiSapire** [livepeer/livepeer-monorepo#114]
**Describe the bug (required)**
I personally felt very irritated that I had to pay to change my allowance. Requiring people to change their transfer allowance takes both time and gas, and therefore causes people people drop off and have a negative experience with Livepeer. Please can you lay out the technical challenge this solves and can we brainstorm how to solve without using the token holder? Here's feedback from a user interview: 

"Having the initial transfer allowance at 0 means I have to spend gas to update it straight away... why not start at a moderate amount initially so people don't have to jump through so many hoops to get started?"

**Expected behavior (required)**
When I click bond, I just want to bond. I don't want to have to adjust my limits and pay gas and then pay gas again to bond.

**Comment by jozanza** [comment]
Yeah it’s an ERC20 thing unfortunately. You need to set one, and there’s no way around that :/

**Comment by jozanza** [comment]
I'm going to close this issue, but it's definitely something to think about when user testing. There will absolutely be ways to continue to improve the first-time bonding experience. Unfortunately, transfer approval is a requirement at this point in time.
