### ISSUE TITLE
explorer.livepeer.org returning 403 forbidden status header

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#117]
**Describe the bug (required)**
Requests to explorer.livepeer.org are returning a 403 forbidden HTTP status. The body of the page is actually returned in the response, but because of this header status some browsers may not render the page or show an error.

**Expected behavior (required)**
The page should return a 200 HTTP status.

**To Reproduce (required)**
1. Open Chrome Dev Tools: CMD+OPTION+J
2. Click the "Network Tab"
3. Visit https://explorer.livepeer.org
4. View the HTTP status on the response: 403
5. View that there is a cloudfront configuration issue in the header details of the response.

It was also reported in chat by ak1 to check using tools like 
https://monitorbacklinks.com/seo-tools/http-header-status-check and http://www.webconfs.com/http-header-check.php

**Device (required):**
 - Macbook Pro on OSX, Chrome.
 
**Screenshots (optional)**
https://cl.ly/241E242V1645

**Console logs (optional)**
Response headers

```
accept-ranges: bytes
content-length: 1775
content-type: text/html; charset=utf-8
date: Tue, 19 Jun 2018 14:02:14 GMT
etag: "4e204e678f9a5d11d315efcbf534c0b8"
last-modified: Tue, 05 Jun 2018 02:34:43 GMT
server: AmazonS3
status: 403
via: 1.1 655ceee114a61672fa30ade2501aa4b4.cloudfront.net (CloudFront)
x-amz-cf-id: pFk41y1chBhXf5l54fNRqiMBBiNJHMMr230N0ocvAfX3DjcdsjqL6A==
x-cache: Error from cloudfront
```

**Comment by jozanza** [comment]
@dob you or @ericxtang will have to update this in the AWS cloudfront distro for explorer/player. I'm going to close this issue here since it's not LivepeerJS codebase-related 👍
