### ISSUE TITLE
Change "Claim Stake & Fees" Workflow

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#121]
**What's the problem? (required)**
Users are explicitly calling "Claim Stake & Fees" when they don't have to.

**What's the current behavior? (required)**
Users are explicitly calling "Claim Stake & Fees", but they don't have to do it unless there are more than 20 unclaimed rounds.

**Do you have any personal experiences dealing with this problem? (optional)**
No - but I see a lot of unnecessary transactions in Etherscan.

**Describe a possible solution you've considered (optional)**
This can be the new workflow:
* Users never see the "Claim Stake & Fees" option.
* In the bonding experience, if the user has less than 20 unclaimed rounds, they don't have to even know about claiming.
* In the bonding experience, if the user has more than 20 unclaimed rounds, a "Claim Stake & Fees" modal pops up.  This modal explains why it's there, and only allows them to claim 20 rounds (don't need to pick how many rounds they want to claim).  They will continue to be prompted to claim 20 rounds until they have less than 20 unclaimed rounds.

**Comment by jozanza** [comment]
Rather than hiding that button, I think we should do a better job of letting users know **when** they should claim their earnings: in what cases should they maybe hold off, and in what cases should they submit that transaction?

**Comment by ericxtang** [comment]
Good idea @jozanza.  What do you think should be the experience for that?  Warning messages in the claim modal?  It might also be helpful to create visual signal to let users know the unclaimed earning is already part of the total stake.

**Comment by jozanza** [comment]
@ericxtang I think we should open 3 issues to tackle this:

1. Add a warning message in the claim modal. Once we settle on the wording, this can be done immediately.
2. Add LPT and ETH from unclaimed earnings to the **Stake** and **Fees** metrics on the account view's delegating tab.
3. Add LPT from unclaimed earnings to the "Your Stake" column on the transcoders list.

**Comment by jozanza** [comment]
@ericxtang Actually, I just did items 2 & 3 on my current fork that contains the mining updates. I also handled #33 while I was at it, which means we can close that one as well as #131 once it gets merged. So all we need to do is think of a good message for item 1.
