### ISSUE TITLE
Richer content embedded in media.livepeer.org for social media sharing

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#126]
**What's the problem? (required)**

When I post livepeer.tv's stream to something like Facebook, the content that is extracted from the webpage 

**What's the current behavior? (required)**

Right now, it shows up something like this:

When I am writing a post on Facebook:

![image](https://user-images.githubusercontent.com/2212651/41695839-2b73ece0-7511-11e8-9864-760a4c16e893.png)

After I have posted to Facebook:

![image](https://user-images.githubusercontent.com/2212651/41695876-56afaac0-7511-11e8-8d27-f0f6568d9c1c.png)

**Do you have any personal experiences dealing with this problem? (optional)**

Every time I try to share Livepeer TV broadcasts with anyone in the non-blockchain world.

**Describe a possible solution you've considered (optional)**

To present some of the streaming content to Facebook, for them to show in their pages.

There are channels with livestreaming content flowing 24/7 - let's help them to share this.

**Additional context (optional)**

This will help broadcasters to start to share content with their existing audiences on traditional social media.

**Comment by dob** [comment]
@chrishobcroft can you research the required `og:` or meta tags (or other integration steps) to have links convert to embedded streams in facebook and twitter? If we have more info on the required implementation it may be easy to add that metadata to the rendered pages so that the embeds show up in a rich way.

**Comment by jozanza** [comment]
It's not that simple. The player is a single page app (SPA). You'd need to have compiled static web pages for all accounts that want to have meta tags like this. And you'd also need to upload any assets that would appear in the shared link. Basically, you're going to need a persistence layer, file storage, and user authentication to implement this.

It would be better for folks to maybe make their own sites that have all the meta tags and media/assets they want. They can embed a Livepeer player via an iframe or fork and white-label their own version of the player.

**Comment by saskakol** [comment]
Yep, really tough to do with an SPA. Most of the webcrawlers that social sites use don’t load client-side JS at all, so the meta tags can’t be added to each page using react. You would have to prender each version of the player page for each streamer, and there are a few problems with that: 
1. If all stream pages were prerendered when the site is deployed, most streams would have outdated pictures on them, if any (in case they weren’t streaming when the prerender happened).

2. There’s not much data to display to the social site either, without implementing #101

3. There are just too many Ethereum addresses to prerender all of the pages. Even if you just did the addresses that have actually streamed (or the page has been visited), then all of the streamers that haven’t streamed before deployment of the site will not have any prerendered content.

It might be possible to just have some default meta tags in place for all streamers, which might make the social posts a bit more descriptive/nice looking, but they won’t really have the same impact as having custom content for all streamers.

**Comment by Randy1Burrell** [comment]
@chrishobcroft and @dob this is not a simple issue but I will spend some time looking into what can be done about it.

**Comment by iameli** [comment]
Closing this for now. We've moved away from Ethereum addresses on `media.livepeer.org`, so unfortunately there's not really a logical source for any data that we'd be serving.

Something like this would be a good candidate for hosting and server-rendering on a Cloudflare Worker when/if we eventually do have integration with something like ENS or 3Box.
