### ISSUE TITLE
Explorer - Address View

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#14]
Since all users are identified by their Ethereum address, the explorer should probably have an `/address/<address>` view. This view will likely be broken into different sections for broadcasting data, delegation data, transcoding data, and watcher data. Some of these sections may be empty if the user has never done a watcher transaction or never been an active transcoder. 

## General account section

* Eth balance
* Liquid LPT balance

## Delegator section

* Bonded amount
* Delegated Amount
* Transcoder delegated towards
* Bonded status
* Start round
* Withdraw round
* lastClaimTokenPoolSharesRound

(potential history of claiming token pool shares, but potentially an enhancement tracked separately)

## Transcoding section

* Current and pending fees/shares like on the all transcoders view.
* I'm thinking there may be so much historical data to dig through for an individual transcoder in terms of all the jobs they've been assigned/claims they've made, verifications invoked/failed, etc that we probably want this on a /transcoder/<address> view.

## Watcher section

* History of watcher functions invoked and finders fees gained, linking to specific claims.

**Comment by dob** [comment]
Right now the address view at `/me` shows "deposit LPT". Deposits are now in ETH instead of LPT.

**Comment by jozanza** [comment]
That button got updated in 30855ef

**Comment by jozanza** [comment]
Closed by https://github.com/livepeer/livepeerjs/commit/1df196f5283c1c1e9dc24d4303eb586bfef86d05
