### ISSUE TITLE
Allow user to hide the "Join the Alpha" banner in the player

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#142]
**What's the problem? (required)**

The player displays a "Join the Alpha" banner in the player that cannot be hidden unless the player is switched into full screen mode.

**What's the current behavior? (required)**

The player does not allow a user to hide the "Join the Alpha" banner in the player.

**Do you have any personal experiences dealing with this problem? (optional)**

A user of the player has commented to me that he finds the banner at the bottom of the player very distracting and would like there to be an "X" to close/hide it. 

**Describe a possible solution you've considered (optional)**

Add an "X" to the banner that will close/hide the banner when the user clicks it.

**Comment by jozanza** [comment]
@yondonfu maybe you can get @ericxtang to walk you through the gitcoin bounty process for this one 👍

**Comment by Randy1Burrell** [comment]
@yondonfu will you still be doing gitcoin for this?
