### ISSUE TITLE
Improve content formatting on the /token page in the explorer

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#144]
**What's the problem? (required)**
When the information got moved from the /participate page, content formatting got lost. Bullets, links, emphasis, spacing, etc. 

**What's the current behavior? (required)**
Big blocks of text with no formatting to make them readable. The graphic from /participate that shows token release schedule also got lost.

**Describe a possible solution you've considered (optional)**
Reproduce the formatting from /participate

**Additional context (optional)**

https://cl.ly/2h273x0L2z1y

**Comment by iamonuwa** [comment]
@dob @ericxtang I would love to work on this task
