### ISSUE TITLE
Explorer - Transcoder View (transactions)

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#15]
Issue #13 defines a view for transcoder data. This should be actionable to let users actually bond and elect transcoders.

* Show token balance and bonding status for the user's web3 enabled account (Metamask, Parity, web3 to local node, etc).
* Add a bond button that lets them specify how much LPT they'd like to bond.
* Add a button next to each transcoder that allows them to delegate towards that transcoder.

These steps could potentially be combined into one step. Purely show them who they're delegating to, and if they choose to delegate button there's a request that asks them how much total LPT they'd like to deposit/bond/delegate in total. This could generate all the necessary transactions under the hood.

**Comment by jozanza** [comment]
The first pass implementation has been deployed to https://explorer.livepeer.org :shipit:
