### ISSUE TITLE
Embedded Player Dimensions Doesn't Match Real Video Dimensions

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#152]
**Describe the bug (required)**
The dimensions of the embedded player doesn't match the real video dimensions.

**Expected behavior (required)**
The player dimensions should adapt to the video dimensions.

**To Reproduce (required)**
1. Embed the video player on a website
2. Try to stream to it with different dimensions

**Device (required):**
 - Any browser
 
**Screenshots (optional)**
<img width="1667" alt="screen shot 2018-07-14 at 11 03 50 am" src="https://user-images.githubusercontent.com/345743/42723038-74bd2bf8-8756-11e8-8854-81cba0d71528.png">

**Comment by Randy1Burrell** [comment]
@ericxtang is this still an issue?

**Comment by Randy1Burrell** [comment]
@ericxtang some updates were made to the player a few months back. Is this still an issue for you?

**Comment by ericxtang** [comment]
Verified - no longer an issue.
