### ISSUE TITLE
Token miner page gives error on Firefox/Metamask/OS X

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#153]
**Describe the bug (required)**
This was originally reported by @darkdarkdragon.

> I've tried to claim LPT (using explorer.livepeer.org), but I've got this error: Sorry, mining is unavailable at this time. Please try again later. ReadableStream is not defined

This is after clicking the start mining button.

```
Error: "Subscription field must return Async Iterable. Received: [object Object]"
got error: 0 resolveHash ReadableStream is not defined resolveHash/</</<@blob:https://explorer.livepeer.org/27363662-a65e-c746-acf1-7fce688898a9:4058:23
27363662-a65e-c746-acf1-7fce688898a9:4198:13
Loading  from ipfs... 0
```

> I'm on firefox 61.0.1 with metamask 4.8.0 on MacOs

**Expected behavior (required)**
Mining should begin at this point.

**To Reproduce (required)**
1. Open Firefox
2. Unlock Metamask
3. Visit explorer.livepeer.org/token
4. Click start mining button

**Device (required):**
 - Device: Mac
 - OS: OS X
 - Browser Firefox
 - Version 61.0.1
 - Metamask 4.8.0

**Comment by darkdarkdragon** [comment]
@dob [worker.js](https://github.com/livepeer/livepeerjs/blob/master/packages/merkle-miner/src/worker.js#L176) uses `ReadableStream` object, but in Firefox this api should be [explicitly enabled](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreaml)
after enabling, mining process started

**Comment by Randy1Burrell** [comment]
@dob and @darkdarkdragon is this an actual cross browser issue or can we work around it by detecting the user's browser and ask them to enable readable stream?

**Comment by darkdarkdragon** [comment]
@Randy1Burrell I've looked checked it on windows machine - it too needs readable stream to be enabled. this is instruction from mozilla's site : `this feature is behind the dom.streams.enabled preference (needs to be set to true) and the javascript.options.streams preference (needs to be set to true). To change preferences in Firefox, visit about:config`
without this mining will not work at firefox

**Comment by dob** [comment]
I don't know enough about `ReadableStream` or the JS stack, but it's pretty crazy that we would have to ask a user to enable an experimental browser flag in order to download and parse a file.

Any other way we can see around this without a major rearchitecture effort?

**Comment by darkdarkdragon** [comment]
@dob quick look into google shows that there is [polyfill](https://github.com/jonnyreeves/fetch-readablestream), but I don't know if it will work out of the box in our case - need to be tested

**Comment by Randy1Burrell** [comment]
@dob and @darkdarkdragon the next best bet might be to remove `ReadableStream` all together. Polyfill might be a great future solution but I am hesitant about introducing new dependencies at this stage.

**Comment by darkdarkdragon** [comment]
@dob @Randy1Burrell giving that that this code anyway lives inside worker thread, `ReadableStream` can thrown out without consequences, I think

**Comment by Randy1Burrell** [comment]
@dob one of the issues I am finding difficult to deal with is that the dapp downloads [woker.js](https://github.com/livepeer/livepeerjs/blob/master/packages/merkle-miner/src/worker.js#L176) as a dependency from [this url](https://gateway.ipfs.io/ipfs/QmbiSa3PSXwRw6aoCRUcEDB4F2c9jvz2UMZJJbyetPA9aY) every time the user clicks Earn LPT. The difficulty in dealing with this is that when I edit the file locally the dapp doesn't test the local version. I'm now thinking that it would be much easier if it was working from local api.

Is there anyway for me to edit the file on ipfs?

**Comment by dob** [comment]
@Randy1Burrell you can not edit the file from IPFS, but I don't see any reason why the file has to be served from IPFS. It could be served from another static server like S3...or it could probably just live in the app itself...though I'm not sure if there's a good reason why it doesn't in the first place.

**Comment by Randy1Burrell** [comment]
@dob I have no Idea why it wasn't served locally but for a quick patch it's probably best I don't touch the way it's served or else I would have to tinker with the current architecture. I will look into the S3 idea for testing purposes.

**Comment by Randy1Burrell** [comment]
@dob and @darkdarkdragon I have commented out the `ReadableStream` from a new [worker.js](https://gateway.ipfs.io/ipfs/QmU3aMRGAHahFoP8aC2jHiMb3DcqZ43myLx3ZPN4dfYYXZ) file on IPFS and pointed the MerkleMining to this file. It works well, but, unfortunately that is just a temporary solution. When I implement the phase where I give users the option to mine their own account then I will be forced to find a permanent fix.

You can test this from the test link in our chat and let me know if it works for you too.

**Comment by Randy1Burrell** [comment]
@dob and @darkdarkdragon I'm closing this. If this becomes an issue again then we can reopen it.
