### ISSUE TITLE
Rinkeby explorer without Metamask

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#156]
**What's the problem? (required)**
Can't use the Rinkeby explorer without Metamask.

**What's the current behavior? (required)**
The default network for the explorer is mainnet and I don't see a way to change that without setting Metamask to use rinkeby.

**Do you have any personal experiences dealing with this problem? (optional)**
Some people run with Metamask disabled as a matter of security. If we want to check out the Rinkeby explorer, that involves enabling Metamask (and later disabling it). This is not a very convenient workflow.

**Describe a possible solution you've considered (optional)**
Something like `rinkeby.explorer.livepeer.org` to take us to the Rinkeby explorer (and maybe vice versa with `mainnet.explorer.livepeer.org`). The `explorer.livepeer.org` could still retain the current auto-select behavior.

**Comment by Randy1Burrell** [comment]
@j0sh How about adding a selection menu that you can use to switch to rinkeby that only shows up when MetaMask is disabled?

**Comment by adamsoffer** [comment]
We now have a dedicated rinkeby subdomain. https://rinkeby.explorer.livepeer.org/
