### ISSUE TITLE
The status bar is not aligned with the boarder lines for smaller screen sizes. 

### ISSUE THREAD

**Issue by bijanshahrokhi** [livepeer/livepeer-monorepo#161]
See attached. 
<img width="435" alt="screen shot 2018-07-30 at 5 23 58 pm" src="https://user-images.githubusercontent.com/26103938/43425753-891870b2-9421-11e8-8298-0e9466192773.png">

**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
@bijanshahrokhi This is caused by the button failing to resize based upon default styling placed on it. I will change this soon.

**Comment by Randy1Burrell** [comment]
@bijanshahrokhi This is done.
