### ISSUE TITLE
Enable the user to merklemine their own account. 

### ISSUE THREAD

**Issue by bijanshahrokhi** [livepeer/livepeer-monorepo#163]
Recycle existing self-claim flow that was developed earlier for the slow start. Link to it from the FAQ page. Raffi to provide content. 

**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by dob** [comment]
Just mentioning that this web based experience functionally lets people merkle mine their own account in case you want to point people there as a stop gap. It is a rough user experience however and we moved away from it towards the in-explorer flow: https://ipfs.io/ipfs/QmUvAFQZxbgMCqCMLUSj2kQBpZUhj5qi8KhmPDVvv9apfj

**Comment by bijanshahrokhi** [comment]
Randy, 
Is tehre anything that needs to be done (development wise)? Can we recycle what existed before?

**Comment by Randy1Burrell** [comment]
@bijanshahrokhi Yes we can but it still require me to write a small amount of code to get it working.

**Comment by Randy1Burrell** [comment]
Closing this.
