### ISSUE TITLE
Fix typo  - replace "unlciamed" with "unclaimed" in mining - page 2 - initializing stage. 

### ISSUE THREAD

**Issue by bijanshahrokhi** [livepeer/livepeer-monorepo#165]
**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
This has already been done. @ericxtang just needs to update the new push.
