### ISSUE TITLE
Update step 2 of "How it Works" as described below. 

### ISSUE THREAD

**Issue by bijanshahrokhi** [livepeer/livepeer-monorepo#166]
Since "Edit" is not coming back, let's update the content of step 2. 
Change title from "Select Mining Parameters" to "Start Mining" and changing the message body from "Select your gas price. If your gas price is too low, the transaction might take longer or miners might not process your transaction." to "Click on Earn LPT to start mining. You can change the gas price from your web 3 wallet. If your gas price is too low, the transaction might take longer or miners might not process your transaction."

**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
@bijanshahrokhi this is done
