### ISSUE TITLE
Get rid of ":" that is after "Hardware / Software Requirements" in How it Works page

### ISSUE THREAD

**Issue by bijanshahrokhi** [livepeer/livepeer-monorepo#167]
**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
This has been done.
