### ISSUE TITLE
Tooltips are inaccurate on the explorer

### ISSUE THREAD

**Issue by gjgd** [livepeer/livepeer-monorepo#170]
**Describe the bug (required)**
Tooltips on https://explorer.livepeer.org/transcoders are inaccurate (see screenshots below)
- First tooltip should say "top 15" instead of “top 10"
- Second tooltip is at the wrong place. It should appear on hovering the Reward Cut column

**Expected behavior (required)**
Tooltips are accurate (for the first one) and at the right place (for the second one)

**To Reproduce (required)**
1. Go to https://explorer.livepeer.org/transcoders
2. Hover the mouse on 'active' for the first and second Transcoders

**Device (required):**
 - Device: MAC
 - OS: MacOs High Sierra
 - Browser: Firefox 
 - Version 61.0.1 
 
**Screenshots (optional)**
<img width="1335" alt="screen shot 2018-08-02 at 19 03 32" src="https://user-images.githubusercontent.com/7913565/43605210-f9673e48-9697-11e8-90da-76071df779d7.png">
<img width="1347" alt="screen shot 2018-08-02 at 19 03 44" src="https://user-images.githubusercontent.com/7913565/43605216-fb24cb88-9697-11e8-8bed-c04c6bba72dd.png">

**Comment by Randy1Burrell** [comment]
@gjgd Thanks for reporting this issue. 

- I will change to "top 15".
- Maybe this is because I am using Linux but the second tooltip seems to appear where it should whenever I test it. Was there any special condition in your browser environment when this happened?

**Comment by gjgd** [comment]
I don't see the second tooltip error either now. Maybe it was just a bug on my machine at the time

**Comment by Randy1Burrell** [comment]
Ok great. @gjgd Thank you for clearing that up.
