### ISSUE TITLE
MerkleMine and MultiMerkleMine not being included in the SDK.

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#171]
**What is this discussion about? (required)**
MerkleMine and MultiMerkleMine not being included in the SDK.

**What do you hope to learn by the end of this discussion? (required)**
How MerkleMine and MultiMerkleMine being included in the SDK would help Livepeer's users build long term decentralised applications that uses the Livepeer network. 

**Additional context**
After a discussion on Friday August 3rd 2018 with Livepeer's core team about why MultiMerkleMine and MerkleMine should not be included in the SDK (because they are not a part of the core protocol being developed by the team). We arrived at a decision that for now, they would not be included in the SDK for the following reasons:

-  The SDK is for developing long term dapps on the Livepeer protocol.
- The MerkleMine and MultiMerkleMine is not a part of the core protocol and will end in 15 Months or when all LP tokens have been mined (this would not be long enough to be considered long term).
- The cost of maintaining dapps that would depend on LPs SDK for MerkleMining when the MerkleMine has ended would outweigh putting it in in the first place (think about it in terms of Python2 and Python3 which is causing some Python2 developers headaches to update their Python2 dependent modules to Python3).
- Being packed with features is not what makes an SDK great. What makes an SDK great is having the right feature that helps developers develop great application without too much fuss when upgrading to its new SDK to get more features.
- A blog or forum post could be written about the merklemine contracts and how to program with them if documentation is needed about these contracts.

**Comment by f1l1b0x** [comment]
yes it is not needed since the whole mining project most likely is over before the SDK ships

**Comment by Randy1Burrell** [comment]
Can we close this issue if everyone agrees?
