### ISSUE TITLE
Use eth_estimateGas RPC call to set default gas limit for transactions

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#174]
**What's the problem? (required)**

Instead of hardcoding default gas limits within the graphql-sdk, we can use the `eth_estimateGas` RPC call to set the provided gas for transactions (users will still always be able to modify the gas limit using their wallet UI).

**What's the current behavior? (required)**

Ethereum transactions submitted from the explorer currently leverage graphql-sdk mutations which invoke the relevant contract functions defined in the SDK. The graphql-sdk hardcodes the default gas limit provided for many transactions (ex. https://github.com/livepeer/livepeerjs/blob/master/packages/graphql-sdk/src/resolvers/Mutation.js#L55). While this works fine in most cases, in the event that the gas usage increases for a particular contract function changes, the hardcoded default gas limit would need to be modified as well. An example of this happening in practice is #168.

**Comment by Randy1Burrell** [comment]
@yondonfu have this been fixed in #175? If so let's close it.

**Comment by yondonfu** [comment]
Nope - the PR you referenced just increased the hardcoded gas limit for a particular transaction. I'm suggesting using the `eth_estimateGas` RPC call to help determine the gas limit (could add a small % extra as a buffer to be safe) when submitting any transaction

**Comment by Randy1Burrell** [comment]
Ok I will add this to the sprint board.
