### ISSUE TITLE
When player is embedded using iframe, it doesn't go fullscreen

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#178]
**What's the problem? (required)**

When I load a webpage which has livepeer's player embedded in an iframe, and then click the "full screen" button (![image](https://user-images.githubusercontent.com/2212651/43825191-65fc28ec-9af4-11e8-9cf9-05d8572f4469.png) bottom right), the player does not fill the screen, instead it fills the iframe (if indeed it isn't already filling the iframe)

**What's the current behavior? (required)**

When I **have not** clicked on the "full screen" button ![image](https://user-images.githubusercontent.com/2212651/43825197-6aa23094-9af4-11e8-8550-d59d77f772af.png), it looks like this:

![image](https://user-images.githubusercontent.com/2212651/43825010-db9ea968-9af3-11e8-80d9-756acee32174.png)

When I **have** clicked on the "full screen" button ![image](https://user-images.githubusercontent.com/2212651/43825197-6aa23094-9af4-11e8-8550-d59d77f772af.png), it looks like this:

![image](https://user-images.githubusercontent.com/2212651/43825044-ef4f4508-9af3-11e8-9147-d33291141a53.png)

**Do you have any personal experiences dealing with this problem? (optional)**

Yes. I have embedded livepeer.tv into the website for [ETHIndia hackathon](http://ethindia.co), and when I click "full scree" ![image](https://user-images.githubusercontent.com/2212651/43825197-6aa23094-9af4-11e8-8550-d59d77f772af.png), it just fills up the frame reserved for the iframe :{

**Describe a possible solution you've considered (optional)**

When a user clicks the "full screen" button ![image](https://user-images.githubusercontent.com/2212651/43825197-6aa23094-9af4-11e8-8550-d59d77f772af.png), it should use the whole screen to show the content.

**Additional context (optional)**

The ability to embed livestreams is one of Livepeer's primary differentiators compared with YouTube Live / Facebook Live. Having it work very well is important as we seek to lure content publishers away from the Google mothership.

**Comment by saskakol** [comment]
Hi @chrishobcroft! Just add the `allowfullscreen` attribute to the iframe element 😄 
So your iframe could look like this, for example: `<iframe width="240" height="160" src="https://media.livepeer.org/embed/0x0ddb225031ccb58ff42866f82d907f7766899014/?maxWidth=100%&aspectRatio=16:9" allowfullscreen></iframe>
`

Maybe this should be added to the player's embed code dialog by default...

**Comment by Randy1Burrell** [comment]
@chrishobcroft does the suggestion by @iSasFTW work for you? If so can we close this? Or should we allow full screen by default first?

**Comment by chrishobcroft** [comment]
Yes, @Randy1Burrell, I believe @iSasFTW provided the best solution.

Is there a gist or a post or something about how to make a Livepeer iframe?

It feels like it could be useful for people embedding streams in their pages.

**Comment by chrishobcroft** [comment]
Shall we close this once there's a document which explains it?

**Comment by Randy1Burrell** [comment]
@chrishobcroft I haven't seen a document that speaks about this. I will look into creating one in the coming week and close out this issue. I will also look into allowing fullscreen by default.

Once these thing have been done then we can close it. Adding this to Livepeerjs weekly sprint now.

**Comment by Randy1Burrell** [comment]
@chrishobcroft [here is a gist that describes how to solve this issue](https://gist.github.com/Randy1Burrell/d2374b3f0a49562115bb9aa95d4dca77)
