### ISSUE TITLE
Present following content once all tokens are mined. 

### ISSUE THREAD

**Issue by bijanshahrokhi** [livepeer/livepeer-monorepo#179]
As presented on this page. 

https://preview.uxpin.com/5497e6dac9138fd9dc7fd14e6dfb9fd0a2105e55#/pages/90831273/simulate/no-panels?mode=i

**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
This issues was fixed in PR #198.
