### ISSUE TITLE
Update sdk to support new pay with ETH and supported functions

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#18]
See this PR in protocol which updated some methods in bondingManager and jobsManager to support paying fees in ETH: https://github.com/livepeer/protocol/pull/136/files

* Two separate methods for withdrawing: `withdraw()` -> `withdrawFees()` and `withdrawStake()`
* New functions named `pendingStake()` and `pendingFees()`
* `deposit()` is now payable and accepts ETH instead of using `approve()` and then `transferFrom()`

If you have any questions @yondonfu can definitely point you in the right direction. Now broadcast from the web or mobile could easily be metamask or status enabled without requiring Livepeer token.

**Comment by jozanza** [comment]
`deposit()` has been updated to use ETH instead of ERC20 token approval/transfer.

The Delegator schema has been updated to reflect to renaming of `unbondedAmount` to `fees`.
