### ISSUE TITLE
Apollo and Merkle-Miner aren't published publicly to npm

### ISSUE THREAD

**Issue by ya7ya** [livepeer/livepeer-monorepo#186]
**Describe the bug (required)**
when installing `@livepeer/explorer` , npm throws a 404 error on `@livepeer/apollo` and `@livepeer/merkle-miner` , when checking npm, the libraries don't appear to be there or aren't published since it redirects me to the npm login page.

**Expected behavior (required)**
`npm install` should work as expected.

**To Reproduce (required)**
1. create fresh clone of this project
2. go to `./packages/explorer` 
3. `npm install --verbose`
4. wait for that `404` error

**Device (required):**
 - OS: Linux
 - Version `master@4d4f6cda8d65f4dd96e9e3a1c155465b0b7ff827`

 
**Screenshots (optional)**
![screenshot from 2018-08-20 12-39-262](https://user-images.githubusercontent.com/932163/44336816-ec29e700-a478-11e8-813e-bd8f7d6bb211.png)

**Console logs (optional)**
```
npm http fetch GET 200 https://registry.npmjs.org/tmpl 3ms (from cache)
npm http fetch GET 404 https://registry.npmjs.org/@livepeer%2fmerkle-miner 9373ms
npm http fetch GET 404 https://registry.npmjs.org/@livepeer%2fapollo 9466ms
npm http fetch GET 404 https://registry.npmjs.org/@livepeer%2fmerkle-miner 2117ms
npm http fetch GET 404 https://registry.npmjs.org/@livepeer%2fapollo 2279ms
npm info lifecycle web3@0.20.7~prepack: web3@0.20.7
npm info lifecycle web3@0.20.7~postpack: web3@0.20.7
npm verb stack Error: 404 Not Found: @livepeer/merkle-miner@^1.0.0-alpha.5
npm verb stack     at fetch.then.res (/home/op/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/home/op/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/home/op/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/home/op/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

```

cc @ericxtang

**Comment by ericxtang** [comment]
Ahh right... I guess the `MerkleMiner` not being published to npm makes sense (I don't foresee anyone using it as a component to build other apps, and it'll go away after the MerkleMine period is over), but maybe `apollo` should be published.

What's your suggestion on fixing this issue @ya7ya ?

**Comment by ya7ya** [comment]
@ericxtang , for now I solved it by using `npm link` on the missing libraries.

**example:** 

```
$ cd ./packages/apollo
$ npm link
$ cd ../chroma
$ npm link ../apollo
$ npm install --verbose
```

**Comment by Randy1Burrell** [comment]
@ya7ya can we close this?

**Comment by ya7ya** [comment]
@Randy1Burrell Yeah, I'll go ahead and close it 👍
