### ISSUE TITLE
Put "Earn LPT" above the fold

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#189]
**What's the problem? (required)**

The button to "Earn LPT" is our main "call to action" on https://explorer.livepeer.org/mine

Yet it appears below the fold of the page.

This means that someone must scroll to see it.

In this world of distraction, sometimes that's just too much to expect from people.

**What's the current behavior? (required)**

The "Earn LPT" button appears with small writing off the bottom of the page, with limited visual cues to guide the viewer to the gold.

**Do you have any personal experiences dealing with this problem? (optional)**

I don't see it when I load the page:

![screenshot from 2018-08-20 23-25-10](https://user-images.githubusercontent.com/2212651/44367564-705b8900-a4d0-11e8-9c1b-44791a71716d.png)
Also, perhaps someone can show this page to a UX / UI designer and give them some LPT for their opinions? Just an idea.

**Describe a possible solution you've considered (optional)**

Put the "Earn LPT" button at the top of the page, to make it easier for a viewer to see, and then to click.

Also, colour it GREEN, and use the Livepeer colour palette with more energy :)

![livepeer_colors](https://user-images.githubusercontent.com/2212651/44367885-5bcbc080-a4d1-11e8-90c6-0f10255b492a.png)

Perhaps take some inspiration from Amazon... they have teams of MBAs working on putting the "Add to basket" button in the best place.

![screenshot from 2018-08-20 23-31-00](https://user-images.githubusercontent.com/2212651/44367858-4191e280-a4d1-11e8-8be2-17ac5aad502f.png)

**Additional context (optional)**

I love you all.

**Comment by Randy1Burrell** [comment]
@chrishobcroft this might throw off people who visit the page. They may not see the instructions on the page and a big green button at the top of the page might not look welcoming to visitors. I wouldn't want to give the wrong impression.

If you agree, then can we close this issue?

**Comment by Randy1Burrell** [comment]
@chrishobcroft I am closing this issue because there is less than 8% of tokens left so updating the UI now to move the button might not be the best thing to do.
