### ISSUE TITLE
New channel player not loading on mobile

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#19]
On mobile the channel based player hangs on loading the stream, and never actually makes a request to get any segments for the stream. Tested in Safari and Brave browser.

**Comment by dob** [comment]
Looks like it's not working in Safari or Firefox either. On Firefox we're getting audio but no video and on Safari the video won't load. When I revert back to this commit: c0ee5a765519b40c55a5d91a2e7e487121556a22, it works in Safari

**Comment by dob** [comment]
This was further isolated. If you broadcast via the CLI, it only plays in Chrome desktop. FFMPEG + our m3u8 files must be doing something that's not quite according to spec.

If you broadcast using OBS, it plays in all desktop browsers, but not currently on mobile.

**Comment by jozanza** [comment]
Closed by https://github.com/livepeer/livepeerjs/commit/a0d39deca34d0c329a970029761d13fcaa72a9ea
