### ISSUE TITLE
Add Reward Call Via Supermax Endpoint

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#192]
**What's the problem? (required)**
When a token holder is making the delegation decision, # of missed reward calls is not exposed.  As a result, people just look at "Total Stake".  We don't want this to happen.

**What's the current behavior? (required)**
No information about reward calls is in the "transcoders" tab of the explorer.

**Do you have any personal experiences dealing with this problem? (optional)**
The best way currently is to use Supermax, which is a very high-barrier action.

**Describe a possible solution you've considered (optional)**
We can use the Supermax API endpoint to load the reward information.  Try it with:
```
curl -X POST \
  https://supermax.cool/supermax/api/v1/activity/livepeer/aggregateCallCountByAccountOverRounds \
  -H 'Authorization: hello@world.com:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvQHdvcmxkLmNvbSIsIl9pZCI6IjVhMTBjMzllNTQ2ZWZiMDc1MWEwYWUzYyIsImlhdCI6MTUxMTA1MDE4NH0.oIe738oMRmez_NI5U4-w9L0LiCjkssJ6f9KtbX9_N_k' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
  "network":"mainnet",
  "startRound":1000,
  "endRound":1101,
  "ethcallName":"reward",
  "accountAddresses":["0xbd91c9df3c30f0e43b19b1dd05888cf9b647b781", "0x4f4758F7167B18e1F5B3c1a7575E3eb584894dbc"]
}'
```

I propose we start with a simple metrics of "# of missed reward calls in last 30 rounds".  This can be queried with a single query to the Supermax API.

**Comment by Randy1Burrell** [comment]
This has been worked on and pushed to production. Closing this, @ericxtang you can reopen if this has not been implemented.
