### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by blake41** [livepeer/livepeer-monorepo#194]
I was attempting to retrieve all the jobs of a broadcaster (getjobs).  
getjobs shows a params object with a number of properties but omits broadcaster as a key i can pass in.  if you look at the actual code this is documented there but not in the docs.

also:
I assumed the "job object" returned 
would be what is documented in the getjob function, but some information seemed to be missing.

I'd add some details to the docs which explain what yondon wrote to me:
"Ah so getJobs actually retrieves the job information from events so the results will not contain the full information for an on-chain job. You can query for the full information using getJob and providing the ID of the relevant job (which you'll have from the results from getJobs). One additional catch...the transcoder field of the on-chain job will only be populated if the assigned transcoder has submitted an on-chain claim which will store the transcoder's address with the on-chain job. Until then, the transcoder field is empty because the transcoder is assigned after the job is actually created - the SDK does not expose that function right now, but internally it would be calling this contract function https://github.com/livepeer/protocol/blob/master/contracts/bonding/BondingManager.sol#L651"
maybe the easiest solution is to just show the keys in the job objects returned in the array?

Also, when I look at the streamId that comes back from the job objects, they look like the manifest id with some additional info appended.  It would be nice if there was somewhere in the docs (not sure the best place for this) that sort of gives someone the lay of the land.  what do different terms mean in your ecosystem.  whats a streamid vs a manifestid. since manifestid is the uniqueid most people are starting with, how do i start learning more information about it via the sdk.  how can i find the right job if i only have manifest id (answer: take the first 132 chars of a streamid and match to manifest id) etc. or can we add manifestid to that object that gets returned?

**Comment by adamsoffer** [comment]
Closing since `getJobs()` has been deprecated as of streamflow.
