### ISSUE TITLE
Open Booking Form for crypto.livepeer.tv - Open Channel for ETH startups

### ISSUE THREAD

**Issue by Matlemad** [livepeer/livepeer-monorepo#196]
**What's the problem? (required)**
There's a **growing demand** from ETH startups to stream their meetups and workshops on Crypto.livepeer.tv (LPtv's second channel). Normally they ask us, Livepeer.tv freelance crew in Berlin, to do it. I believe there's a potential demand that Livepeer could meet directly, by opening a Booking Form on the channel.

**What's the current behavior? (required)**
They ask us, Livepeer.tv freelance crew in Berlin, to help them stream with our equipment. Sometimes they even fly us to other destinations to do it. Although this condition can be sometimes very remunerative, I believe LP should address this interest directly. This would create much more resonance in the environment.

**Do you have any personal experiences dealing with this problem? (optional)**
I always recommend these startups the DIY-streaming solution by providing knowledge of the basic equipment, OBS software and procedure, and by explaining them the importance of having someone trained to do that, in-house, or a friend streaming-company near their location to work with.
When they want to give it a try themselves, I give them the stream key for crypto.livepeer.tv separately, along with a pre-compiled email stating responsibilities and duties of using such private informations.

**Describe a possible solution you've considered (optional)**
_We should open crypto.livepeer.tv to startups and streaming companies, as a temporary thematic channel to livestream their ETH and BC related happenings. In a perfect scenario, every startup in the ETH community will have a www.startup.io/livestream section on their website, where an embedded Crypto.livepeer.tv player runs non-stop. Sponsoring each others, directly website to website
without passing through YT._

Crypto.livepeer.tv landing page should therefore have:

**book a slot feature / Calendar subpage
sign-in/txn to prove identity
disclaimer "LP is not responsible for malicious content/third party violations etc"
release of a Stream key valid for a specific time only.**

**BOOKING FORM**
Let me link you to an example I bumped into recently, as I'm looking for venues for a tour in September.
http://www.theearlybird.at/at/en/booking
it's a bar in Innsbruck, Austria, they have this clear (but in German!) form where they lead you through the rules of the self booking, and at the end there's a calendar widget that shows the availabilities.
I believe that in our case this very last part could definitely be connected to the already existent Google Calendar for Crypto. And allows LP to disclaim any responsibility on the content side.

**ID VERIFICATION**
we might still need a certain degree of human verification to make sure that behind e.g. StartupXYZ there is a active startup, member of the ETH Community (and not villains).
But I also think that a simple transaction could solve the ID problem.
Maybe the StartupXYZ could be asked to do a gas txn, copy the txn number somewhere (on their website?) as a stamp?

**TEMPORARY STREAM KEY**
This is, I suppose, the most tricky part.
So, once the whole booking and ID verification is accomplished, Crypto should release privately and securely a streaming key that allows the applicant to access to Crypto.livepeer.tv for the reserved slot and proceed to stream their Meetup (if the stream happens 18:00 to 20:00, it's suggested to reserve 19:00 to 21:00)

**Comment by saskakol** [comment]
Not at all sure about the temporary stream key, but I'd love to help with building the front-end 😃 
Also, I'm guessing this isn't intended to be an entirely decentralized system? (It can just interact with a centralized server/calendar provider)

**Comment by ericxtang** [comment]
@iSasFTW @Matlemad I think we can come together to do a small brainstorming.  This issue relates to a larger point that I've been thinking for a while, which is that we should have a homepage for livepeer.tv

I think this will help establish livepeer.tv as an application built on top of Livepeer, and create more freedom of experimentation (sign-up forms, different channels, different geo-locations, etc).

@chrishobcroft what do you think about this?

**Comment by saskakol** [comment]
@ericxtang Yeah, that's a good idea. There's a lot of potential with creating a custom webapp for livepeer.tv. Besides, i would say that the logical course of action when building this issue(the booking system) would be to create a whole new page anyway, rather than extend the existing player to only have the feature when browsing a specific channel. (in this case crypto.livepeer.tv)

And i think having livepeer.tv as a separate app will also help with "bootstrapping" app development for livepeer, by acting as a sort of example for developers to start building their own content.

**Comment by Matlemad** [comment]
@iSasFTW do you mean a Tv App, with one channel and a menu where Crypto Community can book their slot and stream live 24/7 ?

I think it's important to limit to a target audience also for testing reasons.

This App could be downloaded/installed using a zero ETH txn (but gas), through Metamask.
maybe this could work as some sort of identity proof: every individual download will have its own hash.

I think laptop as a target device in terms of app optimisation for streamers (as there are quite a few pieces of complexity behind a livestream. OBS, Audio Inputs, etc.) 
Mobile version could be as simple as a player for viewers, with a few basic interaction features 
like throwing carrots or spanking @chrishobcroft 

a few simple profile features for Companies, Startups and Coops to add their logos, name and links.
but mainly a Feature Open Source Channel, with a shared calendar.

and if you want to go a bit down the marketing line, everytime the viewer-TvApp opens on a device,
that session is sponsored by one of the Startups of the community, which freely donate something to support the costs of crypto.livepeer.tv

**Comment by saskakol** [comment]
@Matlemad By “app” I meant a web app (website) rather than a native app. And like @ericxtang said, it could be a site for all of Livepeer.tv. That way Livepeer.tv could have it’s own customized player pages for the different channels. (One for crypto with a booking system, one for the main channel, etc.)
And since Livepeer is encouraging developers to build their own apps that utilize Livepeer/livepeerjs, that website could be used as a sort of example project to give developers an idea of what they could build.

**Comment by Matlemad** [comment]
@iSasFTW got it, sounds amazing to me. 

any idea regarding the temporary streaming key for the booked slot?

Actually I thought, URL and Stream key could remain the same.
in OBS, under "Stream" Settings is possible to tick an "identification" box with username and password.

![screen shot 2018-08-26 at 20 08 12](https://user-images.githubusercontent.com/35381854/44631454-0af21700-a96c-11e8-8f87-631fed10fefc.png)

Maybe at the smartcontract/registration time for the given slot, a company can register their username, and once confirmed the slot on the calendar, a temporary password is given, valid for that time window only.

**Comment by saskakol** [comment]
@Matlemad Yeah, that could be a good idea, but i'm not sure if the livepeer server supports authentication like that. To be honest i don't have any idea about the temporary streaming keys, somebody more knowledgeable might be able to answer that.

**Comment by ericxtang** [comment]
@iSasFTW currently the media server doesn't respect stream keys and don't have RTMP stream authentication.

A possible next step here can be:
1. Create a livepeer.tv homepage.  It can be a simple landing page with an embedded google form that allows people to request for a stream key.  The livepeer.tv app hardcodes a list of `EthKey => ingest IP` maps as broadcasting address to ingest node location.
2. Create an "admin" panel for the dapp that allows an administrator to create a new stream for a specific Ethereum key (new transcoder job on the blockchain). This can either be done by exporting the key into Metamask, or by exposing a "job creation" endpoint on the ingest node. It should generate a new stream key and a job ID.
3. The new stream key can be used to create the custom RTMP url (`rtmp://some-host.com:1935/stream?hlsStrmID=id`), and be emailed to the requester to use for their streaming.
4. Change the player to accept 2 URL parameters: "broadcasterAddr" and "jobID".  The app uses them to query the job from the blockchain and find out about the streamID.  It can then use the streamID to talk to the CDN to get the video stream.  This URL is used to view the stream (broadcaster can tweet it out, embed the player in a webpage, etc).

The only "infrastructure" that has to be provided is running the ingest nodes (which we already do).

**Comment by Matlemad** [comment]
wow @ericxtang, great to hear.

I have only one question, to which URL would the stream be directed for viewers to watch?
it would help this usage trend spread if there was a possibility to generate something like name.livepeer.tv

**Comment by saskakol** [comment]
@Matlemad It would probably just be livepeer.tv or (subdomain).livepeer.tv, but those would be set to point to the new website instead of media.livepeer.tv

**Comment by Randy1Burrell** [comment]
@Matlemad have this issue been solved for you? If so I would like to close it.

**Comment by Matlemad** [comment]
@Randy1Burrell  I think there is still the need for an open channel to be made available for ETH community. I'm not that familiar with Github yet. If we close this, would these infos be still retrievable?
thanks

**Comment by saskakol** [comment]
@Matlemad Yeah, the issue wouldn’t disappear or anything, it just wouldn’t show up in the main open issues tab. I think this should actually have its own repository, separate from livepeerjs, considering it would be a separate project.

**Comment by Matlemad** [comment]
Right. Then I think we have added everything we needed!

**Comment by chrishobcroft** [comment]
@iSasFTW I agree that something like this could have it's own repository, as it is a big enough project / service that it could exist as a separate entity.

This can be a place to start to define how it all might work, e.g.

Design
- Brand / Name
- Project Brief,
- UX / UI,
- Graphic Design,
- Architecture

Build
- Back-End Development
- Front-End Development

Operate
- Hosting
- Monitoring

@Matlemad will you set up a repository for this project?
