### ISSUE TITLE
Update web3 instance access strategy

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#197]
**What's the problem? (required)**

Metamask and other dapp browsers will stop injecting an Ethereum provider/web3 instance in a few months and instead users will have to actively approve the injection of a web3 instance.

For more details see the following links:
- Metamask announcement: https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8
- Relevant EIP: https://eips.ethereum.org/EIPS/eip-1102

We should adopt the new pattern for interacting with a web3 instance in the browser.

**What's the current behavior? (required)**

The explorer (and other livepeerjs based apps) rely on on an injected web3 instance from dapp browsers.

**Additional context (optional)**

Since the change with dapp browsers will not be for another few months, this issue isn't immediately pressing, but I am creating it now to make sure we are aware of it such that we can incorporate the necessary changes such that the explorer is ready when the dapp browsers make the breaking change.

**Comment by saskakol** [comment]
I noticed this a while back when working on the player, but i was told to just use injected web3 for now. But it shouldn't be too much of a hassle to fix, right? (Just adding the web3 library manually, and changing the code to make it request an external web3 provider?)

**Comment by yondonfu** [comment]
Yeah I don't think the fix should require too much work based on the description of the new pattern in the linked blog post - instead of automatically detecting an injected web3 instance, the application can request for user approval which posts a message that will prompt for web3 injection. UX might slightly change to provide users the ability to approve the use of a web3 provider when they land on the page.

**Comment by saskakol** [comment]
@yondonfu Is Metamask's pattern to actually request Web3 injection? If i remember correctly, Mist started using a pattern where the DApp has to add the web3.js library, and the browser only injects the provider. Are Metamask and Mist doing the same, or is Metamask's approach different?
