### ISSUE TITLE
Player - Fallback CDN Support

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#2]
Just like the existing web player, we need fallback support to a gateway node + CDN combo so that non-Livepeer users can consume streams.

I know it may not be trivial out of the box with the current channel based player. But at least the fallback should work as it does currently if the streamID is provided directly. Perhaps different URL patterns/routes for invoking the player?

Another option is to extend the gateway server to actually be able to handle a channelID request and serve up a stream.

**Comment by jozanza** [comment]
You got it. I think working directly with streamID's should be fine for now.

**Comment by dob** [comment]
Closing this, as the player currently falls back to the CDN. There's a separate issue for local stream support #4
