### ISSUE TITLE
Refactoring Views and TokenMiner component to 250 lines or below

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#200]
**What is this discussion about? (required)**
Refactoring the TokenMiner component in Mining view, Token, Transcoders and AccountOverview views. 

**What do you hope to learn by the end of this discussion? (required)**
I want to find an approach for reducing the lines of code in the view/module.

**Additional context**
File TokenMiner.js has 422 lines of code (exceeds 250 allowed). Consider refactoring.
TokenMiner has 24 functions (exceeds 20 allowed). Consider refactoring. 
Found in packages/explorer/src/views/Mining/TokenMiner.js 

> Some methods are not used so those can be deleted.

https://codeclimate.com/github/livepeer/livepeerjs/pull/159#issues

**Comment by ericxtang** [comment]
This is probably not needed anymore.  Can we close it?
