### ISSUE TITLE
There is currently no documentation to show developers how to use the graphql-sdk  

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#201]
**What's the problem? (required)**
https://github.com/livepeer/livepeerjs/tree/master/packages/graphql-sdk has no documentation for how to use the graphql-sdk.

**What's the current behavior? (required)**
The README has pretty good type documentation, but no guidance on how the graphql-sdk could be used to develop video streaming applications.

**Do you have any personal experiences dealing with this problem? (optional)**
Explaining the package to every developer can be time-consuming and it's best practice on Github to put any critical info into READMEs.

**Describe a possible solution you've considered (optional)**
Update README.md with instructions on how to use the graphql-sdk to build software applications.

**Additional context (optional)**
Example code maybe found in packages/explorer/src/views/Bond/enhance.js and creativity for building streaming apps are only limited to what the network can handle and what has been included in the SDK itself. [Another good example](https://github.com/ya7ya/hlsjs-lp-loader)

**Comment by adamsoffer** [comment]
Closing since the `graphql-sdk` package has been archived in favor of the subgraph.
