### ISSUE TITLE
Media Player Intermittently Hangs

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#203]
**Describe the bug (required)**
The media player intermittently hangs when loading the video.

**Expected behavior (required)**
The media player should quickly figures out whether the video is play-able, and display the correct information.

**To Reproduce (required)**
Simply launch the media player.

**Device (required):**
 - Desktop browser
 
**Screenshots (optional)**
https://gist.github.com/ericxtang/c973a48c47bbe29aefd6f6272bc211b7

**Additional context (optional)**
This is a slightly complex problem.
* Partially it's because of the way the media player gets a job from the blockchain (it uses eth_getLogs to query the last 1,000,000 blocks for events that include the current broadcaster address).  Pretty inefficient.
* Partially it's because of Infura's infrastructure (based on regions so the call timeout behavior depends on where you are in the world and the current load in that region)

I think https://github.com/livepeer/livepeerjs/issues/199 would help with this issue.  In the mean time, we can try and reduce the # of blocks down to 50,000 (still over 8 days).  Note this would still cause issues, but it will at least reduce the load on Infura.

**Comment by j0sh** [comment]
Even better would be to avoid a blockchain lookup entirely. See https://github.com/livepeer/go-livepeer/issues/556

This would also allow for off-chain viewing of streams.

**Comment by Randy1Burrell** [comment]
@ericxtang did PR #243 fix this issue?

**Comment by j0sh** [comment]
We should also be able to use `currrent.m3u8` with non-localhost hosts, otherwise the feature can't be used with hosted players, eg livepeer.tv, crypto.livepeer, etc.

**Comment by Randy1Burrell** [comment]
@j0sh should we create a new issue for this or just reopen #208?

**Comment by iameli** [comment]
I believe this and and #208 are irrelevant once #320 gets merged.

**Comment by iameli** [comment]
Obviated by #320
