### ISSUE TITLE
`@livepeer/sdk` works with import but not require out of the box

### ISSUE THREAD

**Issue by ya7ya** [livepeer/livepeer-monorepo#206]
**Describe the bug (required)**
```javascript
// works
import LivepeerSDK from '@livepeer/sdk'
console.log(typeof LivepeerSDK === 'function') // true

// doesn't work
const { LivepeerSDK } = require('@livepeer/sdk')
console.log(typeof LivepeerSDK === 'function') // false
```

this happens because the function in question is actually called `createLivepeerSDK` but exported this way

```javascript
export default async function createLivepeerSDK(
  opts: LivepeerSDKOptions,
): Promise<LivepeerSDK> {
```

this is apparently not picked up by `require` , so in order to get it to work now we gotta use this

```javascript
const LivepeerSDK = require('@livepeer/sdk').default // works fine
```

**Expected behavior (required)**
both `require` and `import` should work out of the box

**To Reproduce (required)**
1. run code in the description section.

**Device (required):**
 - Device: Laptop (browser, webpacked)
 - OS: Ubuntu
 - Browser : Chrome, firefox

**Possible enhancement**

- rename `createLivepeerSDK` to `LivepeerSDK` to avoid confusion
- or mention this explicitly in the docs.

**Comment by Randy1Burrell** [comment]
@ya7ya Great idea. A few questions though.
- Would this break any application that currently depends on the LP SDK?
- Could we do something like: 
```
async function createLivepeerSDK(
  opts: LivepeerSDKOptions,
): Promise<LivepeerSDK> {.....

export {  createLivepeerSDK, createLivepeerSDK as LivepeerSDK }
```

Just to make sure there is backwards compatibility. Then in a few months we deprecate this. Not sure the code is right but just asking if this might be a better solution.

**Comment by ya7ya** [comment]
Yeah, That's a good point @Randy1Burrell , We should probably do that. I'll check if that solves it and submit a PR

**Comment by Randy1Burrell** [comment]
@ya7ya great, thanks! Can we assign this to you and put it in sprints--> in progress?
