### ISSUE TITLE
Marking stream as dead after 4 segments is leading to disrupted streams

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#21]
I was watching the Livepeer tv replay, and the stream was playing fine. However the player kept killing it after seeing the same end segment 4 times. A refresh would have it immediately playing fine again for awhile. 

I'm not sure the best algorithmic fix, but it feels like it's either polling too quickly, or that it would be better off trying more than 4 times. Either way the experience was disrupted when it didn't need to be, and it didn't detect good new content coming in, so there's probably a better heuristic to use.

Buffering isn't ideal...but even if the segments were slow to arrive, buffering then resuming would be better than marking permanently dead.

**Comment by jozanza** [comment]
All the custom logic is gutted now. The bug in the node that was working around is resolved now (https://github.com/livepeer/go-livepeer/issues/224). This issue should be fixed by https://github.com/livepeer/livepeerjs/commit/a1cd9c2d0598a3467a18472737f00491efb72e80
