### ISSUE TITLE
MultiMerkleMine txns are occasionally sending to the 0x000 address

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#210]
**Describe the bug (required)**
Two separate users have reported incidents where they've tried to mine LPT using the web based MultiMerkleMiner, and the txns get submitted to the "to" address of 0x0000000..., the null address. This attempts to create a new smart contract and fails.

**Expected behavior (required)**
It should have a "to" address of the MultiMerkleMine smart contract.

**To Reproduce (required)**
I have not been able to reproduce. I assume it has something to do with the order that resources are loading, and for some reason it doesn't set the to address of the txn correctly.

See

https://etherscan.io/tx/0x527285ad64ad000ad7969208a8b34c96f9be417b2c25af3e802371831a8403b6

https://etherscan.io/tx/0x1b3ceeab53f5cd97f96fa3e2cee0a2d86f33138a066d8cd2aa9c282c1137cd56

https://etherscan.io/tx/0x6ee4920798a9e6bdec0975f29dee603a9746e5953d67b7224fdc5a364cea8b72

**Device (required):**
Metamask in Chrome is one confirmed environment.
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
@dob I have been investigating this bug but was unable to recreate it. I searched the database and found that the genesis address (0x0000000000000000000000000000000000000000) was some how included in the list of valid addresses. I did some research about it and had a discussion with @yondonfu who informed me that submitting proofs for this address can cause this bug. I have deleted this address from the database which I hope fixes this issue. 

We can close this issue and reopen it if anyone else has this problem.

**Comment by dob** [comment]
Ok. I would be surprised if that was the only cause because one user saw
this issue on 3 straight txns and the odds of that would be pretty low. But
it's possible! We'll keep an eye out.

**Comment by Randy1Burrell** [comment]
@dob I am going to continue investigating this bug.

**Comment by Randy1Burrell** [comment]
@dob let's close this issue. We can reopen if this bug reappears.
