### ISSUE TITLE
Lack of precision in formatted LPT/ETH amounts leads to user confusion

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#211]
**Describe the bug (required)**

The [formatBalance](https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/utils.js#L80) helper is used in various places in the explorer to create a formatted string representing an amount of LPT/ETH. The function accepts a `decimals` parameter to specify the level of precision to use when representing the input amount which defaults to 8. At the moment, the default level of precision is used which leads to cases where the value displayed to the user is 0 even when the actual input amount > 0.

See:

- https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/views/AccountDelegating/index.js#L137
- https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/views/AccountDelegating/index.js#L129

**Expected behavior (required)**

If the user has an amount of LPT/ETH > 0, she does not see 0 displayed in the UI.

**To Reproduce (required)**
1. Navigate to the delegating tab in the explorer for an account that has bonded stake that cannot be represented with the default level of precision used by `formatBalance`
2. Observe that the displayed stake in the UI is 0 even though the actual bonded stake > 0

**Device (required):**
 - OS: OSX
 - Browser: Brave

**Comment by Randy1Burrell** [comment]
@yondonfu I am not able to reproduce this issue. Can you give a little more details on this?

**Comment by yondonfu** [comment]
Here is an example:

On Rinkeby, I bonded 10000000000 LPTU (base units of LPT where 1 LPT = 10^18 base units).

When I approve that amount prior to bonding, the transfer allowance modal says that I approved 0 LPT:

![screen shot 2018-10-08 at 10 05 42 am](https://user-images.githubusercontent.com/5933273/46623213-e9538600-cafa-11e8-8f52-d2fe510b14a2.png)

When I am bonded, the delegating page says that I have 0 LPT bonded:

![screen shot 2018-10-08 at 1 02 35 pm](https://user-images.githubusercontent.com/5933273/46623232-f40e1b00-cafa-11e8-9413-76cc79d595d0.png)

Since 10000000000 LPTU = 0.00000001 LPT which requires > 6 decimals to represent, the `formatBalance` helper used in various places in the explorer will just display 0 LPT.

**Comment by Randy1Burrell** [comment]
@yondonfu I have updated the code.
