### ISSUE TITLE
Developer Onboarding Documentation

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#213]
**What is this discussion about? (required)**
This discussion will be centred around developer on-boarding documentation.  

**What do you hope to learn by the end of this discussion? (required)**
I would like to learn developers' thoughts about what they would like to see for documentation concerning developer on-boarding. For example, some developer prefer getting started guides while others prefer to see readme.md files with method documentation, or some developer may say there should be a website dedicated specifically to developer docs, so let hear your thoughts.

**Additional Context**
Related to #201

**Comment by dob** [comment]
1) Is this issue aimed around a developer using Livepeerjs to build something? Or a developer contributing to the Livepeerjs codebase?

2) I believe that there were originally generated docs for the SDK layer, but haven't been able to locate them. Anyone know what happened to that generated doc site?

**Comment by Randy1Burrell** [comment]
@dob I think both contributing to Livepeerjs and being able to build an application with the SDK goes together. The way I look at it is, if you understand how Livepeerjs works then it will be pretty easy to contribute to it and build an application with it.

**Comment by jozanza** [comment]
Knowing the basics of the Livepeer protocol is also essential.

For LivepeerJS, API documentation already exists and is pretty thorough, but it's actually kind of difficult to know when or why you would call any particular method imho.

Additionally, it's also hard to know what sorts of things you could build with the SDK even if you can grok the method signatures and know the basics of Ethererum.

I'd advocate for more adding examples to codesandbox.io. Giving folks some demos of actual uses kind of helps put all those pieces together. And you might even see others fork the sandboxes or create their own.

**Comment by Randy1Burrell** [comment]
Thanks @jozanza I will look into your suggestion. Does anyone else have any suggestion on the matter?

**Comment by Randy1Burrell** [comment]
This can be closed because the issue to do the documentation is in progress.
