### ISSUE TITLE
Mining is unavailable due to lambda timeouts

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#216]
**Describe the bug (required)**
Users trying to use the web based MerkleMine are seeing "Mining is unavailable." The underlying lambda is timing out.

**Expected behavior (required)**
Mining succeeds

**To Reproduce (required)**
1. Go to explorer.livepeer.org/token
2. Unlock Metamask
3. Try to mine with default configuration
4. Observe the issue

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**
The lambda is possibly timing out because it has to check too many accounts to see if they are mined or not? Or possibly because of Infura limiting queries/connections?

**Comment by Randy1Burrell** [comment]
I fixed it. Closing this.
