### ISSUE TITLE
Create Partial Unbonding UI Spec

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#221]
**What's the problem? (required)**
Currently the protocol supports partial unbonding, but the explorer UI does not.

**What's the current behavior? (required)**
No partial unbonding.

**Describe a possible solution you've considered (optional)**
Let's create a spec for how we plan to expose partial unbonding in the UI.

**Additional Context**
[See](https://github.com/livepeer/LIPs/issues/5) for details of the discussion.

**Comment by Randy1Burrell** [comment]
This is finished
