### ISSUE TITLE
Plan to deal with issues that are pilling up

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#222]
**What is this discussion about? (required)**
Issues are pilling up in LivepeerJs repo.

**What do you hope to achieve by the end of this discussion? (required)**
I feel the issues on LivepeerJs needs to be dealt with promptly. Over the next few weeks I will be trying to decrease these issues to a maximum of 10 issues remaining. The objective here is to make sure the cracks in the foundation of LivepeerJs are fixed before they are built on top of.   

**Additional context**
I will be going over the issues in the following order

**Week 1 -- October 1 - 5**
Work on livepeer/livepeerjs#221 livepeer/livepeerjs#211 livepeer/livepeerjs#203 livepeer/livepeerjs#213 livepeer/livepeerjs#201 livepeer/livepeerjs#208 livepeer/livepeerjs#178 livepeer/livepeerjs#174 livepeer/livepeerjs#172 livepeer/livepeerjs#170

**Week 2 -- October 8 - 12**
Work on livepeer/livepeerjs#182 livepeer/explorer#75 livepeer/livepeerjs#142 livepeer/livepeerjs#109 livepeer/livepeerjs#47 livepeer/livepeerjs#92

**Week 3 -- October 15 - 19**
Work on livepeer/explorer#74 livepeer/livepeerjs#106 livepeer/livepeerjs#105 livepeer/livepeerjs#69  livepeer/explorer#73

**Week 4 -- October 22 - 26**
Work on livepeer/livepeerjs#68 livepeer/livepeerjs#81 livepeer/livepeerjs#79 livepeer/livepeerjs#78 livepeer/livepeerjs#77

**Comment by chrishobcroft** [comment]
Hi Randy,

Well done on managing the livepeerjs repo, and the issues. If you would like some help with reviewing these, let me know if you would like to get on a call sometime next week to talk about them.

All the very best,

Chris

**Comment by Randy1Burrell** [comment]
@chrishobcroft Thanks for reaching out. How about we schedule a call sometime on Wednesday?
