### ISSUE TITLE
CI bot for Explorer and LP SDK among other things

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#223]
**What's the problem? (required)**
Deployment of dapps in Livepeerjs is cumbersome, manual and takes too long to be done. It depends on @ericxtang or someone else on LPs team who might already be busy solving problems to help move LP's projects forward.

**What's the current behavior? (required)**
You have to deploy the Explorer manually every time a change is made.

**Do you have any personal experiences dealing with this problem? (optional)**
I deployed the Explorer to staging environment a few times in the past. It would have been much better if it was automated.

**Describe a possible solution you've considered (optional)**
I have considered using [Hubot](https://hubot.github.com/) to help with automation of deployment.

**Additional context**
[Hubot](https://hubot.github.com/) has multiple use cases which can be automated and will save LPs team of engineers time in the long run.

**Comment by samparsky** [comment]
@Randy1Burrell Is this issue still open? I am willing to work on it

**Comment by Randy1Burrell** [comment]
@samparsky sure this is still open. [Here](https://github.com/Livepeer-Community-Node/Grant-Program) is a program where you could submit a proposal and get compensated for helping out.

**Comment by adamsoffer** [comment]
Deployments are now made automatically on PRs via vercel.
