### ISSUE TITLE
Gas Ptice?

### ISSUE THREAD

**Issue by RobbieRich** [livepeer/livepeer-monorepo#224]
Sorry, mining is unavailable at this time. Please try again later. Error getting addresses from server. This might be a netwok problem. Please try again later. If the problem persists contact livepeer administrators in their discord group. 
This is the message i am getting ! What am I doing wrong ? eth 0.25 gas price 15

**Comment by Randy1Burrell** [comment]
@RobbieRich Thanks for reporting this issue. It should be fixed now, you can test it and let me know.
