### ISSUE TITLE
media.livepeer.org won't load on Brave Browser mobile

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#23]
For some reason the Brave Browser on mobile won't load media.livepeer.org. It just looks like it's freezing while connecting for awhile and then gives up. 

It works on brave desktop.

**Comment by chrishobcroft** [comment]
Also on Chrome on Android

**Comment by jozanza** [comment]
@chrishobcroft just created a newer version of this issue with the ISSUE_TEMPLATE format, so I'm going to close this issue and we can track this problem in https://github.com/livepeer/livepeerjs/issues/64
