### ISSUE TITLE
Show round number  with txn reward history

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#230]
**What's the problem? (required)**
On a transcoder's transaction history page, we can see when they call reward on a round. However, it's not as straightforward to determine which round that call applies to. For example, some days reward is called twice, some days are skipped, etc. This may be due to skew, but it's hard to tell. Being able to see the round number along with the reward call would help when gauging a transcoder's reliability. 

**What's the current behavior? (required)**

No round number is shown along with the reward transaction.

![image](https://user-images.githubusercontent.com/292510/46306223-8432ea00-c568-11e8-88ce-ca152893d6b8.png)

**Describe a possible solution you've considered (optional)**

Change the message to `Claimed inflationary token reward for round <N>`

**Comment by dob** [comment]
Since the `Reward()` event doesn't contain round number, if the transaction metadata has access to the block number I guess it could just calculate what round the event was called in by dividing the block number by `RoundLength` or 5760.

**Comment by adamsoffer** [comment]
The new explorer displays the round number that a transaction occurred in in the history tab.
<img width="395" alt="Screen Shot 2020-02-05 at 10 14 41 PM" src="https://user-images.githubusercontent.com/555740/73902822-091cca80-4865-11ea-9a74-2953ce4a7fc4.png">
