### ISSUE TITLE
Fetch maxEarningsClaimsRounds value from BondingManager

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#233]
**What's the problem? (required)**

The explorer hardcodes 20 as the max number of rounds that a delegator can claim earnings for in a single transaction. Instead, the explorer should fetch the `maxEarningsClaimsRounds` parameter from the BondingManager contract so that even if the parameter value changes, the explorer will still be able to craft transactions that use the updated parameter value as the max number of rounds that a delegator can claim earnings for in a single transaction.

**What's the current behavior? (required)**

The explorer hardcodes 20 as the max number of rounds that a delegator can claim earnings for in a single transaction - see: https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/views/ClaimEarnings/index.js#L30

**Describe a possible solution you've considered (optional)**

The SDK already contains a getter function [getMaxEarningsClaimsRounds()](https://github.com/livepeer/livepeerjs/blob/master/packages/sdk/src/index.js#L746).

The [Protocol](https://github.com/livepeer/livepeerjs/blob/master/packages/graphql-sdk/src/fragments/Protocol.js) GraphQL query could be updated to contain the output of this getter function in the result. The query would then be used in the explorer to retrieve `maxEarningsClaimsRounds`.

**Comment by yondonfu** [comment]
#245 adds support for dynamically fetching `maxEarningsClaimsRounds` from the BondingManager contract. However, there are still a few areas in the explorer where the UI displays a hardcoded value of 20 and also blocks bonding related transactions if the user has more than 20 rounds of unclaimed earnings. These hardcoded values should also all be removed in favor of using the value fetched from the BondingManager.

**Comment by yondonfu** [comment]
Reopening to track the above comment

**Comment by Randy1Burrell** [comment]
@yondonfu where in the explorer are these hard coded values?
