### ISSUE TITLE
Running out of Gas when attempting to bond

### ISSUE THREAD

**Issue by kingjacob** [livepeer/livepeer-monorepo#234]
Used the gas limit(650K) and gas price suggested by metamask and ran out of gas.
<img width="742" alt="screen shot 2018-10-03 at 10 39 34 am" src="https://user-images.githubusercontent.com/806312/46428376-a5c2db80-c6f8-11e8-88af-356681336339.png">

Only thing I can think of is maybe the gas limit calculation is off because it includes 20rounds of claims?

Edit: Nope, manually raised the gas limit to 750,000 and that worked and it used fewer gas than the previous
<img width="460" alt="screen shot 2018-10-03 at 10 40 01 am" src="https://user-images.githubusercontent.com/806312/46428396-b4a98e00-c6f8-11e8-9295-12fa7ebda7bb.png">

**Comment by dob** [comment]
I also saw that we have run out of gas on the default `initializeRound()` txn lately, despite it using slightly less than the offered gas. I think we should address this by increasing the default offered gas for:

* bond(): 750000
* initializeRound(): 3200000

**Comment by Randy1Burrell** [comment]
@dob PR #237 merged yesterday fixes this so I'm closing.
