### ISSUE TITLE
Deploy the protocol explorer

### ISSUE THREAD

**Issue by jozanza** [livepeer/livepeer-monorepo#24]
@dob @ericxtang @yondonfu https://explorer.livepeer.org sound good to you guys?

**Comment by dob** [comment]
Yes!

**Comment by yondonfu** [comment]
🚀

**Comment by jozanza** [comment]
Woo this is done! You can see it at https://explorer.livepeer.org

But I'm going to avoid making a big announcement as I would to to take some time to do some QA with the team and fix any major issues first. MetaMask vs no MetaMask / http vs https seems to consistently cause small bugs and ux issues. I'd love help reporting any bugs!
