### ISSUE TITLE
unbounded but no LPT

### ISSUE THREAD

**Issue by yugobiz** [livepeer/livepeer-monorepo#241]
hi, i just unbounded from delegate but why my lpt balance 0 ?

0x558d1e16b69be5323595d948632446011276771f1a5626ac088ec42c50659ece

cann someone help?

**Comment by Randy1Burrell** [comment]
Hey @yugobiz, when you unbond your tokens are held by the smart contract for a period of 7 days before being released to you.

**Comment by Randy1Burrell** [comment]
@yugobiz closing this issue. Please let us know if you have any other questions.
