### ISSUE TITLE
Allow users of Livepeer Explorer to claim 100 rounds of Earnings

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#247]
**What's the problem? (required)**

Users of explorer.livepeer.org are only able to claim up to 20 rounds of earnings at a time.

Since the recent protocol change, it should be possible to claim up to 100 rounds in one go.

**What's the current behaviour? (required)**

In the cases where a user has not claimed for between 21 and 100 rounds, they must submit multiple transactions (up to 5), in order to claim all their rewards to-date.

This can be tedious and costly in terms of gas.

**Do you have any personal experiences dealing with this problem? (optional)**

Oh yes. Submitting 5 transactions when 1 would have been enough was an unnecessary hurdle to get over to be able to continue to operate.

**Describe a possible solution you've considered (optional)**

If a user's account has X rounds of earnings to be claimed, where X <=100, it should provide the option to "Claim X rounds of earnings".

If a user's account has >100 rounds of earnings, it should provide the option to "Claim 100 rounds of earnings"

In my user testing, user found the slider thing to be quite confusing.

**Comment by saskakol** [comment]
Is this just a UI change to allow of up to 100 rounds instead of just 20? And to be clear, it should rather be a number input box than a slider?

**Comment by chrishobcroft** [comment]
I don't know about technical details of the implementation, but my proposed solution is as above.

I personally don't find the slider to be so intuitive, and the user I just sat with had very little idea about what she was supposed to do with the slider.

It seems that we might be able to help guide a user a little more here: I feel that it's very likely that they will start with the objective of "claiming all earnings" so we should aim to evolve the interface to a) make the overall flow more intuitive by dynamically suggesting sensible values for "number of rounds to claim", and b) reduce the number of transactions they must submit by allowing them to claim up to 100 per transaction (increased from 20).

For example, my user has 149 rounds to claim. Claiming all of these (in order to bond more, rebond, or unbond), would currently take 7 transactions, each claiming 20 rounds and then one transaction claiming 9 rounds. This is 8 transactions and feels excessively arduous.

**Comment by yondonfu** [comment]
Just wanted to note that PR #245 will enable users to claim earnings for more rounds (does not make any additional UI updates aside from updating the max value of the slider).

> For example, my user has 149 rounds to claim. Claiming all of these (in order to bond more, rebond, or unbond), would currently take 7 transactions, each claiming 20 rounds and then one transaction claiming 9 rounds. This is 8 transactions and feels excessively arduous.

In this scenario, the last transaction to claim 9 rounds is actually unnecessary if the user intends to bond, rebond or unbond because any of those actions will also automatically claim the remaining rounds. This could probably be made more clear to users in the UI.

**Comment by Randy1Burrell** [comment]
@chrishobcroft this has been fixed. Closing this.
