### ISSUE TITLE
Dashboard doesn't show current round + unclaimed earnings

### ISSUE THREAD

**Issue by PetSte** [livepeer/livepeer-monorepo#253]
I keep having connection problems with the Livepeer dashboard. If I connect the hardware wallet  (Nano Ledger S) I use for bonding, via MetaMask to LivePeer, the dashboard can't seem to find the current round LivePeer is in and it won't show my unclaimed earnings ("0 LPT/0 ETH All caught up"). See attached pictures for more detail.

The dashboard **does** show my staking amount (initial stake+earned LPT), but the unclaimed earnings are not showing. The stake amount however is the balance of a couple of rounds ago, it should be higher now.

So there seems to be **a** connection between my wallet and the dashboard, but not a proper one.

I cleared the history/cache/etc as suggested, but this doesn't seem to fix the problem. The strange thing is that when I change MetaMask accounts (to an non-LPT, non-hardware account) it instantly shows the current LivePeer round; no other details though, since it doesn't contain LPT and isn't delegating.

Since starting delegating up until recently, I could simply press F5 each day and I'd see my daily received unclaimed earnings and updated total LPT stake get higher.

Would love to know how to make a proper connection so I can seen my balances again. There's no rush, because there are lots of rounds left till I reach round 100, but if this problem shows up to someone in round 95, nearing 100, he wouldn't know when he passes round 100 and isn't even able to claim his earnings, because according to the dashboard there are no unclaimed earnings.

Thanks in advance!

Extra info: I am staking for more than 20 rounds. I have never claimed anything, wanting to let it ride till 100 rounds. The fact that I am staking for more than 20 rounds however shouldn't be a problem, because the problem seemed to have started somewhere around Livepeer round 24, and up untill then everything was working properly and the earnings balance kept adding up. Besides according to your team it should be possible to let your earnings add up untill round 100 and then claim them.

![current round](https://user-images.githubusercontent.com/27784228/47947227-e2ad0880-df18-11e8-97fe-1b1c63e59157.jpeg)
![unclaimed earnings](https://user-images.githubusercontent.com/27784228/47947228-e2ad0880-df18-11e8-9d14-1ec1bb5599ba.jpeg)

**Comment by dob** [comment]
Thanks for reporting this.

1. Let's see if merging #251 fixes the connection issues, which may have more to do with latency and cacheing, and may be addressed by that big change. If it's still an issue after that we'll look back into it.

2. You can let your reward LPT go "unclaimed" for as many rounds as you'd like, including past 100 rounds. You won't lose anything by doing so. If the # of rounds is greater than 100 though, you'll need to submit 2 txns instead of 1 txn in order to do a bonded related action or claim earnings.

**Comment by Randy1Burrell** [comment]
@PetSte are you still having this issue?

**Comment by PetSte** [comment]
Yup, it's hard to make a connection with the blockchain via the dashboard sometimes. Sometimes the round counter (top left) stays grey with no current round, sometimes it's at the current round, but all my balances are incorrect/not showing and sometimes it simply works as it should. Switching pc/clearing caches etc sometimes works and sometimes doesn't, can be a real pain. Fortunately I finally managed to get all my LPT bonded so I am most likely set for at least a couple of months and I expect lots will be accomplished in that time frame.

Happy holidays! And if you need more info about this problem, feel free to ask!


-------- Oorspronkelijk bericht --------
Van: Randy Burrell <notifications@github.com>
Datum: 20-12-18 17:46 (GMT+01:00)
Aan: livepeer/livepeerjs <livepeerjs@noreply.github.com>
Cc: PetSte <peterstevens92@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [livepeer/livepeerjs] Dashboard doesn't show current round + unclaimed earnings (#253)


@PetSte<https://github.com/PetSte> are you still having this issue?

**Comment by adamsoffer** [comment]
Closing since the classic explorer has been sunsetted and this is no longer an issue.
