### ISSUE TITLE
The future of LivepeerJs workflow

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#257]
**What is this discussion about? (required)**
LivepeerJs future plans.

**What do you hope to learn by the end of this discussion? (required)**
Currently LivepeerJs has different packages that the explorer depends on in order to give Livepeer's community of users useful data to make critical decisions. The explorer also requires more frequent updates to its interface for features and bug fixes. Scheduled feature releases to both the SDK and the GraphQL SDK is also needed. For the past two weeks I have been structuring plans to modify LivepeerJs workflow, that will:

1. Get the explorer more updates and have issues fixed faster and deployed to production ASAP.
2. Fix broken experiences faster and make LivepeerJs more dependable.
3. Give the team the ability to have scheduled deployments.
4. Give users of Livepeer SDK and GraphQL SDK the ability to expect scheduled updates.
5. Deprecate outdated code, implement more current updates and get them deployed to production faster.
6. Implement greater test coverage to help improve dependability and decrease regression.
7. Increase documentation and create example tutorials for using Livepeer SDK and GraphQL.

> LivepeerJs needs to be ready for streamflow!!

## Proposals
Going forward there are some things about LivepeerJs that will need to be changed in order to get these plans implemented. These are:
1. Edit the contribution guide to make it more suitable for [git-flow workflow/PR](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) model where contributors only sends feature PRs to a development branch and all branches are named accordingly. 
* Ex. Branches that introduces features are called `feature/[NameOfFeature]`, this will help to allow more named tracking of code being merged into LivepeerJs.
* We can have the development branch merged to master on a scheduled basis by creating releases. 
#### This will also have the following benefits:
* `hotfix/[NameOfHotfix]` and `bugfix/[NameOfBugfix]` can be in production faster because reviewing these will take priority. 
* Circleci can be scripted to only build and deploy the release branches for the SDK and GraphQL SDK.
* The explorer can be deployed quicker with hotfixes and bugfixes because of the circleci automation script that I have worked on will be able to deploy to production quickly after merging to master.
* More structured schedule and versioning for releasing the SDK. 
2. Begin implementing tests for remaining packages in LivepeerJS and require new PRs that introduces features to have tests. 
* The explorer and the player have no test which can cause regression and introduce new bugs.
* The SDK could do with some more tests because a package that has over a thousand lines of code will require more than 30 tests to cover code regression and find bugs.
* The GraphQL SDK has some todo tests that needs to be implemented and other test needs to be added to cover more code.
3. Have a scheduled time for SDK/GraphQL releases `Biweekly/Mothly seems good for this`, updates to the explorer `weekly seems good for this` and automate the process  `this is already in the works!!`
* The Circleci configuration script I modified will be finished pending what we decide here!
* The git-flow workflow will make scheduled releases easier because we could have planned commits included and release packages on a weekly basis.
* There are some methods from the core Livepeer protocol still remaining to be implemented within the SDK rpc. These could have a schedule for release.
4. PRs should now be required to come with comments. I have found that packages in the explorer have minimal comments. This is important because:
* As engineers we tend to revisit code after a few days/months/weeks and have no idea what it does, even though it was written by us. Therefore, we end up spending more time than needed trying to relearn what's happening with specific areas of the code.
* Let's think about the guy who did not write the code but needs to understand it in order to modify your code.
* It creates less confusion as to what the code is meant to do and what it actually does and makes it easier to modify.
* Helps developers spend less time on reviewing code.
5. Along with the SDK and GraphQL SDK's scheduled release, documentation updates and examples should be involved. A separate package within LivepeerJs called tutorials that has code examples, explanations and links to sandbox environments such as JS Bin or JS Fiddle should be created. We should require that examples/tutorials of how these features can be used should be included with feature PRs. This will have the benefits of:
* Getting developers up to speed quickly about how to use LivepeerJs.
* Help grow the tutorials and user base.

**Additional context**
Please note that none of these are set in stone. They are just guides on how I think we should move forward. I am open to suggestions and comments!!

**Comment by ericxtang** [comment]
Thanks for making this proposal @Randy1Burrell.  I see that it's largely process-related.  I'm always supportive of good development process, so a lot of these sound good to me.  

I think aiming to have a bi-weekly/monthly release is good, but if we don't have anything important to release because we've been focused on something else, that's ok too.

Curious about the plan of adding tests to the explorer and the player.  What kind of tests are you thinking?

**Comment by Randy1Burrell** [comment]
@ericxtang thanks for the comments. I aim to add front-end unit and integration tests to the explorer and the player. I have found that these tests might be an issue with the new MetaMask security updates but I am sure I will be able to find a way around it. The React components in the player and the explorer also needs testing too. 

There is also the suggestion of using JS Bin or JS Fiddle to deploy tutorial code so that the developer community interested in using Livepeer's infrastructure for video transcoding can get up to speed quickly.

Fixing the explorer's experience means I will have to continue working on issue #222 and implement great UX while doing so and at the same time integrating this plan.
