### ISSUE TITLE
Overestimation of Gaslimit Needed for claiming staking earning

### ISSUE THREAD

**Issue by marczeller** [livepeer/livepeer-monorepo#259]
**What's the problem? (required)**
Claiming earnings is currently hard coded at 2.1M Gas units, that's a quarter of a Block !

Actual gas usage is a fraction of that : 
![image](https://user-images.githubusercontent.com/21088542/48491454-85ba2800-e81f-11e8-935c-17a03028b1bd.png)
![image](https://user-images.githubusercontent.com/21088542/48491562-c5810f80-e81f-11e8-80e0-e31bd3b7696a.png)

that's lead to terrible UX for several reasons : 
1)The User have a gas estimation cost on is Metamask UI completely false (several $ when they just pay cents) resulting of "i have to pay 5$ of gas to claim 0.5$ of reward ? what a scam !" reactions
2) Miners hate this kind of Txs you just ask them to squat a quarter of their block and end up paying only for a fraction, they loose money, they don't like that so longer confirmation time meaning bad UX

**Describe a possible solution you've considered (optional)**
Nobody like "Out of Gas", that's a UX nightmare and yep, unspend gas is paidback but the user doesn't know that and don't really care.

The amount of rounds of rewards we can claim is capped at 20

-the lazy solution is to hardcode the upper limit corresponding to 20 rounds claim (a bit less than 500k gas units if we are really conservative)

-Real solution? dive into the Appendix G of the yellow paper, suffer, understand that's it's completely outdated and you just wasted time, cry a little and do a lot of maths to figure it out ! 😸 

Good luck, i love your project !

**Comment by dob** [comment]
Thanks for the suggestions. Just adding a note that the protocol allows claiming up to 100 rounds at a time, and the UX of the explorer will be adjusted to allow this at some point soon.

It seems like a reasonable strategy would be to use the gas estimator + 20%, rather than a hardcoded value.

**Comment by marczeller** [comment]
Quite fair, https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethestimategas + 20% should be the best solution.

Thanks Doug!

**Comment by adamsoffer** [comment]
Closing since manually claiming earnings is no longer necessary as of LIP-36.
