### ISSUE TITLE
Network and address status indicators in explorer

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#26]
This is a small feature request. Not highest priority. 

I think that if the explorer is using some state about the user derived from an extension like Metamask, the UI should give them some sense of this. For example it should display what network they're connected to (Livepeer Testnet), and what their current address is. The address should perhaps be clickable to take them to their account address page (/me).

**Comment by jozanza** [comment]
This one's a bit tricky since web3 apparently doesn't actually expose any url info about the provider. (Please let me know if I'm wrong about that).

But I should at least be able to indicate whether the provider is being set by MetaMask or not.

**Comment by yondonfu** [comment]
`web3.version.network` https://github.com/ethereum/wiki/wiki/JavaScript-API#web3versionnetwork might help with the displaying the network name (it returns the network ID).

**Comment by jozanza** [comment]
@yondonfu do you know if there's any way a url can be derived from the `web3.version.network`? It seem to only return an integer.

**Comment by yondonfu** [comment]
I'm not aware of a way to derive a provider URL, but you could derive the network name from the network ID: https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids We're using 858585 for our test network

**Comment by jozanza** [comment]
I did some digging, and it look like these are the names and addresses of a few of the most common public networks, as well as our own:
```js
{
  1: 'Ethereum Main Network',
  2: 'Morden, Expanse Mainnet',
  3: 'Ropsten Test Network',
  4: 'Rinkeby Test Network',
  30: 'Rootstock Main Network',
  31: 'Rootstock Test Network',
  42: 'Kovan Test Network',
  61: 'Ethereum Classic Main Network',
  62: 'Ethereum Classic Test Network',
  858585: 'Livepeer Test Network',
}
```
Any others we should add? Or should we remove any?

**Comment by dob** [comment]
Looks good to me!

**Comment by jozanza** [comment]
Cool. The current network is shown on the landing page now. I’ll work on adding the current account + profile link soon!
