### ISSUE TITLE
Claim stake & fees button leading to empty page and GraphQL error

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#260]
**Describe the bug (required)**
When you attempt to "Claim Stake and Fees" from your account page in the explorer, it leads to a blank page. The console outputs a graphQL error.

**Expected behavior (required)**
The claim dialog should pop up.

**To Reproduce (required)**
1. With a staked Metamask account visit the "My Account" page in the explorer.
2. Click on claim stake and fees
3. Observe a blank screen. Viewing the console shows JS errors.

**Device (required):**
 - Device: Macbook Pro
 - OS: OS X
 - Browser: Reproduced in Chrome, Firefox, and Brave
 
**Screenshots (optional)**

https://cl.ly/7ae077bc8993

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by Randy1Burrell** [comment]
@dob I just redeployed a fix. Can you try again?

**Comment by Randy1Burrell** [comment]
Closing because this issue have already been fixed.
