### ISSUE TITLE
transcoder page doesn't load on Chrome with latest version of Metamask

### ISSUE THREAD

**Issue by marczeller** [livepeer/livepeer-monorepo#262]
**Describe the bug (required)**
https://youtu.be/xk4ScfISfZQ

i have made a video of the issue.
Metamask unlocked, metamask secure approved.
Bug only on Chrome, Brave work as expected.

**Comment by ericxtang** [comment]
Thanks for reporting this @marczeller!  Are you able to reproduce this issue consistently?  Could you share the javascript developer console output?
