### ISSUE TITLE
Explorer Transcoding View: Block reward cut and pending block reward cut should be given in %, not LPT

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#27]
The following issues reference the transcoder view for an address in the explorer:
https://explorer.livepeer.org/accounts/0xFeBF35b94e16E018Ab5cA9aA1f66aaC1a1AB29E0/transcoding

Viewable in this screenshot:
https://cl.ly/3C320Y2z1c2P (note that the address in the screenshot is different than above because it was using my local metamask address reported in issue #25)

## Expected Behavior
I expect the reward cuts to be given in %'s, not in LPT. I expect them to be 20%, as per the CLI.

## Current Behavior
They are listed as 0 LPT.

## Possible Solution
It's possible the explorer is pulling the wrong field to display that data. The CLI pulls it and displays it correctly.

## Steps to Reproduce (for bugs)

1. Visit https://explorer.livepeer.org/accounts/0xFeBF35b94e16E018Ab5cA9aA1f66aaC1a1AB29E0/transcoding
2. View the current and pending reward cuts. Note that they're listed as LPT and are incorrect.

## Your Environment

* Chrome on OS X, with Metamask running as the transcoder account.

**Comment by jozanza** [comment]
Fixed by https://github.com/livepeer/livepeerjs/commit/9e14e696a89282635669c80913f2964eea949e64
