### ISSUE TITLE
Errors while bonding tokens

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#271]
**Describe the bug (required)**
The explorer keeps giving different reason why I cannot bond my tokens. 
1. ETH balance too low.
2. Need to claim earnings.
3. Need to adjust my amount I can bond.

**Expected behavior (required)**
The explorer should allow me to bond my token.

**Device (required):**
 - OS: Linux
 - Browser Chrome

**Comment by dob** [comment]
Is this bug suggesting that those errors are reported but are untrue? They seem like valid errors in the case where they are true.

**Comment by Randy1Burrell** [comment]
@dob they are valid errors in the case where they are true. Just to be sure I will looking into whether or not it's a bug or a case where the explorer was correctly reporting my account's state.
