### ISSUE TITLE
Explorer Transcoding View: Fee shares are off

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#28]
The following issues reference the transcoder view for an address in the explorer:
https://explorer.livepeer.org/accounts/0xFeBF35b94e16E018Ab5cA9aA1f66aaC1a1AB29E0/transcoding

Viewable in this screenshot:
https://cl.ly/3C320Y2z1c2P (note that the address in the screenshot is different than above because it was using my local metamask address reported in issue #25)

## Expected Behavior
I expect the fee shares to be listed as a % less than 100.

## Current Behavior
They are listed as 100000%.

## Possible Solution
They are supposed to be listed as 10%. The protocol stores these values as a numerator which gets divided by the protocols percent-divisor of 1,000,000. The solution is likely to divide this value by % divisor to get the resulting .10 == 10%.

## Steps to Reproduce (for bugs)

1. Visit https://explorer.livepeer.org/accounts/0xFeBF35b94e16E018Ab5cA9aA1f66aaC1a1AB29E0/transcoding
2. View the current and fee shares. Note that they are listed as 100000%

## Your Environment

* Chrome on OS X, with Metamask running as the transcoder account.

**Comment by jozanza** [comment]
Fixed by https://github.com/livepeer/livepeerjs/commit/9e14e696a89282635669c80913f2964eea949e64
