### ISSUE TITLE
Spacing on the Account Overview tab is way off after Graph integration

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#282]
**Describe the bug (required)**
The spacing between the recent transactions is enormous on the Overview tab of the account pages in the explorer in the graph integrated version.

**Expected behavior (required)**
The recent txns should not have nearly this much space between them.

**To Reproduce (required)**
1. Go to http://explorer-staging.livepeer.org.s3-website-us-east-1.amazonaws.com/accounts/0x50d69f8253685999b4c74a67ccb3d240e2a56ed6/overview
2. View the space between the recent txns

**Device (required):**
 - Macbook Pro, OS X, Brave Browser
 
**Screenshots (optional)**

https://cl.ly/12896b6bd8a7

**Comment by Randy1Burrell** [comment]
Hmmm, I wonder about this. Seems we're using an outdated version of rmwc which this feature depends. I wonder if that is causing this bug, because I now realise that the options menu in the Navbar which also depends on rmwc is not opening either.

**Comment by adamsoffer** [comment]
@dob  @Randy1Burrell I've confirmed this is due to a breaking change in the `rmwc` package. Let's freeze that dependency version at `1.6.2`.
