### ISSUE TITLE
Rinkeby transcoder info not loaded based on graph node

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#285]
**Describe the bug (required)**
The explorer shows transcoder information from mainnet, even when the user switches Metamask to Rinkeby

**Expected behavior (required)**
Explorer should show Rinkeby transcoder information in this case.

**To Reproduce (required)**
1. Go to the explorer
2. Select "Rinkeby" in Metamask
3. Transcoder info is from mainnet

**Additional context (optional)**
This is caused by enabling of the graph node.  @adamsoffer - what do you think is the best strategy here?

**Comment by adamsoffer** [comment]
Nice catch. I'd say we have two options:
1. We can spin up a separate graph node that indexes Rinkeby events. ([The network is configurable in a graph node](https://github.com/livepeer/livepeerjs/blob/master/packages/subgraph/docker-compose.yml#L19)).
2. We can fallback from the graph-node to infura when the network detected is not mainnet.

Thoughts?

**Comment by adamsoffer** [comment]
For now, I'm leaning towards option 2 and falling back to infura whenever the network detected is not mainnet. We can always spin up another graph node for rinkeby down the line.

**Comment by Randy1Burrell** [comment]
Sounds good to me.

**Comment by Randy1Burrell** [comment]
PR #286 fixes this.
