### ISSUE TITLE
claim button missing for delegators in explorer

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/livepeer-monorepo#288]
**Describe the bug (required)**
The claim fee button is missing for delegators

**Expected behavior (required)**
As a delegator I want to use the claim fees button of the explorer at
https://explorer.livepeer.org/accounts/"transcoder"/delegating

**To Reproduce (required)**
1. Go to 'https://explorer.livepeer.org/accounts/0x481efb669b423cfaffa49890205427dea9b3d693/delegating'
2. With the unclaimed earnings tab you should see a  'claim' button if you are bodned to the transcoder and have outstanding fees not yet claimed, but it is missing.

<img width="380" alt="bildschirmfoto 2018-12-17 um 19 01 58" src="https://user-images.githubusercontent.com/32998038/50105919-70755680-022e-11e9-80f8-52b28d9997f4.png">

**Comment by dob** [comment]
I'm sensing a repeating pattern here, with the checkmarks in these UI components also disappearing.

**Comment by f1l1b0x** [comment]
@Randy1Burrell

**Comment by Randy1Burrell** [comment]
I'm looking into it. I am not yet able to recreate this bug.

**Comment by Randy1Burrell** [comment]
@f1l1b0x just to make sure I am looking in the right place is this the button that's not showing up?
![image](https://user-images.githubusercontent.com/10135939/50112395-2334bd00-020d-11e9-8b41-b52b52efac64.png)

**Comment by Randy1Burrell** [comment]
Also, what OS and browser are you using?

**Comment by f1l1b0x** [comment]
that is the right tab, OSX and latest chrome

**Comment by Randy1Burrell** [comment]
@f1l1b0x As per our discussion, there is not a bug here.

**Comment by f1l1b0x** [comment]
ugh @Randy1Burrell just showed me I am looking at the wrong page. to claim the delegator fees you need to go to https://explorer.livepeer.org/accounts/"delegator-address"/delegating
not https://explorer.livepeer.org/accounts/"transcoder"/delegating
