### ISSUE TITLE
Running YARN in Ubuntu 16.04.3 fails for livepeerjs

### ISSUE THREAD

**Issue by rayj00** [livepeer/livepeer-monorepo#29]
#### New Issue Checklist

- [x] I made sure the issue observed is not already reported by searching on Github under https://github.com/livepeer/livepeerjs/issues
- [x] I have filled out all relevant sections of this issue template

#### Expected Behavior

...

#### Current Behavior

Running yarn should install all of the dependencies I will need to run the Livepeer Player locally.
The YARN command is failing.

#### Possible Solution

...

## Build Media Player Locally

It is recommended on a fresh and updated version of Ubuntu 16.04.3 Server perform the following procedures.    Note these procedures may or may not apply to other Ubuntu versions.

**Install nodejs v8:**
 
	$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
	$ sudo apt-get install -y nodejs
   	
	$ node –v
     	  V8.9.4

   	$ npm –v
     	  5.6.0

## **Install YARN**	

With Yarn, developers still have access to the npm registry, but can install packages more quickly and manage dependencies consistently across machines or in secure offline environments. 

	$ sudo npm i -g yarn

	$ yarn –v
	  1.3.2

Per Josiah,  I ran the following two commands:
	$ sudo apt-get install libssl-dev)
        $ sudo apt-get install build-essential)

## **Install livepeerjs** 

	$ git clone https://github.com/livepeer/livepeerjs.git 
	$ cd livepeerjs 

Run YARN to install all of the dependencies
	
	$ yarn 

#### Context

I am trying to build the Livepeer player locally so I can then customize the webpage to fit the needs of prospective broadcasters. Executing the YARN command is failing. See console output below.

#### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

I am running Ubuntu 16.04.3 server.

#### Console Output

ray@LivepeerPlayer:~/livepeerjs$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/chroma > video-react@0.8.10" has incorrect peer dependency "react@^15.0.0".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/chroma > video-react@0.8.10" has incorrect peer dependency "react-dom@^15.0.0".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/chroma > babel-preset-react-app@3.1.1" has unmet peer dependency "babel-runtime@^6.23.0".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/chroma > react-addons-test-utils@15.6.2" has incorrect peer dependency "react-dom@^15.4.2".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/explorer > graphql-tag@2.6.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/explorer > react-redux@5.0.6" has unmet peer dependency "redux@^2.0.0 || ^3.0.0".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/player > recompose@0.26.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-ef6ed143-7973-4d0a-89df-70cc643bd594 > @livepeer/chroma > jest > jest-cli > jest-runtime > babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ yarn build
yarn run v1.3.2
$ ./bin/build.sh
./bin/build.sh: 1: ./bin/build.sh: Syntax error: "(" unexpected
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jozanza** [comment]
Looks like the installation completed, but the build failed. Seems like there's a syntax error on your command line. Must be an incompatibility between the shell on your OS and mine (OSX). For now, here's a workaround. From the root dir run the following:

```bash
cd ../@livepeer/sdk && yarn build
cd ../@livepeer/graphql-sdk && yarn build
cd ../@livepeer/chroma && yarn build
cd ../@livepeer/apollo && yarn build
```

I'll look into correcting that syntax error.

**Comment by rayj00** [comment]
Thanks Josiah.  Yep the work around worked as we proved last night.
Looking forward to the fix for the original YARN procedure.

**Comment by jozanza** [comment]
Hopefully, [this commit](https://github.com/livepeer/livepeerjs/commit/96051489d2717028063908ccf5cddc02b7917de1) fixes the issue. Mind doing a `git pull && yarn` to test it out @rayj00?

**Comment by jozanza** [comment]
Closed by https://github.com/livepeer/livepeerjs/commit/294d6268d9af0dc0e3893732e2a56fde89929359
