### ISSUE TITLE
Transcoder view shows old data before refreshing with latest data

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#292]
**Describe the bug (required)**
When I visit the transcoder view of a user account in the explorer, it sometimes shows old data, such as "last claimed round 995". Then after a few seconds it updates to show the recent, accurate data.

**Expected behavior (required)**
It should not show out of date data initially. It should either show a loading indicator, or nothing, or fresh data.

**To Reproduce (required)**
1. Go to https://explorer.livepeer.org/accounts/0xfb9849b0b53f66b747bfa47396964a3fa22400a0/transcoding
2. Observe old data, then see it refreshing to new data after a few seconds.

**Device (required):**
 - Device: Macbook Pro, OS X, Brave
 
**Screenshots (optional)**

See gif: 

https://cl.ly/6d9b473e5328

**Comment by Randy1Burrell** [comment]
@dob I wonder if caching has something to do with this issue? That alongside the Infura api data issue. If it does then only able to fix if infra improves or we move everything to the graph.

**Comment by dob** [comment]
Or updating the caching policy, right? Not saying that's top priority if it's a huge architectural change, but it would be a potential way to address the issue.

**Comment by Randy1Burrell** [comment]
Updating the caching policy might not fix this.

I think of it in terms of we caching data to load when Infura is down but in other cases when the data is outdated and Infura responds but takes too long then it will still show the outdated data. A solution I am looking at it is to refrain from loading data that's too old from cache unless Infura doesn't respond.

**Comment by Randy1Burrell** [comment]
#309 is related to this.

**Comment by adamsoffer** [comment]
Closing since the classic explorer has been sunsetted.
