### ISSUE TITLE
Unbonding Locks Component needed.

### ISSUE THREAD

**Issue by Randy1Burrell** [livepeer/livepeer-monorepo#296]
**What's the problem? (required)**
I am not able to manage my unbonding locks within the explorer.

**What's the current behavior? (required)**
No unbonding locks shows up within the explorer.

**Do you have any personal experiences dealing with this problem? (optional)**
Yes, when someone unbonds, whether partially or fully, the LP tokens are held within an unbonding lock for a period of 7 days. After 7 days passes then the token holder is able to withdraw or rebond their tokens. Currently the UX for this process is bad. Each unbond creates a new lock. See [this issue](https://github.com/livepeer/LIPs/pull/8) for more details surrounding unbonding locks.

**Describe a possible solution you've considered (optional)**
I would like to see users having the ability to manage their unbonding locks within the explorer's MyAccount Delegating page. A section would show up with all the user current and pending unbonding locks, where with the click of a button tokens can be withdrawn when a lock is ready or rebonded whether lock is ready or not. For this to happen a component is needed for helping to display and manage unbonding locks.

**Additional context (optional)**
Each unbonding lock should have two buttons, withdraw and rebond. The withdraw button should be disabled if the unbonding lock is not ready to be withdrawn and the rebond button is only enabled when the token have not been withdrawn or rebonded.  

![image](https://user-images.githubusercontent.com/10135939/50200621-a72d9880-0324-11e9-9dc7-844e3b524957.png)

**_Note:_** The styling of the unbonding lock component should follow the normal styling within the explorer.

Please see [partial unbonding](https://preview.uxpin.com/889b8e76042300f53aef82b29ff22567ebf6bcbf#/pages/98491956/simulate/sitemap?mode=i) and [fully unbonding](https://preview.uxpin.com/e339740dc9aa5862f4c7c88a3f1b6edfc1556b3f#/pages/98379007/simulate/sitemap?mode=i) for a walk through of the mock ups and user flow of how partial/fully unbonding should operate.

**Comment by samparsky** [comment]
Is this design okay?
<img width="961" alt="screen shot 2018-12-21 at 12 44 00 am" src="https://user-images.githubusercontent.com/8148384/50317052-e04b4180-04b9-11e9-9f57-6e86614f9c83.png">

**Comment by Randy1Burrell** [comment]
@samparsky sure that design if fine. At the section where you talk about the block number that the transaction occurred, we will replace that with the estimated date the user will be able to withdraw and until that date arrives and the unbonding lock is open then the withdraw button should be disabled.

**Comment by RaffiSapire** [comment]
@samparsky @Randy1Burrell the WITHDRAW button on the 30 LPT should be Greyed out, like it is in my design mockup. The text above is not correct - please make sure to use the text that is linked in the preview flow. If you hover over it, it should look like 
<img width="512" alt="screen shot 2018-12-26 at 10 18 06 am" src="https://user-images.githubusercontent.com/14640410/50450704-8acdc500-08fd-11e9-8961-bdc936d12a8d.png">

The hover format should be the same as it is with all other "i" hovers (question mark when you hover over it)
<img width="242" alt="screen shot 2018-12-26 at 10 59 47 am" src="https://user-images.githubusercontent.com/14640410/50450714-a042ef00-08fd-11e9-9324-92ceddf27b41.png">

**Comment by samparsky** [comment]
<img width="768" alt="screen shot 2018-12-27 at 1 11 16 am" src="https://user-images.githubusercontent.com/8148384/50460363-bd1b0900-0975-11e9-8589-e72031d031f1.png">

<img width="841" alt="screen shot 2018-12-27 at 1 17 16 am" src="https://user-images.githubusercontent.com/8148384/50460374-dfad2200-0975-11e9-8fa1-0475e98a215a.png">


The changes requested
