### ISSUE TITLE
Success dialog shows negative rounds to claim after claiming

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#299]
**Describe the bug (required)**
After claiming earnings, the Explorer success dialog says I have the same (but negative) number of rounds left to claim.

**Expected behavior (required)**
Zero should be returned, or the number of rounds actually claimed subtracted from the original remaining rounds. My guess is the "original remaining rounds" value is being reset prematurely.

**To Reproduce (required)**
1. Claim earnings. I had 83 unclaimed rounds. Claimed them all
2. Wait for tx to succeed
3. Success dialog pops up with "-83 rounds left to claim" 

**Device (required):**
Chrome OSX
 
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/292510/50303712-c91d3d00-0442-11e9-99ac-29c9bfff3fd3.png)

**Comment by adamsoffer** [comment]
Closing since the classic explorer has been sunsetted.
