### ISSUE TITLE
Player - StreamID Support

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#3]
If a Livepeer broadcaster or developer knows the streamID for their specific stream, they should be able to make it available via the player. The easiest way I can think of to support this is to handle the url pattern

`/stream/<streamID>`

Currently the player accepts the channelID, and uses it to parse through the blockchain logs to determine the streamID so that it can make a request to the CDN for the .m3u8 file based on the streamID. In the case of the streamID being provided directly, it can avoid all the searching and just make the request directly.

**Comment by jozanza** [comment]
I'm going to close this one out since I just made a comment about this on another issue: https://github.com/livepeer/livepeerjs/issues/58
