### ISSUE TITLE
[Fix] Update package @livepeer/sdk with latest changes

### ISSUE THREAD

**Issue by mariano-aguero** [livepeer/livepeer-monorepo#312]
**Describe the bug (required)**
The livepeer SDK package is not updated

**Expected behavior (required)**
There are missing properties, for example for the getDelegator () function, the fields `allowance, address, bondedAmount, delegateAddress, delegateAmount, fees, lastClaimRound, pendingFees, pendingStake, startRound, status, withdrawRound, nextUnbondingLockId` must exist.
Right now the fields `allowance, pendingFees, pendingStake` are missing. (Problably other functions also have missing fields)

**To Reproduce (required)**
1. Create a little project with node
2. Install the SDK, `npm i @livepeer/sdk`, version 1.0.0-alpha.5
3. Call getDelegator() function, example
```
  const { rpc } = await LivepeerSDK.default()
  const summary = await rpc.getDelegator(address)
  console.log(summary, 0 , 2)
```
4. Compare properties with the [docs](https://github.com/livepeer/livepeerjs/tree/master/packages/sdk#getdelegator)

**Device (required):**
 - Device: [Notebook]
 - OS: [Linux Ubuntu]
 - Version [18.04.1 LTS (Bionic Beaver)]
 
**Screenshots (optional)**
Screenshot actual package
![screenshot_20190117_102828](https://user-images.githubusercontent.com/1144028/51325177-18a75680-1a4b-11e9-9239-a63972fd2595.png)

Screenshot updated package
![screenshot_20190117_103155](https://user-images.githubusercontent.com/1144028/51325171-147b3900-1a4b-11e9-8c98-6b9858079aa1.png)

Command to build an updated package
![screenshot_20190117_103606](https://user-images.githubusercontent.com/1144028/51325185-1cd37400-1a4b-11e9-8179-e1a81ff12aac.png)

**Comment by Randy1Burrell** [comment]
@mariano-aguero I am currently setting up a pipeline for continuous deployment of the SDK to npm, so this should be updated in the near future.

**Comment by mariano-aguero** [comment]
Thanks @Randy1Burrell !! If you need help let me know, I can contribute

Regards

**Comment by mariano-aguero** [comment]
Relates to #314
