### ISSUE TITLE
Migrate to the new Infura Dashboard

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-monorepo#313]
Infura [will begin requiring a Project ID](https://blog.infura.io/infura-dashboard-transition-update-c670945a922a) generated from the new Infura Dashboard. **On January 23rd** requests using Dashboard-generated Project IDs will be prioritized over legacy keys during periods of high traffic activity. **On March 27** support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID. The livepeer SDK will need to update its infura endpoint to support this update. 

How to transition to the new update:
1. Register project with Infura and generate a Project ID
2. Update the [sdk infura endpoint](https://github.com/livepeer/livepeerjs/blob/5ebb90ec2562c3c5a96e1be81d712cc47887f507/packages/sdk/src/index.js#L103) to `https://mainnet.infura.io/v3/[PROJECT_ID]`

**Comment by iameli** [comment]
Fixed by https://github.com/livepeer/livepeerjs/pull/362
