### ISSUE TITLE
Can't view explorer after declining Metamask login

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#315]
**Describe the bug (required)**
My Metamask is active but not logged in. When I try to visit the explorer, I cancel the login prompt. All I see on the explorer page is a pink screen.

**Expected behavior (required)**
The explorer should be shown.

**To Reproduce (required)**
1. Activate Metamask, but don't log in
2. Visit https://explorer.livepeer.org/
3. Dismiss the login prompt
4. See a pink screen

**Device (required):**
Chrome OSX

**Comment by Randy1Burrell** [comment]
@j0sh This has already been fixed in [this PR](https://github.com/livepeer/livepeerjs/pull/306). It haven't been deployed yet though.
