### ISSUE TITLE
Fix "method_complexity" issue in packages/subgraph/src/mappings/bondingManager.ts

### ISSUE THREAD

**Issue by jozanza** [livepeer/livepeer-monorepo#326]
Function `bond` has a Cognitive Complexity of 9 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/livepeer/livepeerjs/packages/subgraph/src/mappings/bondingManager.ts#issue_5c5cb3505f8d4f000100019c

**Comment by iameli** [comment]
Uhhhhh. This happened when I hit "Create a ticket" in Code Climate to see what happened. This happened. Whoops!
