### ISSUE TITLE
Unbonding Status in Explorer Displaying Wrong Number

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#327]
**Describe the bug (required)**
The "Unbonding" panel in the "Staking" section of the explorer is displaying wrong information.  Here is the [link](https://explorer.livepeer.org/accounts/0x4f4758F7167B18e1F5B3c1a7575E3eb584894dbc/delegating).

<img width="390" alt="screen shot 2019-02-11 at 1 17 11 pm" src="https://user-images.githubusercontent.com/345743/52584229-856e0080-2dff-11e9-970e-7a46549e1d40.png">

**Expected behavior (required)**
A positive number is displayed for "round(s) left in the unbonding period"

**Comment by Randy1Burrell** [comment]
I believe this could be related to #299.

**Comment by adamsoffer** [comment]
Closing since the classic explorer was sunsetted.
