### ISSUE TITLE
Explorer - Pending price, reward cut, fee share are more important in transcoder election view than active values

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#33]
In the [transcoder election view](https://explorer.livepeer.org/transcoders) in the explorer, seeing the pending values is more important than the active values, since these are the ones which will be active next round that you can actually make decisions on.

If both values can't fit in the UI, then I'd propose displaying the pending values instead of the active values. But I'm open to debate in this issue.

**Comment by chrishobcroft** [comment]
I agree 100%
