### ISSUE TITLE
"Value too low" appears too frequently when bonding token

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#332]
**Describe the bug (required)**
While bonding token in the explorer, a "value too low" error appears even when the value is not too low.

**Expected behavior (required)**
Not that. Except maybe if the field is negative?

**To Reproduce (required)**
1. Go to bond token
2. That field will autofill with your LPT balance
3. It will say "too low"

**Comment by adamsoffer** [comment]
Closing since the classic explorer was sunsetted.
