### ISSUE TITLE
Bonding fails when there are over 15 decimal places

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#336]
**Describe the bug (required)**
This bug was reported to me via email.

> We’ve had a new bug come up in the past few weeks. When we try to bond our LPT with a transcoder, it fails when there are over 15 decimal places. The error we get is “rpc error with payload.”

**Expected behavior (required)**
Bonding should succeed

**To Reproduce (required)**
I don't have full reproduction steps.

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]

**Comment by dob** [comment]
More info:

> The workaround I’ve found thus far is to remove the decimal places and bond the integer amount.

**Comment by iameli** [comment]
Hmm. I'm able to bond and unbond that many decimal places successfully but I found at least one place in the UI where we round the places incorrectly.

![image](https://user-images.githubusercontent.com/257909/53138296-b60a1480-353a-11e9-9ea3-5436c9f863dd.png)

So potentially this incorrect display could lead to people attempting to unbond an incorrect number of tokens and fail the transaction. Still looking around though.

EDIT: That trailing "7" is weird too. The correct number is `19.555555555555555555`.

**Comment by iameli** [comment]
Found it. This `parseFloat` is making the numbers lose precision past JavaScript's number handling. https://github.com/livepeer/livepeerjs/blob/9c3aeaebc141cff6c4c512b7b4cdf84046b2043d/packages/explorer/src/utils.js#L93

PR shortly.

**Comment by iameli** [comment]
@dob Just deployed a potential fix for this, #342. Would you mind reaching out to whoever emailed you and seeing if there's still a problem?

**Comment by dob** [comment]
Will do. Will close the issue now and re-open if still a problem.
