### ISSUE TITLE
Unable to Bond or Unbond tokens..

### ISSUE THREAD

**Issue by HydraGene** [livepeer/livepeer-monorepo#338]
**Describe the bug (required)**
For some time I have tried to Bond more LPT to a transcoder that I already have bonded to. However, I am unable to.. (I use explorer.livepeer.org)

When trying to Bond I get 2 error messages. 
First time I try:
`e is undefined`
Then, when I click "TRY AGAIN" and submit:
`Variable "$to" got invalid value undefined; Expected non-nullable type String! not to be null.`

Since it didn't work, I tried to Unbond.
I get the following error message:
`e is undefined`

Unbond did work once when entering the exact bonded amount, including all 14 decimals that the bonded amount had. Second time, it didn't work anymore.
Bond did work when entering an amount less than total balance in the wallet.

**Expected behavior (required)**
The amount entered, with or without decimals, should get bonded or unbonded without problems.

**To Reproduce (required)**
1. Go to explorer.livepeer.org/transcoders
2. Click on bond or unbond
3. Enter any amount, with or without decimals
4. Click on submit

**Device (required):**
 - Device: laptop
 - OS: linux, debian 9
 - Browser: firefox 65.0.1
 - Version: ??

**Comment by iameli** [comment]
Thanks for the report - cross-referencing #334 as another bonding failure and #336 as a potential root cause. I'm looking into these today, reproducing as much as I can on Rinkeby.

**Comment by iameli** [comment]
@HydraGene I just deployed some changes that should fix rounding errors with decimal LPT values. Could you try bonding again and let me know if you see the problem?

**Comment by HydraGene** [comment]
@iameli Alright. I clicked the bond button, and now I see a value with 18 decimals, which previously I didn't see. It was less than the rounded value previously. (I have no idea why...) So previously I tried to bond more than I owned. 
When I bond now, by entering the full decimal value, it worked for me.

P.S. Try to increase the width of the window. If you increase the width, LPT will be next to the value instead of on the line below. It'll look nicer. ;)
![screenshot from 2019-02-25 18-26-33](https://user-images.githubusercontent.com/25724887/53360069-e1bf3d00-3934-11e9-96db-107339024fe5.png)

**Comment by iameli** [comment]
Great, glad to hear it's working for you now! Sounds like you were running into the rounding error that I fixed [here](https://github.com/livepeer/livepeerjs/pull/342).

That's a good suggestion about the bonding modal too — went ahead and filed it as #346.
