### ISSUE TITLE
Update initializeRound as GraphQL mutation and use gas estimation

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#339]
**What's the problem? (required)**
Describe the problem or need in exactly 1 sentence. Ex. "I'm unable to [...]", or "I am confused by [...]"

The round initialization transaction is currently submitted using a [SDK function call](https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/views/ProtocolStatus/enhance.js#L18) from the explorer with a hardcoded gas amount. This is inconsistent with other transactions submitted via the explorer which are modeled as GraphQL mutations. Furthermore, if the gas cost of round initialization increases such that it is greater than the hardcoded gas amount, then round initialization attempts from the explorer will fail and waste user funds.

**What's the current behavior? (required)**
A clear and concise description of the current behavior of the DApp or package (or lack thereof).

The explorer submits round initialization transactions using a SDK function call with a hardcoded gas amount.

**Describe a possible solution you've considered (optional)**

Model the round initialization transaction as a GraphQL mutation so the explorer can use the GraphQL mutation without touching lower level SDK function calls. Within the GraphQL mutation, gas estimation can be used (see this [example](https://github.com/livepeer/livepeerjs/blob/master/packages/graphql-sdk/src/resolvers/Mutation.js#L34)).

**Comment by iameli** [comment]
Seems reasonable, I was wondering why it failed all the time in Rinkeby.
