### ISSUE TITLE
Bonding to an arbitrary address

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#34]
We should allow token holders to bond to an arbitrary address (an address not in the transcoders list).  This is useful when a brand new transcoder is campaigning to replace one of the current transcoders when the transcoder set is full.

**Comment by jozanza** [comment]
Good call. Related to https://github.com/livepeer/protocol/issues/191

**Comment by jozanza** [comment]
If this feature is combined with #67 , then I think transcoders will have a much nicer experience campaigning :)
