### ISSUE TITLE
Explorer round count sometimes shows up negative

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#340]
**Describe the bug (required)**
The "rounds remaining" indicator displays incorrect data while the data is still loading from Infura. I believe I introduced this with https://github.com/livepeer/livepeerjs/pull/333, as that switched up the render logic on some of the GraphQL data.

![image](https://user-images.githubusercontent.com/257909/53136911-a1774d80-3535-11e9-820e-66c590c29fe0.png)

**Expected behavior (required)**
![image](https://user-images.githubusercontent.com/257909/53136923-ab00b580-3535-11e9-9dd2-5789e4c1d583.png)

This seems to show up after a few seconds.

**To Reproduce (required)**
1. Boot up the explorer.
2. Immediately click on the "round" thing in the upper left.
3. That'll show up.

**Comment by adamsoffer** [comment]
Closing since the classic explorer was sunsetted.
