### ISSUE TITLE
bonding modal is too small to contain a full 18-decimal LPT amount plus the word LPT

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#346]
**What's the problem? (required)**
The bonding modal is too small to contain a full 18-decimal LPT amount plus the word LPT.

**What's the current behavior? (required)**
![image](https://user-images.githubusercontent.com/257909/53365775-e82ec400-38f6-11e9-99a9-9fd0bb4ad8bf.png)

**Describe a possible solution you've considered (optional)**
![image](https://user-images.githubusercontent.com/257909/53365795-f250c280-38f6-11e9-82b9-d904a825d6a7.png)

**Additional context (optional)**
Reported by @HydraGene

**Comment by jakeburden** [comment]
I've opened a PR to address this #357 :D
