### ISSUE TITLE
Bonding question

### ISSUE THREAD

**Issue by wils26** [livepeer/livepeer-monorepo#347]
Yesterday I bonded to one of the transcoders and under the staking page on Livepeer Explorer it showed I had 103 LPT bonded.

Today I checked the page and it says I have 0 LPT bonded.

Also, on the Transcoder page the 'BOND' button is no longer there.

Anyone know what might be happening?

**Comment by iameli** [comment]
Hm, that's no good! The first thing I'd check is that you have "Ethereum Main Network" selected in Metamask — often I'll forget I'm on Rinkeby or something and run out.

Past that if you email me your ethereum address or PM me on Discord I can take a look and help diagnose further.

**Comment by wils26** [comment]
HI Eli,

I do have MetaMask on the Main Ethereum Network.

Here's the addy: 0x566bd52454aed2dafd7469c8aba9e313a748cae7<https://explorer.livepeer.org/accounts/0x566bd52454aed2dafd7469c8aba9e313a748cae7>

Thanks,
Greg

________________________________

**Comment by wils26** [comment]
Update it's working now.

**Comment by iameli** [comment]
Hmm, thanks for the report anyway. Recent issues are definitely pointing to a caching problem somewhere... closing for now but feel free to reopen if you run into this again.

**Comment by wils26** [comment]
Appreciate the response. It's still working fine today. I'll let you know if I run into any more issues.

________________________________
