### ISSUE TITLE
Player resizes video to fill screen

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#354]
**Describe the bug (required)**
The Livepeer JS player resizes the video to fill the screen regardless of the video's resolution, which makes it difficult to distinguish between transcoded renditions. This is probably not the effect we want with a sample player that's intended to showcase Livepeer ABR.

**Expected behavior (required)**
Show the video at its native resolution it's if smaller than the screen. I suppose if the video is larger than the screen, it can be rescaled to fit.

**To Reproduce (required)**
1. Start streaming and transcoding
2. Play back the resulting video at media.livepeer.org
3. Attempt to change the rendition
4. The size of the video will look approximately the same between renditions.

**Device (required):**
 - OS: OSX
 - Browser: Chrome

**Comment by iameli** [comment]
Interesting. Presumably this should be a setting? If I'm someone with a low-bandwidth connection watching the low-rez version of a video, I don't want it to be smaller just for demonstration purposes.

**Comment by j0sh** [comment]
I suppose this goes back to the purpose of the LivepeerJS player. In my mind, the player is a convenient way to test Livepeer-generated streams, including visually inspecting the output and ensuring the resolution is as expected. It's not really meant to be a production-caliber tool.

For production, developers would be integrating with their own player that has proper ABR fallback, and those can make the corresponding presentation choices such as resize-to-fit.

So here, the goal isn't actually to use the ABR fallback in non-ideal scenarios; it's to demonstrate the differences in ABR renditions. So it feels like we should be explicit about the display sizing.

Anyway, that's just how I interpret it. If that's not the case, then I'll look for a different player to test with.

**Comment by iameli** [comment]
I do think this is a good idea, I just think it should be something that can be toggled on and off — I suppose implying it'd be an enhancement rather than a bug. Even if the player is being used primarily for visually expecting the output, I might want a low-resolution stream to fill the screen so I can easily inspect visual artifacting and such — inspect the stream as it would be seen by someone consuming the low-bandwidth version.

**Comment by j0sh** [comment]
The toggle could be a feature / enhancement, but IMO not displaying the native resolution is a bug, if the intent of the player is to "demonstrate the differences in ABR renditions".

BTW I'm totally making a presumption here about the intent of the player; I'm not completely sure what the original impetus was for developing a custom player.

**Comment by iameli** [comment]
I think we're on the same page — "Demonstrate the differences in ABR renditions" is certainly a primary goal for the player. Toward that end, two use cases:

1. Display the video in its native resolution for the purpose of demonstrating and verifying that the transcoded video changes the video resolution.
2. Stretch the video to fill the viewbox, or even to fill the entire screen in fullscreen mode, for the purpose of understanding what the output video will look like to a low-bandwidth end user.

The player currently does [2]. I'm proposing we add a button that lets you switch between [1] and [2]. My only objection would be to changing the behavior to only do [1] — I think they're both valid uses of the player.
