### ISSUE TITLE
Player is broken in Safari

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#358]
**Describe the bug (required)**
The player can't play things back in Safari.

![image](https://user-images.githubusercontent.com/257909/53753868-33048a80-3e67-11e9-8cc4-080f5f286c44.png)

Looks like the error might be:

![image](https://user-images.githubusercontent.com/257909/53754011-870f6f00-3e67-11e9-9bc0-d39d81dc8027.png)

**Expected behavior (required)**
![image](https://user-images.githubusercontent.com/257909/53753872-3730a800-3e67-11e9-8e15-88b0a1719c7a.png)

**To Reproduce (required)**
Open any player page in Safari.

**Device (required):**
 - MacOS 10.14.3
 - Safari 12.0.3

**Comment by adamsoffer** [comment]
Closed by #971
