### ISSUE TITLE
Update SDK to Rinkeby protocol

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#36]
#### New Issue Checklist

- [ ] Re-generate protocol SDK according to the latest version (deployed on Rinkeby)

Let's deploy this after EthDenver and after we deploy the same version onto our own testnet.

**Comment by jozanza** [comment]
If we are planning on keeping the testnet/rinkeby ABIs in-sync, it might also be good to add a new option to explicitly specify the Controller address, when constructing an sdk instance. Right now, the Controller address is baked into the ABI artifacts checked into the repo: https://github.com/livepeer/livepeerjs/blob/master/%40livepeer/sdk/etc/Controller.json#L204
