### ISSUE TITLE
Can't unbond

### ISSUE THREAD

**Issue by Anarchyinco** [livepeer/livepeer-monorepo#360]
When trying to Unbond from the delegates account page I get an error message "e is undefined", also "withdraw stake" option is grayed out in my acccount.

**Comment by robiair** [comment]
I am having exactly the same problem....scary that no-one has replied till now

**Comment by dob** [comment]
Can you please provide a little more information to help debug? What browser are you using? What web3 wallet - Metamask? Is Metamask unlocked, connected to mainnet, with your account selected as active?

**Comment by robiair** [comment]
Using metamask on chrome 

Today I just tried to unbound the tokens I had staked and I have received this error:

[ethjs-rpc] rpc error with payload {"id":6404590407910,"jsonrpc":"2.0","params":[{"to":"0x511bc4556d823ae99630ae8de28b9b80df90ea2e","from":"0xe10824fd1ffb9951215025eb26cda42d2d8d9c4c","value":"0x0","data":"0x27de9e320000000000000000000000000000000000000000000000000000000000000000"}],"method":"eth_estimateGas"} {"code":-32000,"message":"gas required exceeds allowance or always failing transaction”}



I have sufficient funds in my metamask account, and naturally metamask is connected to the main net

R

**Comment by pupmaps** [comment]
Using metamask with Brave browser and seeing the same issue.

Also get a unbond failure popup from within the delegate screen (see screenshot)

I have another issue which can also be related. If not, I can open a new ticket.
From the main explorer page where it lists all the delegates, it shows me bonded to the delegate with the staking number shown. When I try to unbond, the confirmation page shows that I can only unbond 10 less LPT. Very strange.

It also shows the number of LPT I have zeroed out from within the delegate's page (see 2nd screenshot).

Thank you.

![image](https://user-images.githubusercontent.com/19463969/57189018-a48ba400-6ebd-11e9-98e7-e79d6aa98d09.png)

![image](https://user-images.githubusercontent.com/19463969/57189043-19f77480-6ebe-11e9-8062-b7fe23b77b58.png)

**Comment by pupmaps** [comment]
Using metamask with Brave browser and seeing the same issue (see 1st screenshot).


I fixed it by turning my computer off and on again :P

![image](https://user-images.githubusercontent.com/19463969/57189079-c33e6a80-6ebe-11e9-80e5-44ea2f6fc3fe.png)

![image](https://user-images.githubusercontent.com/19463969/57190443-fc7ed680-6ece-11e9-943d-a567bd6a99fe.png)

**Comment by pupmaps** [comment]
I can also not bond any new token to the existing delegator.

Please help, because I just went way out of my way to buy more tokens.

**Comment by iameli** [comment]
Hmm, curious, [I fixed that once before by removing the gas limit from eth_estimateGas calls](https://github.com/livepeer/livepeerjs/pull/343/files#diff-15139370d913e41f2ea501962ebb97a4L1998), because that doesn't make sense... I wonder if there's somewhere else where eth_estimateGas is being called with that limit still in place. Will investigate further.
