### ISSUE TITLE
stuck at 1291 google/chrome not updating.  been this way for 2 days.  says there are no transcoders and will not let me withdraw stake.  none of the other keys are working as well

### ISSUE THREAD

**Issue by lmorse59** [livepeer/livepeer-monorepo#371]
**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by lmorse59** [comment]
when i run incognito it is updating properly.  i guess  it may be the same issue as the one reported 2 days before my with the cache being stale and not updating properly

**Comment by iameli** [comment]
@lmorse59 Could you check again now? We've recently deployed a variety of package upgrades that seem to be causing this sort of thing less frequently.

**Comment by lmorse59** [comment]
All is working properly. Sometimes I have to log out. And restart but problem seems to have corrected itself. 

Thank you,

Lynn Morse
Fairfield County Construction Services
203-981-0489

**Comment by iameli** [comment]
Great, thanks!
