### ISSUE TITLE
Explorer: Bonding dialogue omits the information about # of rounds auto-claimed

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#372]
**Describe the bug (required)**

When bonding, the explorer displays some guidance notes about bonding.

It includes a bullet which says:

- You will automatically claim up to rounds of unclaimed earnings when bonding

**Expected behavior (required)**

I expect that it was originally intended to include information about _how many_ rounds of unclaimed earnings would be automatically claimed.

For example:

- You will automatically claim up to **_100_** rounds of unclaimed earnings when bonding

**To Reproduce (required)**

1. Go to https://explorer.livepeer.org/transcoders (with MetaMask logged in)
2. Click on BOND
3. See the guidance notes

**Device (required):**

All.
 
**Screenshots (optional)**

![Screenshot from 2019-03-27 22-46-05](https://user-images.githubusercontent.com/2212651/55117337-67740b00-50e2-11e9-9c05-b7753cbfd14b.png)

**Comment by adamsoffer** [comment]
Closing since manually claiming earnings is no longer necessary as of LIP-36 and the old explorer is no longer maintained.
