### ISSUE TITLE
Bonding to 2+ Transcoders at a time

### ISSUE THREAD

**Issue by githubuser5551** [livepeer/livepeer-monorepo#374]
What is this discussion about?
Possibility of bonding to more then 2 Transcoders at a time?

What is the current state / experience?
At 02.04.2019 I bond 1 LPT to the first transcoder by clicking the "Bond" button entering the number "1" to the "Amount to Bond" field (in case of entering "0" or leaving it blank, the existing amount of bonded LPT would be delegated to this transcoder). 

After this was accomplished (green rectangle surrounding the first transcoder field), I searched for a second transcoder and bond 1 LPT to the second transcoder as described above for the first transcoder.
But although of entering a "1" to the "Amount to Bond" field and clicking the "Submit" button in the "Bond your token" and the Metamask Addon Page to confirm the action, in this case an amount of 2 LPT were bond to the second transcoder and the 1 LPT in the first transcoder disappeared

I read the bonding tips before:
...
You may only bond to one delegate
...

So my conclusion is that it is only possible to bond to one transcoder at a time, otherwise you have to use another wallet with an own amount of LPT to use.

Could other users confirm this?

Additional context
I'am using Opera with a Metamask Addon on a Windows 10 PC.
I have been through the open and closed topics for this "issue", but couldn't find any information regarding this usecase.

Thanks everyone upfront!
Greetings

**Comment by dob** [comment]
Hi @githubuser5551. Yes it is confirmed that you can only stake towards one transcoder at a time per account. The workaround, as you suggest, is to use a second account to stake towards another transcoder.

It would definitely be a nice UX improvement to allow staking towards multiple nodes, but the underlying protocol, transactions, and smart contracts on Ethereum would need to change drastically to support this. I think it could be addressed at the UX/app level by creating an app that used contracts to represent the various accounts that invoked the staking related transactions. This would be quite a lot of architecture and product work though to nail the experience. I don't believe it will be a core team priority any time soon, as the workaround is pretty straightforward, however if someone in the community wants to work on this, then it could be a good candidate for a [grant](https://github.com/Livepeer-Community-Node/Grant-Program).

**Comment by githubuser5551** [comment]
Hello @dob ,thanks for the fast response to my "issue".

Okay, I now understand the reason why this is feature is not possible yet. Then I would use a second wallet in future to bond to another Transcoder.

Maybe someone in the community will do it, as you described.

Anyway, thanks to you and your team for creating and maintaining such a big project as Livepeer and sharing your work with the community, I appreciate that very much.

Greetings
