### ISSUE TITLE
Claimed Earnings Not Showing

### ISSUE THREAD

**Issue by rnakaima** [livepeer/livepeer-monorepo#375]
Hello,

When I claim my earnings under the staking tab, I do not see any added LPT in the Staking or Overview tabs, even though it indicates that the claim was successful.  Please let me know if I am doing something wrong.

Thank you

**Comment by juanfrand** [comment]
Same here!!

**Comment by ngerald51** [comment]
After unclaiming my earnings im not seeing my lpt balance increased as well. Thanks

![image](https://user-images.githubusercontent.com/8562512/61212345-91eee000-a734-11e9-8565-01939f9ae41b.png)

**Comment by adamsoffer** [comment]
Closing since the classic explorer is no longer maintained.
