### ISSUE TITLE
Can't bond new LPT

### ISSUE THREAD

**Issue by maxmersch** [livepeer/livepeer-monorepo#376]
I seemingly cannot bond new LPT. 
I am bonded to a transcoder, but just send additional LPT to my address, and it doesn't show up in the Livepeer explorer on that address. The "CURRENT LIVEPEER TOKEN BALANCE" is basically not up to date when compared to Etherscan.
When I try to click on "bond to delegator", it also doesn't allow me to increase allowance (greyed out).

**Comment by dob** [comment]
Hey @maxmersch. We've had some reports of stale data or caching issues in the explorer.

One thing to try is a hard refresh: CMND+SHIFT+R, and see if that updates your accurate balance? What browser are you using?

It's also worth mentioning if you urgently need to complete these actions they are possible through an interface like MyCrypto, but that's a little more technically involved.

**Comment by iameli** [comment]
@maxmersch Hmm, agreed definitely consistent with issues we've been seeing. I'd try verifying in a different browser - if there's still problems then and you're comfortable sending me your Ethereum address I can diagnose further.

**Comment by maxmersch** [comment]
So I switched over the Brave and that worked (was on Chrome before). Still shows up as the previous amount on Chrome now despite clearing history/cache.
Will check if it works for a 3rd round of LPT i plan to send to that address on Brave.

In either case - many thanks for the quick answers!
