### ISSUE TITLE
Cannot Update Transfer Allowance

### ISSUE THREAD

**Issue by monarogm** [livepeer/livepeer-monorepo#377]
<img width="443" alt="error - livepeer - update transfer allowance" src="https://user-images.githubusercontent.com/49298026/55665514-df81c400-588c-11e9-89d0-60654c765998.PNG">

Hi, I am trying to update my trading allowance so I can start bonding. I am having trouble as I keep getting the same error. Please see attachment. I have tried transacting at least 15 times. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/49298026/55665529-2ff92180-588d-11e9-91c4-bf020b94cd15.png)

**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by adamsoffer** [comment]
Closing since the classic explorer was sunsetted.
