### ISSUE TITLE
A lot of the nodes in explorer are reported as inactive on a random basis. 

### ISSUE THREAD

**Issue by j1v** [livepeer/livepeer-monorepo#378]
Currently explorer is showing a lot of the nodes as inactive. 

Tested on different devices ( iOS / macOS Mojave ) , Brave browser and Safari ( Trust built in browser ) 

At least for my node I'm sure is active and registered : 

```
+----------------+
|TRANSCODER STATS|
+----------------+
*---------------------------*------------------------------*
|                    Status |                   Registered |
*---------------------------*------------------------------*
|                    Active |                         true |
*---------------------------*------------------------------*
|               Service URI |   https://.............:8935 |
*---------------------------*------------------------------*
|           Delegated Stake | 56492.815544358378427904 LPT |
*---------------------------*------------------------------*
|            Reward Cut (%) |                         0.19 |
*---------------------------*------------------------------*
|             Fee Share (%) |                          100 |
*---------------------------*------------------------------*
|         Price Per Segment |             150000000000 WEI |
*---------------------------*------------------------------*
|    Pending Reward Cut (%) |                         0.19 |
*---------------------------*------------------------------*
|     Pending Fee Share (%) |                          100 |
*---------------------------*------------------------------*
| Pending Price Per Segment |             150000000000 WEI |
*---------------------------*------------------------------*
|         Last Reward Round |                         1307 |
*---------------------------*------------------------------*
```

<img width="951" alt="Screenshot 2019-04-08 at 20 13 58" src="https://user-images.githubusercontent.com/10178015/55743411-e5b5a300-5a3a-11e9-84ce-7f8786691023.png">

Using the explorer for looking at detailed info for some node could eventually change the node info to "active". 

Behaviour is confirmed by other user on Discord : 

> yes @j1v  same for me
> your transcoder also showing inactive
> j1v Today at 8:09 PM
> could you please click it's info
> maybe try different menus
> it showed inactive, but later it became active
> but I don't remember when
> I'm trying to post an issue, as @dob suggested
> 
> ToasT Today at 8:10 PM
> oh wait
> it just updated
> j1v Today at 8:10 PM
> I guess it's cache again. reward cut is 0.19 since a few rounds already
> ToasT Today at 8:10 PM
> 
> So it's interesting...
> If you click on a transcoder and let it update it's info and click back to the transcoders page..it'll show active
> But then others arent

**Comment by adamsoffer** [comment]
I'm seeing this too. @iameli If you check out the subgraph playground on The Graph's explorer, for some reason a bunch of transcoders are being incorrectly indexed as inactive. I'm not seeing this issue on my self hosted subgraph though so I wonder if this issue is only occurring in The Graph's hosted environment? If that's the case, is it possible to switch back to our self-hosted Graph Node?

**Comment by iameli** [comment]
Yep, it's ready to go. I'll go ahead and make the switch now, hopefully will resolve this right away.

**Comment by iameli** [comment]
Waiting on CI pipeline, then will close this.

**Comment by iameli** [comment]
Should be fixed now.
