### ISSUE TITLE
Install is dependent on libsecret-1-0 that is not mentioned in the Readme

### ISSUE THREAD

**Issue by j1v** [livepeer/livepeer-monorepo#380]
on a minimalistic ubuntu based LXC the stated equirements  "node, npm and yarn" are not enough to run as yarn fails on libsecret-1-0 missing :

```
error /root/livepeerjs/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /root/livepeerjs/node_modules/keytar
Output:
prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
```

`apt install libsecret-1-0` solves the problem and yarn starts successfully

**Comment by iameli** [comment]
Good catch! I'm hoping to address this upstream here https://github.com/graphprotocol/graph-cli/pull/251

**Comment by iameli** [comment]
Fixed upstream, it’s now an optional dependency.
