### ISSUE TITLE
The transcoder to which I was bonded disappeared. What is going on?

### ISSUE THREAD

**Issue by Maheek** [livepeer/livepeer-monorepo#400]
As a new investor, I am feeling a bit unsafe right now. 

I bonded my first LPT on 4/27/19. My second bonding of LPT was to a transcoder on May 1 that seems to have disappeared from explorer.livepeer.org/transcoders. The transcoder showed a price >100000 GWEI, so I thought I'd see how it paid. 

What happened to the transcode such that it is missing from the list? Where are my LPT? Is the transcoder still active? Am I still earning from it? How can I unbond and bond to another transcoder if I cannot see the old one?

**Comment by dob** [comment]
@Maheek If a transcoder resigns, or loses their spot in the top 30, they may disappear from the list. Your LPT are safe, but if you'd like to continue earning inflationary LPT then you should bond towards another node that is in the active set. You can view your LPT balance on the staking tab of the "my account" page on the explorer at explorer.livepeer.org/me

**Comment by Maheek** [comment]
I see that I am bonded to 0x1d3c25f612d12b902c3ce6eb74afec8ce27ec612 -- but cannot see how to unbond. This seems an awkward design. So the transcoder resigned or lost the spot. Why not show it on MY list since I still have a STAKE in it. This display feature would allow me to UNSTAKE without contacting you. If the transcoder resigned, that status should replace "Active" / "Inactive" with oh, say "Resigned" ?  Or am I such a novice that my request is nonsense... That too has been known to happen.

**Comment by dob** [comment]
I don't believe the request is nonsense :) If the unbond button doesn't show up for you on their account page at https://explorer.livepeer.org/accounts/0x1d3c25f612d12b902c3ce6eb74afec8ce27ec612/overview, then this sounds like a feature that *probably should* be added to the explorer. In the meantime, even though it's an extra step, I'd recommend staking towards another active node, and then using the unbond button if you want to unbond.

**Comment by Maheek** [comment]
Then too, I need to be smarter than the bullet on the web page that says, "You do not need to unbond to switch delegates."  -- So I am attempting to rebond to a new one. Seems to be hung on "submittting". I am a bit concerned that is says there are only 167.569913215921150304 LPT to bond. Yesterday, the explorer showed that I had 232,1428 --- then dropped down to 168.71, which was my balance on 5/3. Have I *LOST* LPT in this fiasco?

**Comment by dob** [comment]
There is no reason that you would lose any LPT as a result of using the explorer or protocol. If you share your public account address we can take a deeper look. If you're not comfortable placing it here, you can send a DM to me in Discord @dob. **(Note: do not share your private key anywhere. Only your public Ethereum address)**

**Comment by Maheek** [comment]
I have successfully bonded to another transcoder. I did not need to unbond from the inactive one to switch my LPT to a new transcoder, implicitly unbonding to inactive transcoder.

**Comment by Maheek** [comment]
On LivePeer Explorer, I have an idea that may help others decide which transcoder to bond to.

Once ready to bond and searching by transcoder, one can see "Reward, Fee, Price, Total Staked, and Missed"
Could the team consider adding columns focused on performance in a UNIT, where UNIT is your design choice of either a ROUND or DAY (midnight to midnight), or last 24HRS (updated every minute?)

Consider adding columns such as "Segments Processed last (UNIT)"  and "Average Segments/UNIT"?

I'm thinking about this because, for example,
0x9e14 charges 250 GWEI and 0 100. Sounds good. But what if they process only 4,000 seconds during a day?
0xda43 charges 200 GWEI and 0.5 50, but they process 21,600 segments a day every day.

The second would have a better payout for the investor. As someone seeking to promote the technology AND make an ROI, I look for that metric.
Perhaps my understanding of payouts is flawed, but as it is now, I think a column showing how BUSY the transcoder is, may be of help.

In a prior email or phone call, you indicated that one should not use LPT as an investment. That statement is difficult to accept when I see north of $34 million of LPT staked on the various active nodes.

I welcome your response.

Mike

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Maheek** [comment]
We interacted last in May.

I've not checked back on he livepeer system for a while, but I stopped earning about 10/28. Instead of 6.5 LPT/day, I am getting 0.04.

Upon checking, orchestrator 0x9e14de5cc84e437518c2c303c88570fe13f0ad15 died about that time. I tried to unstake but see a requirement: "You must claim your earnings before you can continue staking."

I can find no obvious way to claim my earnings so I can restake.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adamsoffer** [comment]
@Maheek you should see a call to action to claim your earnings above the staking widget.
<img width="359" alt="Screen Shot 2019-12-08 at 3 34 25 PM" src="https://user-images.githubusercontent.com/555740/70395776-49c8a680-19d0-11ea-8e83-59e9bc62ce2c.png">

**Comment by Maheek** [comment]
Butttttt.

Clicking on Transcoder

Connect Wallet:

Wallet connected

I'm going NUTS. There *IS* no CLAIM button. Notice no scroll bar and the bookmarks -- I *AM* at the top of the web page.

Is this a bug in the web page that I cannot claim from a defunct orchestrator?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
