### ISSUE TITLE
Ledger Support

### ISSUE THREAD

**Issue by roleerob** [livepeer/livepeer-monorepo#401]
**What's the problem? (required)**
Having just spent a considerable amount of time getting my LPT purchased and set up to delegate to a Transcoder, was chagrined to discover Liverpeer / Protocol Explorer apparently REQUIRES the use of MetaMask.  MY FAULT for not reading through this carefully enough up front, since I am NOT saying this was hidden.  Just a very disappointing discovery ...

**What's the current behavior? (required)**
I cannot utilize my LPT to delegate to a Transcoder, without moving it out of my Ledger wallet and into a MetaMask wallet ...  I will NOT be doing that ...

**Do you have any personal experiences dealing with this problem? (optional)**
Yes, just experienced it.  Nothing to be done, as far as I know, except request a future enhancement, as I am doing now.

**Describe a possible solution you've considered (optional)**
Support for Ledger-linked wallets.

Thank you, in advance, for your serious consideration of this request.

**Comment by adamsoffer** [comment]
Hey @roleerob - Metamask supports Ledger hardware Wallets as of September of last year so good news is you can delegate your LPT without having to move your LPT out of your Ledger wallet. Hope this helps. https://link.medium.com/VUN3n2GQrW

**Comment by roleerob** [comment]
Thank you adamsoffer!

From the link you provided, it has been an .... uhhhh ... "adventure" to follow-up on it and get it all working.  I won't bore you with the details, but I am not a computer beginner or anything remotely close.  Before recently retiring, I was a Business Systems Analyst ...

I only mention this to say my experience getting this all set up just reinforced for me why this new "digital asset" class is NOT ready for the masses.  Way too many technical details and no clear path forward.  All written down in one place ...

Well, anyway, I have survived it and hope soon to begin earning some income from my bonded LPT tokens ...

Thanks again for the assist!

**Comment by roleerob** [comment]
For any who may follow and read this thread of messages, Adam's link is only the starting point.  Here is a very brief outline, assuming you are like me and you already had a MyEtherWallet account, backed up by a Ledger, and you did NOT want to create another whole new wallet in MetaMask:

1.  You have to set up a new MetaMask wallet anyway!!  Even though it will ultimately (at least in my case) be left empty.  Poor design ...

2.  Once you get into your new MetaMask account, click on the little colored icon in the upper right (__*no*__ obvious way to it ...) and select "Connect Hardware Wallet."

3.  Logged into your Ledger and with the ETH app open, then select Legacy (MEW / MyCrypto) on the drop-down in the middle of the resulting dialog you get with "Connect Hardware Wallet."  Select the account you want to use ...

I use Brave and have always successfully opened MyEtherWallet from there, with my Ledger.  Good luck!

P.S.  If I can help anyone, I am @roleerob on the Steem blockchain.

**Comment by adamsoffer** [comment]
Thanks for sharing @roleerob !
