### ISSUE TITLE
Can't Bond - No icon

### ISSUE THREAD

**Issue by jvanlan** [livepeer/livepeer-monorepo#406]
**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**
See Jing Video:  https://www.screencast.com/t/jJHyn2jZlpT

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6] PC
 - OS: [e.g. iOS, Linux] Win 10
 - Browser [e.g. Chrome, Safari]  Chrome & Firefox tested
 
**Screenshots (optional)**
If applicable, add screenshots to help explain your problem. https://www.screencast.com/t/jJHyn2jZlpT

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by iameli** [comment]
Thanks for the video! I'm taking a look at these issues today - will get back to you shortly. Are you still running into the problem?

**Comment by jvanlan** [comment]
The Jing video explained all of the "Requirements"

Describe the bug (required)
There is not an icon to bond on the transcoder screen

Expected behavior (required)
I expected to see the "Bond" icon on each transcoder

A clear and concise description of what you expected to happen.

To Reproduce (required)
See Jing Video: https://www.screencast.com/t/jJHyn2jZlpT
Steps to reproduce the behavior:

Go to https://explorer.livepeer.org/transcoders
 -No "Bond" icon on any transcoder
Click on any Transcoder and there is also no icon to Bond at the top for any Transcoder.


Device (required):

Device:  PC
OS:  Win 10
Browser  Chrome & Firefox tested
Version   74.0.3729.131
Screenshots (optional)
If applicable, add screenshots to help explain your problem. https://www.screencast.com/t/jJHyn2jZlpT
