### ISSUE TITLE
Cannot Bond

### ISSUE THREAD

**Issue by maddogsam** [livepeer/livepeer-monorepo#408]
I own LPT
I have MetaMask, and Livepeer open with MyEther Wallet
When trying to Update my Transfer Allowance I enter my LPT total
I try to BOND
pop up screen says "Alert, not enough funds!!"

**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by maddogsam** [comment]
I own LPT
I have MetaMask, and Livepeer open with MyEther Wallet
When trying to Update my Transfer Allowance I enter my LPT total
I try to BOND
pop up screen says "Alert, not enough funds!!"

I have MAC OS
Brave browser

**Comment by jvanlan** [comment]
You need some ETH so you have enough gas. I had the same issue before.

**Comment by maddogsam** [comment]
Thanks

Sent from my iPod

Madison Sample Jr MD

**Comment by ericxtang** [comment]
Closing the issue
