### ISSUE TITLE
How can we stop the explorer from confusing people?

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#411]
**What is this discussion about? (required)**

When using the Livepeer Explorer, it is often the case that the information displayed on the STAKING tab is incorrect - I presume due to that fact that the data is being updated from Graph / Ethereum, and can occasionally take longer than "instantly".

What appears to happen is that in the absence of any "live" data from Graph / Ethereum, the page will default to showing some kind of "base case", before replacing it with accurate information.

Such base cases I have experienced include:

- Showing STAKING Status as "Unbonded"
- Showing STAKE as 0 LPT
- Showing UNCLAIMED EARNINGS as "0 LPT / 0 ETH"
- Showing Stake as being all the claimed Stake, without adding UNCLAIMED EARNINGS (probably same issue as previous bullet)

See below for a screenshot 

For users connecting on slow / unstable connections, we are seeing that occasionally this "base case" information doesn't update to the accurate version for several moments, and occasionally not at all.

I would like to discuss whether:

a) we think that showing this "base case" can be confusing / misleading / disenfranchising for users - and result in an excessive number of queries, and / or a loss of credibility of the staking mechanism (which would be a real shame, given how robust and elegant it all actually is in the back end).

b) it might be sensible to replace the base case with something to indicate that information is _still loading_, instead of showing them information that is _inaccurate_ (however momentarily).

**What do you hope to learn by the end of this discussion? (required)**

1. What the options + pros / cons are for displaying different information to users

2. How developers of livepeerjs simulate slow connections (e.g. 3G mobile on old smartphones, vs. Fibre-broadband on 3.4GHz CPUs) for testing the UX of e.g. explorer.livepeer.org)

**Additional context**

This is a screenshot taken before the page was able to update to accurate information about the address:

![image](https://user-images.githubusercontent.com/2212651/57851244-f8f52480-77d7-11e9-9644-b4d23109839b.png)

**Comment by ericxtang** [comment]
@adamsoffer is working on a [Livepeer primer](https://github.com/Livepeer-Community-Node/Grant-Program/issues/13), which is a good start. I think more instructive content can be added to it for the next step, especially around instructions for the explorer.

There are also a few other grants where people are doing product work like user journey, interviews around the explorer UX.  All of this will help us improve the explorer :)

**Comment by iameli** [comment]
Thanks for doing this write-up! I think you did a great job articulating some of the deficiencies in the existing system.

> I would like to discuss whether:

> a) we think that showing this "base case" can be confusing / misleading / disenfranchising for users - and result in an excessive number of queries, and / or a loss of credibility of the staking mechanism (which would be a real shame, given how robust and elegant it all actually is in the back end).

> b) it might be sensible to replace the base case with something to indicate that information is still loading, instead of showing them information that is inaccurate (however momentarily).

Definitely agreed with all of this. The existing system has a lot of unfortunate caching and doesn't do a good job surfacing either "loading" or "error" states in many of the views.

> How developers of livepeerjs simulate slow connections (e.g. 3G mobile on old smartphones, vs. Fibre-broadband on 3.4GHz CPUs) for testing the UX of e.g. explorer.livepeer.org)

This can be tricky in our context! The first time I tried to simulate a slow connection, nothing changed for me — all of my blockchain queries were flowing through my Metamask extension which wasn't throttled. I'm sure it's possible to throttle extensions too, but that's what's stopped me so far from simulating a 3G connection.

Slow connections are just one of a few issues that I'm aware of, though:
* "Loading" and "Error" states not being properly surfaced by the front-end
* Different users using different Web3 implementations - I see different problems on browsers without Metamask, browsers with Metamask, and browsers with other wallets.

> What the options + pros / cons are for displaying different information to users

Moving forward I'd like to lean on the `@livepeer/subgraph` system as much as possible that we're hosting on `graph.livepeer.org`. I like the tradeoff that it makes between decentralization and practicality — on the one hand, anyone can run the subgraph if they care to, but it provides a much more consistent user experience in the explorer as everyone is pulling from the same data source.

There are a few pieces that need to be in place to actually make that transition. I've been working incrementally to improve the underlying infrastructure, recently introducing a caching layer in front of the graph-nodes themselves.  Additionally, [@adamsoffer has a long-running PR to make a variety of improvements to the subgraph](https://github.com/livepeer/livepeerjs/pull/325) but those changes haven't yet been integrated into the explorer.

In the meantime I'm happy to look at this profile loading issue specifically, but I've gone down the rabbit hole a few times on these data inconsistencies without making a ton of progress - too many variables. It seems like the specific issue that you've referenced here could be solved if we can get a proper "loading" state working on the profile screen — I'll see what we can do there.
