### ISSUE TITLE
ENS not displaying correctly in all places

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#414]
**Describe the bug (required)**

The ENS name for Ethereum accounts is not being displayed in the list of Transcoders, or in the OVERVIEW page.

It displays correctly in the browser address bar, and also in the top left next to My Account.

This is inconsistent.

**Expected behaviour (required)**

I expect that ENS names should be displayed wherever possible in Livepeer Explorer.

**To Reproduce (required)**

Steps to reproduce the behaviour:
1. Go to https://explorer.livepeer.org/accounts/lptfutures.eth/overview
2. See how the text `lptfutures.eth` displays correctly next to the "My Account"
3. See how the text under ETH ADDRESS on the OVERVIEW tab **_displays the full ETH address.(`0xb52ea89d6532ac8c5f17f06482ff4f8a9c353e3a`) and not the ENS name_**
4. Go to https://explorer.livepeer.org/transcoders
5. Scroll down to the entry marked `0xb52ea89d6532ac8c5f17f06482ff4f8a9c353e3a`
6. See how it **_displays the full ETH address.(`0xb52ea89d6532ac8c5f17f06482ff4f8a9c353e3a`) and not the ENS name_**

**Device (required):**
 - Device: Lenovo Thinkpad
 - OS: `Ubuntu 19.04`
 - Browser: Brave
 - Version: `0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)`
 
**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/2212651/57963789-c5261600-7921-11e9-8caa-546d211f17d8.png)

![image](https://user-images.githubusercontent.com/2212651/57963797-dff88a80-7921-11e9-9989-2ec4ae8f6c46.png)

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by adamsoffer** [comment]
Closing since the old explorer is no longer maintained and ENS support implemented (using 3box for profile data).
