### ISSUE TITLE
Update transfer allowance input and button are disabled

### ISSUE THREAD

**Issue by worldlyjohn** [livepeer/livepeer-monorepo#417]
**Describe the bug (required)**
Cannot update transfer allowance

**Expected behavior (required)**
Text input field and buttons should not be disabled

**To Reproduce (required)**
1. Enable transfer allowance of N LPT
2. Bond N/2 LPT to a transcoder
3. Bond N/2 LPT to a 2nd transcoder (thereby moving N LPT)
4. The bonding goes through, but it seems to get stuck where I can't see where I've bonded my LPT nor can I unbond. https://www.supermax.cool/livepeer/mainnet/activity?filter=%7B%22search%22%3A%220x6c3f28abb2c24c2b531e77eea5c9edecc1778694%22%7D

**Device (required):**
 - Device: MacBook Pro
 - OS: Mac
 - Browser Chrome
 - Version 74
 
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/211638/58583564-5058b300-8222-11e9-8058-94528875eabe.png)
![image](https://user-images.githubusercontent.com/211638/58583576-577fc100-8222-11e9-9719-1f37e83a6f55.png)

**Additional context (optional)**

**Comment by worldlyjohn** [comment]
maybe related to #416

**Comment by adamsoffer** [comment]
Closing since the classic explorer is no longer maintained.
