### ISSUE TITLE
Bonding: Status changes

### ISSUE THREAD

**Issue by marcdemar** [livepeer/livepeer-monorepo#421]
Hi, 
I bonded some LPT to a transcoder recently and it all showed up correctly. I left it for a day and now when I look in the Livepeer explorer, the bonding status of my account is 'Unbonded'. It seems a bit erratic - after logging out and in again in Metamask I somehow got the bonding status back to 'Bonded' and the correct LPT amount showed up (although I am not at all convinced it has something to do with Metamask). 
Only to switch to unbonded again shortly after.
Any clues why this happens? My account: 0x10fb43571923a809ff57c756078bf50a6cdd2fd8

**Comment by dob** [comment]
@marcdemar The account itself looks good to me, so this is just an explorer data syncing issued. Unfortunately building on top of the blockchain and some newer technology solutions like the Graph means that sometimes data takes awhile to sync. Others have certainly reported things like this, but generally just refreshing the page and waiting a couple seconds will cause the data to update if things look funky. We'll work to make this more stable of course over time.

**Comment by marcdemar** [comment]
@dob It indeed looks like a refresh/sync issue. Thanks! And keep up the good work!
