### ISSUE TITLE
Changing signing module to make sure there is replay protection

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#43]
#### Expected Behavior

There should be replay protection for signed transactions so that they cannot be replayed on different networks once they are submitted on one network.

#### Current Behavior

Seems like `ethjs-signer` is used as the package for signing transactions in the SDK, but according to its README it currently DOES NOT have replay protection so it should not be used in a production setting.

#### Possible Solution

Another candidate package to use for signing transactions is [ethereumjs-tx](https://github.com/ethereumjs/ethereumjs-tx) which does have replay protection.

**Comment by jozanza** [comment]
Good catch, @yondonfu. I can work on switching that over very soon. Luckily, the explorer relies on MetaMask to submit transactions, so it's not a vulnerability for anything we have deployed currently 👍
