### ISSUE TITLE
Dear support. 

### ISSUE THREAD

**Issue by dcoutolpt** [livepeer/livepeer-monorepo#436]
**What's the problem? (required)**
Describe the problem or need in exactly 1 sentence. Ex. "I'm unable to [...]", or "I am confused by [...]"

**What's the current behavior? (required)**
A clear and concise description of the current behavior of the DApp or package (or lack thereof).

**Do you have any personal experiences dealing with this problem? (optional)**
Describe your personal experiences related this problem in 1-4 sentences.

**Describe a possible solution you've considered (optional)**

**Additional context (optional)**
Add any other context or screenshots about the enhancement or feature request here.

**Comment by dcoutolpt** [comment]
Dear Support,

I can not claim my staking fees, the box to claim doesn´t appear on my account? what is the problem? i have eth availabel

**Comment by adamsoffer** [comment]
Hey @dcoutolpt - are you logged into metamask? The claim button in the "unclaimed earnings" widget only displays if you own the account you're viewing and you're logged in.

**Comment by dcoutolpt** [comment]
Hi,

Yes i have my metamask account open and log in.

Dear Support,

I can´t claim my staking fees. The box which i can click below the "earning
during the last rounds" doesn´t apear.

I have some earning to clai and i have ETH on my metamask

Thanks in advance

Adam Soffer <notifications@github.com> escreveu no dia segunda, 29/07/2019
à(s) 16:36:

**Comment by adamsoffer** [comment]
hmm are you definitely on your own account view? The "Staking" view looks the same for every delegator, whether it belongs to you or not which can be confusing. Click "My Account", then the "Staking" tab.

Also, sometimes you have to give the page a refresh if you want to give that a try.

**Comment by dcoutolpt** [comment]
The problem is solved.

Thanks

Adam Soffer <notifications@github.com> escreveu em seg, 29/07/2019 às 16:42
:
