### ISSUE TITLE
Add Network entity to the subgraph for displaying protocol pauses

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#437]
The Livepeer protocol can become paused in response to security issues - see for example https://forum.livepeer.org/t/protocol-paused-for-bug-fix-upgrade-5-26-18-9-00pm-edt-update-resumed-at-5-27-18-2-30pm-edt/265

This would be a good piece of information to expose in the frontend and the subgraph, perhaps through a Network entity.

**Comment by yondonfu** [comment]
Closed by #595
