### ISSUE TITLE
Earned LPT Rewards in Unclaimed Earnings not incrementing Bonded Stake amount accordingly

### ISSUE THREAD

**Issue by mckeet** [livepeer/livepeer-monorepo#444]
In testing out our LPT bonded account as a delegate I've noticed over the past few weeks that our Unclaimed Earnings are received but when keeping track of the Staked amount, it does increment but only by around 50% of the Earnings and no Fees are indicated. Is 50% of a delegates earnings all that should be expected to be applied to any delegates staked amount of their earnings? For example, our 17.0459 LPT staked amount four days ago has automatically increased to 17.2428 LPT Staked without claiming our Unclaimed Earnings, as expected. Only the Unclaimed Earnings Reward for 8 rounds across those 4 days was 0.39 LPT. Even after claiming these earnings successfully, the balance of 17.2428 remains. Our claim rewards fee in Eth was only 0.06 wei so one wouldn't think it would be the transfer fee from Metamask. Obviously 17.2428 LPT less 17.0459 LPT is only approx 0.2 LPT so where does the remainder of the 0.39 earnings go?

**Comment by adamsoffer** [comment]
Closing since claiming is no longer a required action in the explorer. If you run into any issue or have any other questions feel free to reach out on the Discord server.
