### ISSUE TITLE
Unbonded after succesful payment

### ISSUE THREAD

**Issue by lor2ex** [livepeer/livepeer-monorepo#447]
I have bond  LPTs to 0xe9e28427... https://etherscan.io/tx/0x42c2edd09d0094664d0d23ef15ee5884647e556c3f0a67f431baa6289e8c3d85

but status Unbonded. Please help

**Comment by adamsoffer** [comment]
Hey @lor2ex - it looks like you've successfully approved your tokens for bonding but have yet to actually bond them. You're one step away! Now that you've approved your tokens for bonding, you can pick a transcoder to bond to.

(If you're interested in why this extra "approval" step is necessary this is a helpful resource: https://tokenallowance.io/)
