### ISSUE TITLE
Bond Your token dialog just hangs with console errors

### ISSUE THREAD

**Issue by ebadiere** [livepeer/livepeer-monorepo#448]
**Describe the bug (required)**
I am trying to Bond my tokens.  I picked my transcoder, entered my amount, and hit 'submit'.  I now just hangs, with a Network changed error and MetaMask RPC Error.

**Expected behavior (required)**

I expected the transaction to complete and my tokens to be bonded.

**To Reproduce (required)**
Stated above

**Device (required):**
 - Device: MacBook Pro
 - OS: Mac OS Sierra
 - Browser Chrome, Safari
 - Version 76.0.3809.100 (Official Build) (64-bit)
 
**Screenshots (optional)**
![Screen Shot 2019-09-02 at 7 21 45 PM](https://user-images.githubusercontent.com/183383/64137678-f7676080-cdb6-11e9-8765-c1cb8c02b97b.png)

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by iameli** [comment]
Hmm. Unfortunately, I'm not sure there's much we could do in this case — that's showing a failed network connection from your computer to the Ethereum RPC provider, Infura. Perhaps we should show an error instead of hanging in this case, but I don't think there's much we could do other than that.
