### ISSUE TITLE
Api Token Authentication

### ISSUE THREAD

**Issue by ya7ya** [livepeer/livepeer-monorepo#449]
**What's the problem? (required)**
we need a http bearer token authentication middleware to protect the API endpoint(s)

**What's the current behavior? (required)**
there is no auth checks, this is needed to ship to production

**Comment by iameli** [comment]
Thanks for opening this! I know we've talked a bit about the workflow but I'm not sure I ever wrote it down anywhere useful so here's how I currently see it:

* Endpoints can opt-in to the API token verification middleware, something like:
```
app.get("/status", authMiddleware(), (req, res) => {
```
* That middleware checks for the existence of an Authorization header of the form `Bearer ${uuid}`. If it's not present, it returns 401.
* If it is present, it checks the database for that auth token. If it exists, great! If not... at some point, we'll return a 403, but for now we should create a new entry in the database for that token so we import all of the existing LivepeerWowza users.

That should be good enough to ship for now; once we've collected all the existing UUIDs and sorted out who is who, we can start locking things down and returning 403s.
