### ISSUE TITLE
api: implement compilation to ServiceWorker/Cloudflare Worker

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#454]
This will entail writing a wrapper for the express router that populates the `(req, res, next) => {}` middleware with the appropriate information.

(I've done this a couple times now, let me know if you want me to point you in the right direction!)

**Comment by wohlner** [comment]
Part of this is done in https://app.zenhub.com/workspace/o/livepeer/livepeerjs/issues/453. Maybe close as a duplicate @angyangie @iameli
