### ISSUE TITLE
api frontend: figure out codesharing and compilation process

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#459]
Currently the preliminary API frontend is being built off of @adamsoffer's `as/explorer-streamflow` branch. We should figure out how these projects can collaborate without breaking the monorepo.

**Comment by adamsoffer** [comment]
@iameli I can move the `theme-ui` config file, compiled components, and storybook into a separate shared package and then we can just both submit PRs to that package. I was originally thinking we could use the existing Chroma package for this but to avoid confusion with the "[Chroma Design System](https://www.chromadesignsystem.com/)" perhaps wise to call it something else. `[company-name]-ui` seems to have become the defacto naming convention for brand-specific ui libraries. `livepeer-ui` sound good?

**Comment by iameli** [comment]
Yeah, that would be great! The only thing that might cause problems is that (AFAICT) you currently have a separate Yarn workspace set up in `explorer-streamflow`; I had trouble getting the Yarn repo to properly symlink packages in that context. If you know an easy way around that, awesome, otherwise it oughta be possible to integrate explorer-streamflow with the rest of the monorepo without too much effort but such things can end up being tricky.

**Comment by adamsoffer** [comment]
Great! Yeah, I was originally using a separate workspace for `explorer-streamflow` because I was running into some weird dependency issue on install with the `web3` package but I figured out the issue last week and now it's part of the same workspace as everything else so should be alright.

**Comment by adamsoffer** [comment]
Merged in `livepeer-ui` yesterday so you no longer have to use the `as/explorer-streamflow` branch. There's a limited set of components to choose from but we can add more over time.
