### ISSUE TITLE
Ethereum network name

### ISSUE THREAD

**Issue by nicolasburtey** [livepeer/livepeer-monorepo#46]
If you metamask is not set to Rinkeby, the app will still work but most of the info will be empty. 

Either showing the network name provided by Metamask/web3js, or showing a warning if it's not on Rinkeby could be useful to the user.

**Comment by jozanza** [comment]
@nicolasburtey Thanks for filing this issue. I think this will be an enhancement I can work on adding sometime in April.

**Comment by jozanza** [comment]
![screen shot 2018-04-30 at 5 52 29 pm](https://user-images.githubusercontent.com/740794/39452213-6cb7e0a2-4c9f-11e8-9597-acd6a38f9c89.png)

This update is live on https://explorer.livepeer.org
