### ISSUE TITLE
Explorer: Add transcoder to the job history view in the broadcasting tab of a user account?

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#47]
When people are broadcasting/testing/debugging they often have the question as to which transcoder was assigned to a specific broadcast. I believe we have enough information on chain to make the determination offchain and add it as a clickable link in the UI - in the job history area of the broadcasting tab of the account view.

Totally open to other options of exposing this data if we don't think it fits well in this specific spot however. It could also just be logged out on the node output.

**Comment by dob** [comment]
Another option is to explore the "Job" view as the next entity. There's lots we want to know about a job:

* ID
* Transcode Profiles
* Price offered
* Broadcaster who created it
* Transcoder assigned
* Segment claims
* Verifications on those claims succeeded or failed
* Payments claimed

So perhaps rather than adding this within the broadcaster job history tab, we make those jobs clikcable link into a job specific view?

**Comment by jozanza** [comment]
@dob I like the idea of a job since most of the information beyond what's shown in the job history list would require additional requests. Also, people might want to share links directly to a specific job.
