### ISSUE TITLE
LPT address

### ISSUE THREAD

**Issue by JVsGithub** [livepeer/livepeer-monorepo#479]
Is it possible to have metamask overwrite my original livepeer address with another one which is when I used metamask to open my etherwallet?

Now when I try to see my livepeer account, I can no longer see any details as if it doesn't exist and I didn't write down the public address.  Is that what I need?

Please advise.

**Comment by JVsGithub** [comment]
I think I just figured it out.  I really appreciate you guys and even tho I didn't need your help.  Thank you for all you do.

**Comment by iameli** [comment]
Great, and thanks for the kind words! Let us know if you run into any other trouble.
