### ISSUE TITLE
Livepeer - transcoders.

### ISSUE THREAD

**Issue by Mitch390** [livepeer/livepeer-monorepo#480]
When requesting the list of transcoders, a message stating 'loading transcoders' appears for a short period before reverting to 'there are no transcoders'. The same situation occurs following several attempts. Can you please advise.

**Comment by adamsoffer** [comment]
Hey @Mitch390 - thanks for reporting. Can you try opening the page in incognito mode? If it works in incognito mode, then try just clearing your browser cache. Also, if you're using metamask, can you confirm you're on mainnet?

**Comment by Mitch390** [comment]
Hi Adam,

 

Thank you for your help, your suggestions followed and problem now solved. 

 

Not sure about metamask so I have de-installed it and will re-install making sure this time that I'm on mainnet.

 

Thanks again.

 

Mitch390

 

Sent: Friday, October 04, 2019 at 5:31 PM
