### ISSUE TITLE
Transcoding video that's not live?

### ISSUE THREAD

**Issue by amplicity** [livepeer/livepeer-monorepo#487]
**What is this discussion about? (required)**
Explore use cases other than _live_ broadcasting.

**What do you hope to learn by the end of this discussion? (required)**
Can Livepeer support non-live video transcoding? If so, can we explicitly define setup instructions in the api docs?

**Additional context**
I run a home media server called [Plex](https://www.google.com/search?q=raspberry+pi+plex&oq=raspberry+pi+plex&aqs=chrome..69i57j69i59.1653j0j1&sourceid=chrome&ie=UTF-8). It can be installed on any kind of computer. One of the widespread limitations is the inability to transcode videos on older/lighter computers (Raspberry Pi implementations are popular). What attracted me to Livepeer was the thought that companies like Plex could implement a connection to Livepeer and outsource transcoding if the user's computer doesn't have the resource bandwidth. I've looked through API docs and found no mentions of this functionality. I want to know if Livepeer can transcode non-live videos, and if so, I believe it should be more prevalent in the API docs.

**Comment by dob** [comment]
Good question, and great use case idea. Currently Livepeer supports live transcoding for streamed inputs. VOD support, which is what I believe you're asking about, is on the roadmap. In the meantime, I guess there's an option and an ask...

1. It would be possible to use the live transcoding functionality of Livepeer to encode a VOD file, with a little hackery. Segment the file, send each to the LP network for encoding, and then recombine the outputs. Not ideal, but possible.

2. If Plex is interested in leveraging Livepeer for this sort of use case, or has an open plugin architecture where someone could write this feature for Plex users, then this could certainly influence the roadmap and priorities, and we'd welcome input on the ideal workflow for getting VOD files encoded.

**Comment by amplicity** [comment]
Thanks @dob 

It looks like Plex does (did?) have a open plugin API.  It looks accessible but unofficially supported based on initial inconclusive research. I've inquired for more feedback from the Plex community [here](https://www.reddit.com/r/PleX/comments/dicr1t/outsource_transcoding/).
