### ISSUE TITLE
LPT on Poloniex

### ISSUE THREAD

**Issue by mgrrasmussen** [livepeer/livepeer-monorepo#493]
**What is this discussion about? (required)
       -Poloniex going to stop service to U.S. customers

A one sentence description of the the discussion topic.
       -If I unbond my LPT today I won't have access to it in time to sell it on Poloniex before 11/01/19

 **What do you hope to learn by the end of this discussion? (required)**
      -I need to know if there is another exchange available to U.S. customers where I will have the ability to trade LPT.
AND, if there is nowhere else for U.S customers to trade LPT besides Poloniex, can someone help me to unbond my LPT sooner than one week?

**Additional context**

**Comment by adamsoffer** [comment]
LPT is available on a number of DEXs now. I recommend matcha.xyz which sources all of them and finds the best price.
