### ISSUE TITLE
Video Player Deployment - HTTPS & Redirection Policy

### ISSUE THREAD

**Issue by jozanza** [livepeer/livepeer-monorepo#5]
We need to make 2 updates to get the video player in a usable production state:

- [x] ~**Secure access to our testnet geth node.** Browser mixed-content policy means we need to run everything over the same protocol, and https > http if we want users to trust our apps. Here's [one approach with nginx](https://ethereum.stackexchange.com/questions/26026/how-to-ssl-ethereum-geth-node).~
- [X] ~**All 404s should return index.html.** Right now, this works in bucket-land, but not once we get to Route 53. We can probably address this with a [Cloudfront distro](https://johnlouros.com/blog/using-CloudFront-to-serve-an-SPA-from-S3).~

Let me know if I can help speed this along in any way.

**Comment by dob** [comment]
Question for @ericxtang and @joewest as well. Do we really want to use S3 to host this if it presents these configuration issues anyway? If we're setting up nginx, ssl cert, and custom 404 rules then we may just serve it out of nginx (possibly behind a load balancer), anyway?

**Comment by jozanza** [comment]
http://media.livepeer.org is in business. We just need geth ssl now.

**Comment by joewest** [comment]
@jozanza Nice!

@dob We can configure redirects in the bucket, but the easiest option is to run a combo of S3+Cloudfront+ACM (the latter two provide TLS on *.livepeer.org). On first glance, I don't think we need nginx for this, but if I'm missing something let me know and we can review the requirements.

**Comment by jozanza** [comment]
nginx would be for the geth node @joewest. Redirects are all working via S3+Route53+Cloudfront. We can switch on TLS once we get a secure url for the geth rpc provider. Web browsers don't like it when you host a secure site and make insecure requests.

**Comment by jozanza** [comment]
It also looks like aws' [API Gateway](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html#api-gateway-create-api-as-simple-proxy-for-http-build) could be a good option for wrapping geth

**Comment by joewest** [comment]
@jozanza Ah, gotcha. It'd be nice to not manage certs manually. API Gateway is one option, though, it's a little weird. 

Is Geth for providing endusers access to the network via the HTTP-RPC / WS-RPC in their browser? Where do we limit what commands are accessible via a proxy?

**Comment by joewest** [comment]
It looks like Geth and Parity do **not** support TLS on [json|ws]-rpc. That's pretty wild.

**Comment by jozanza** [comment]
Yeah, imho it's really crazy they don't. If you have an http/ws server, typically, it's not hard to support tls 🤷‍♂️

**Comment by jozanza** [comment]
Closing this one out. Video player is live at https://media.livepeer.org
