### ISSUE TITLE
View full history link in explorer is broken within Scout

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#502]
**Describe the bug (required)**
The account overview pages in the explorer have a link to "View full history" for the account. Clicking on this redirects to scout.cool, but leads to a 404. See:

https://explorer.livepeer.org/accounts/0xd71f271fFa7a6580e5710FEB7279D795A8272A66/overview and the corresponding link to Scout -> https://www.scout.cool/livepeer/mainnet/activity?filter=%7B%22search%22%3A%220xd71f271fFa7a6580e5710FEB7279D795A8272A66%22%7D

**Expected behavior (required)**
It should lead to a valid Scout page. Or we should remove the option if this view isn't available.

**To Reproduce (required)**
1. Go to https://explorer.livepeer.org/accounts/0xd71f271fFa7a6580e5710FEB7279D795A8272A66/overview
2. Click on View Full History Link
3. Observe 404

**Device (required):**
 - Device: Macbook Pro, Chrome Browser, Metamask

**Possible solution**
Observe the correct URL pattern for filtering by accounts in Scout, and update the link.

**Comment by adamsoffer** [comment]
Closing this issue since this pertained to the old explorer.
