### ISSUE TITLE
Broken existing URLs in new explorer

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#505]
**Describe the bug (required)**
I noticed a popularly shared URL (http://explorer.livepeer.org/transcoders) leads to a weird 404 view within the new explorer. Similarly, I noticed that /accounts/ *addr* /transcoding also leads to an empty page. I don't think the latter is as important as the former.

We shouldn't break these links if possible, as there is a built up history of content all over the internet that link directly to these pages.

I'd suggest a quick pass of the classic explorer, noting the URL patterns, and then try to preserve or redirect based upon them within the new explorer when possible. I do think the /transcoders link should be treated as a high priority step one though.

**Expected behavior (required)**
Existing links shouldn't be broken.

**To Reproduce (required)**
1. Visit /transcoders and observe the 404.

**Device (required):**
 - Device: Macbook Pro, OS X, Chrome

**Comment by adamsoffer** [comment]
👍 I'll capture any other 404s using the Google Search Console tools and set up appropriate redirects.

**Comment by adamsoffer** [comment]
@dob I've added 301 redirects for the following routes:

```
"routes": [
  {
    "src": "/transcoders",
    "status": 301,
    "headers": { "Location": "/" }
  },
  {
    "src": "/accounts/(.*)/transcoding",
    "status": 301,
    "headers": {
      "Location": "/accounts/$1/campaign"
    }
  },
  {
    "src": "/accounts/(.*)/delegating",
    "status": 301,
    "headers": {
      "Location": "/accounts/$1/staking"
    }
  },
  {
    "src": "/accounts/(.*)/",
    "status": 301,
    "headers": {
      "Location": "/accounts/$1/staking"
    }
  }
]
```

**Comment by dob** [comment]
Great. Feel free to close the issue when you're comfortable with the fix as rolled out.
