### ISSUE TITLE
Unable to change transcoder, contract interaction freezes when claiming rewards

### ISSUE THREAD

**Issue by chrisBonGit** [livepeer/livepeer-monorepo#532]
Hi,
I am trying to change transcoder. I currently have LPT already staked and have earned rewards that I haven't claimed (there was no need until now). 
When I attempt to bond with the new transcoder, I am informed that I need to claim the unclaimed reward LPT. Fair enough. So I follow the steps and, using metamask, confirm the contract interaction / transaction. That's when it freezes.
I have tried with the classic explorer, with default Gas and then doubled to 2GWEI, without success. I have tried on different days. No joy, the TXN freezes and when I look for that TXN hash on Etherscan (following the link in metamask) it confirms that is not a valid transaction hash (so at least I'm not wasting small amounts of Ether on these attempts).
I tried this in the new Livepeer explorer too (but used unstake with my current transcoder, rather than bond with the transcoder I want to move to) and this also freezes.
I suspect I'm doing something stupid, but can't find any reference to this issue in forums etc. 
I'd be really grateful if you could offer some advice. I can message my public address and the transcoder which I'm currently staked to, if that helps. But I'd prefer not to put those details here.
Thanks,
Chris.

**Comment by adamsoffer** [comment]
Hey @chrisBonGit - by any chance are you using a Ledger? A user described a very similar issue recently and solved it by going into the app settings of his ledger device and enabling the setting `allow contract data`.

**Comment by chrisBonGit** [comment]
Thank you @adamsoffer - yes I am securing my LPT with a Ledger, and your proposed solution worked. Much appreciated.
