### ISSUE TITLE
Intelligently Skip "Approve" during "Bond"

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#54]
#### Expected Behavior 

`Bond` should skip the `approve` step if the amount of token in question has already been approved.

#### Current Behavior 

`Bond` submits the `approve` call every time we click `Bond`.

#### Context 

Sometimes the `approve` transaction gets included in the blockchain, but for some reason the `bond` step does happen (for example, if `approve` takes a long time, we may time out in the middle of this action)

#### Possible Solution 

Check and see if the bonding amount has already been approved.

**Comment by jozanza** [comment]
I started addressing this issue yesterday. To start off, the explorer will now skip approval transactions for bonds where the amount is omitted. ([view commit](https://github.com/livepeer/livepeerjs/commit/ecd9805866caac8a96f1f2d3100ee591242b5ae9#diff-b2aec6fea59b33ff264b168f768feb39R57))
