### ISSUE TITLE
Explorer can't bond with leading whitespace in LPT amount

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#55]
#### Expected Behavior 

Would like to bond token

#### Current Behavior 

UI shows nothing/ no feedback after attempting to submit. JS console shows a regex error.

#### Context 

Can't bond token as smoothly as I'd like; had to hunt around before figuring out there was a whitespace in there.

#### Possible Solution 

Trim whitespace from the input

#### 🐞Steps to Reproduce

1. Take an amount of LPT and try to bond (eg, copy-paste from the bond UI)
2. Ensure there is whitespace prefixed to bond amount 
3. Submit.

#### 🐞Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

#### 🐞Console Output

```
Uncaught Error: while converting number to string, invalid number value ' 0.588480889565364451', should be a number matching (^-?[0-9.]+).
```

**Comment by jozanza** [comment]
Now you can't use leading whitespace: 4606693286b1ce9b8ccc10e32dea3d6445de3468
