### ISSUE TITLE
Chrome Bonding dialog cant be copied as it vanishes if you click on it

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/livepeer-monorepo#56]
#### Expected Behavior 
if there is an errors in the bonding process on the page https://explorer.livepeer.org/transcoders
a user wants to click in the dialog frame to copy paste the error details
#### Current Behavior 
currently clicking in the frame will make the dialog disappear and the user cant copy the error details anymore
#### Context 
It is hard to report errors 

#### 🐞Steps to Reproduce

1. go to https://explorer.livepeer.org/transcoders
2. bond to a transcoder
3. enter an invalid gas amount
4. process and wait for the error
5. click in the dialog when you see the error

#### 🐞Your Environment
Chrome Version 66.0.3359.139 on OSX 10.13.4

**Comment by jozanza** [comment]
I'm not able to reproduce this error locally @f1l1b0x . Here's what I'm seeing:

![copy_bond_error](https://user-images.githubusercontent.com/740794/39549174-e5c5bbd6-4e2a-11e8-8d20-1a74a2466c06.gif)

Is there something I'm missing?

**Comment by f1l1b0x** [comment]
Hmmm no if I mark the text it vanishes

**Comment by jozanza** [comment]
Okay, if you can provide a screen recording or any additional details steps to reproduce, that would be helpful. Otherwise, if I can't actually get this to happen, I'll probably out close this issue and we can feel free to reopen whenever it's reproducible 👍
