### ISSUE TITLE
explorer: add rinkeby support

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-monorepo#565]
**What's the problem? (required)**
The new explorer doesn't currently support rinkeby. 

**What's the current behavior? (required)**
When switching to the rinkeby network on metamask, the explorer continues to display data on mainnet. It should interact with and reflect what's on the rinkeby network.

**Describe a possible solution you've considered (optional)**
Upon detecting a network change:
1. Instantiate the livepeer SDK with the rinkeby controller address
2. Instantiate apollo client with the rinkeby subgraph endpoint
3. Instantiate wallet providers with rinkeby api keys

**Comment by yondonfu** [comment]
Closed by #570
