### ISSUE TITLE
Front-end for B eth addresses

### ISSUE THREAD

**Issue by wohlner** [livepeer/livepeer-monorepo#569]
Add details after 1-1 with Angie and Eli

**Comment by wohlner** [comment]
In planning, talked about: we will need balances, transaction history. 

Talk with Adam about what is available...subgraph

**Comment by angyangie** [comment]
- Goal NOW: onboard Picarto. Product requirements:
    - Dashboard with B fund status.
    - Admin hits a button, which queries `/addresses` endpoint, and populates status of all mainnet Bs with their deposit and reserve.
    - Livepeer would manually reload funds on Bs
        - Automation not necessary for now since the only mainnet B is Labrador.
        - ATM stream_instances = picarto streams. No need for `/stream_instances` yet

**Resulting Front-end to-dos:**
- [ ]  Login button on the side [http://localhost:3004/](http://localhost:3004/)
- [ ]    `Broadcaster Statuses` button below to `live` button, which hits `/addresses` endpoint, and takes us to new broadcaster page
- [ ]    Broadcaster page with B statuses, displays all $$ statuses
- [ ]    Refresh button on Broadcaster page
