### ISSUE TITLE
Misaligned price field in transcoder view of explorer when value is large

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#57]
#### Expected Behavior 

The title/value for the price field to be aligned with the rest of the field in the transcoder view.

#### Current Behavior 

Funky alignment for the price field when the value is large.

#### Context 

It would be nice to have the title/values of fields in the transcoder view to be aligned.

#### Possible Solution 

Perhaps once there are a certain number of digits, switch to using a larger unit like GWEI or ETH instead of using WEI.

#### 🐞Steps to Reproduce

![screen shot 2018-05-02 at 8 09 34 am](https://user-images.githubusercontent.com/5933273/39522466-3f3825c8-4de0-11e8-837f-206887996d17.png)

1. Navigate to the transcoder view in the explorer while pointed to mainnet

#### 🐞Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): Google Chrome 66.0.3359.139 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOS High Sierra

**Comment by j0sh** [comment]
Maybe the default price unit should be in gwei rather than wei?
