### ISSUE TITLE
api-frontend: user access token creation/list frontend

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#585]

**Comment by adamsoffer** [comment]
Hey @iameli - could you describe the user flow here? Were you envisioning something similiar to this?

<img width="775" alt="Screen Shot 2020-03-12 at 2 25 25 PM" src="https://user-images.githubusercontent.com/555740/76555080-57794680-646d-11ea-8514-b7e70bf96c79.png">

↕

<img width="513" alt="Screen Shot 2020-03-12 at 2 23 02 PM" src="https://user-images.githubusercontent.com/555740/76555101-606a1800-646d-11ea-90dc-b97464854236.png">

↕

<img width="513" alt="Screen Shot 2020-03-12 at 2 22 41 PM" src="https://user-images.githubusercontent.com/555740/76555108-63650880-646d-11ea-9540-e0ed904fd7d5.png">
