### ISSUE TITLE
api-frontend: set up API docs page

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#588]
Should include all of our Swagger documentation compiled into the api-frontend itself

**Comment by adamsoffer** [comment]
What sort of flexibility do we have designing the docs page? Do the swagger docs compile down to markdown?

In terms of look and feel, I was thinking of designing something similar to [https://zeit.co/docs/api](https://zeit.co/docs/api).

**Comment by iameli** [comment]
Swagger docs compile into lots of things, but here's one that does Markdown if that'd be ideal: https://github.com/Swagger2Markup/swagger2markup

But the ecosystem is enormous — I'll take a look at a few of these and see if anything jumps out at me. https://openapi.tools/
