### ISSUE TITLE
Able to Unbond when Pending

### ISSUE THREAD

**Issue by RaffiSapire** [livepeer/livepeer-monorepo#59]
#### After bonding to the community node, I expected not to be able to unbond in the same round that I bonded 
The unbond button should not appear if the node is pending

#### A few minutes after bonding, i hovered over the community transcoder node and the unbond button appeared
Not sure if you should be able to see the unbond button, or when you click on it maybe it says error, you cannot unbond during the same round . But maybe I bonded to that node and its for a round starting tonight, so that is why it let me unbond?

#### 🐞Steps to Reproduce

1. Without having ever bonded before, bond to node

#### 🐞Your Environment

* chrome 
* macbook

**Comment by jozanza** [comment]
Fixed by e777536c5aee5d5781ebab4b036e01dbbc184f42

(https://github.com/livepeer/livepeerjs/commit/e777536c5aee5d5781ebab4b036e01dbbc184f42#diff-168f7607e9231d79576400718086977eR177)

This fix has been pushed live to https://explorer.livepeer.org.
