### ISSUE TITLE
Polling application backend spec

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#593]
## Abstract

This spec outlines a polling application backend that uses a contract for non-binding voting in on-chain polls and a [subgraph](https://thegraph.com/) for off-chain vote tallying.

## Motivation

This design seeks to fulfill the following criteria:

- Simplicity. In this MVP, the priority is making the process of participating easy to understand and accessible so more complex mechanics such as as more sophisticated vote weighting rules are left for a future iteration.
- Auditable. A third party should be able to audit the results of a poll to establish confidence that the votes were tallied correctly.
- Censorship resistant. A centralized party cannot censor votes. We assume that miners are not censoring transactions for the duration of a poll.
- Open poll creation.  Anyone should be able to create a poll. Any requirements for creating a poll should apply to all parties.

This design does NOT seek to fulfill the following criteria:

- Secrecy. Votes will be public as soon as they are submitted on-chain. We leave vote secrecy as a problem to be solved in a future iteration.
- Coercion resistant. Since votes will be public, voters can also be coerced (i.e. via a smart contract bribe) into voting a certain way. We leave coercion resistance as a problem to be solved in a future iteration.

## Proposed Solution

The polling application backend will consist of two components

- A `PollCreator` contract that manages the creation of `Poll` contracts.
- A `Poll` contract that manages voting operations.
- A poll subgraph that indexes events emitted by the `PollCreator` contract to keep track of created polls and events emitted by `Poll` contracts to tally votes.

### PollCreator Contract

```
    contract PollCreator {
    	// The amount of LPT that needs to be burned when creating a poll.
    	uint256 public pollCreationCost;
    	// The address of the RoundsManager.
    	// This value will be used for all polls created.
    	address public roundsManagerAddr;
    
    	// Emitted when a poll is created
    	// This event can be indexed to construct a list of all polls.
    	event PollCreated(
    	    address poll,
    	    bytes memory proposal,
    	    uint256 endRound,
    	    uint256 quorum,
    	    uint256 threshold
    	);
    
    	constructor(uint256 _pollCreationCost, address _roundsManagerAddr) public;
    
    	/**
    	 * @dev Create a poll by burning POLL_CREATION_COST LPT.
         *            Reverts if this contract's LPT allowance for the sender < POLL_CREATION_COST.
         * @param _proposal The IPFS multihash for the proposal.
         * @param _pollPeriod The number of rounds that a poll will be open for.
         * @param _quorum The % (represented as a fixed point number) of active stake that needs to vote for the poll result to be considered valid.
    	 * @param _threshold The % (represented as a fixed point number) of active stake that needs to vote yes for the poll result to be considred an approval signal.
         */
    	function createPoll(
    	    bytes memory _proposal,
    	    uint256 _pollPeriod,
    	    uint256 _quorum,
    	    uint256 _threshold
    	) external;
    }
```

**Creating a poll**

- Anyone call call `createPoll()`.
- The sender must have already set the LPT allowance for `PollCreator` to at least `POLL_CREATION_COST` by calling the LPT `approve()` function.
- `createPoll()` will call the LPT `transferFrom()` function to move `POLL_CREATION_COST` LPT from the sender to the contract. This LPT will then immediately be burned using the LPT `burn()` function.
- After the `POLL_CREATION_COST` LPT is burned, a new `Poll` will be deployed by this contract and a `PollCreated` event will be emitted containing the address of he new `Poll`.

N.B. While the contract does not support crowdfunding the poll creation cost, anyone can write a crowdfunding contract that submits the `createPoll()` transaction when the contract has accumulated sufficient LPT to pay for the poll creation cost.

### Poll Contract

```
    contract Poll {
        // The IPFS multihash that can be used to fetch the proposal text off-chain.
        bytes public proposal;
    	// The round at which the poll ends and votes can no longer be submitted.
    	uint256 public endRound;
    	// The % (represented as a fixed point number) of active stake that needs to vote for the poll result to be considered valid.
    	uint256 public quorum;
    	// The % (represented as a fixed point number) of active stake that needs to vote yes for the poll result to be considred an approval signal.
    	uint256 public threshold;
    
    	// The RoundsManager interface used to check the current round.
    	IRoundsManager private roundsManager;
    
    	// Emitted when an account submits a yes vote
    	// This event can be indexed to tally all yes votes
    	event Yes(address indexed voter);
    	// Emitted when an account submits a no vote
    	// This event can be indexed to tally all no votes
    	event No(address indexed voter);
    
    	constructor(
    	    bytes memory _proposal,
    	    uint256 _endBlock,
    	    uint256 _quorum,
    	    uint256 _threshold,
    	    address _roundsManager,
    	) public;
    
    	/**
    	 * @dev Vote yes for the poll's proposal.
    	 *            Reverts if the poll period is over.
         */
    	function yes() external;
    
    	/**
    	 * @dev Vote no for the poll's proposal.
    	 *            Reverts if the poll period is over.
         */
    	function no() external;
    }
```

**Voting in a poll**

- Both `yes()` and `no()` will revert if `roundsManager.currentRound() <= endRound`
- `yes()` will emit a `Yes` event containing the sender's address
- `no()` will emit a `No` event containing the sender's address
- There are no restrictions on the number of times that a sender can call `yes()` or `no()`
- There are no restrictions preventing a sender from calling both `yes()` or `no()`
- The interpretation of the `Yes` and `No` events emitted by this contract is left for the subgraph.

### Subgraph

The following entities will be added to the subgraph:

```
    enum PollChoice @entity {
    	No
    	Yes
    } 
    
    type Poll @entity {
    	id: ID!
    	proposal Bytes!
    	endRound BigInt!
    	// This is a fixed point number that will need to be converted into a %
    	// prior to displaying to a user
    	quorum BigInt!
    	// This is a fixed point number that will need to be converted into a %
    	// prior to displaying to a user
    	threshold BigInt!
    	// This will be updated at the beginning of each round
    	tally PollTally
    	voters: [Voter!] @derivedFrom(field: poll)
    }
    
    type PollTally @entity {
    	id: ID!
    	// Active stake that voted yes
    	yes: BigInt!
    	// Active stake that voted no
    	no: BigInt!
    }
    
    type Voter @entity {
    	id: ID!
    	stake: BigInt!
    	// The stake that does not back a vote
    	// This can be subtracted from stake to compute the voter's voting stake
    	// If the voter is a delegator, this will be null
    	// If the voter is an active orchestrator, this will be non-zero if any
    	// of the its delegators voted on their own
    	nonVoteStake: BigInt
    	choice PollChoice!
    	poll: Poll!
    }
```

The following new event handlers will be added to the subgraph:

`PollCreated(address poll, bytes proposal, uint256 endRound, uint256 quorum, uint256 threshold)`

- Store a poll entity
    - `poll.id = poll`
    - `poll.proposal = proposal`
    - `poll.endRound = endRound`
    - `poll.quorum = quorum`
    - `poll.threshold = threshold`
- When a new poll entity is created, the subgraph should start indexing the new `Poll` contract
    - TheGraph supports data source template definitions that should help with this
    - The subgraph should start indexing the new `Poll` contract from the block in which it is deployed and it should stop indexing once the poll's end round is initialized

`Yes(address voter)`

- If a voter entity does not exist, create one
    - `voter.id = voter`
    - `voter.poll = Poll(<POLL_CONTRACT_ADDRESS>)`
- Update the voter entity
    - `voter.choice = PollChoice.Yes`

`No(address voter)`

- If a voter entity does not exist, create one
    - `voter.id = voter`
    - `voter.poll = Poll(<POLL_CONTRACT_ADDRESS)`
- Update the voter entity
    - `voter.choice = PollChoice.No`

The following existing event handlers will be updated in the subgraph:

`Round(uint256 newRound)`

- Fetch all polls
- For each poll where `poll.endRound > newRound`
    - Update the vote stake for each voter
        - For each voter in the poll
            - If `voter.id` is an active orchestrator
                - `voter.voteStake = Transcoder(voter.id).totalStake`
            - If `voter.id` is not an active orchestrator
                - `voter.voteStake = pendingStake(voter.id, currentRound)`
            - `delegate = Delegator(voter.id).delegate`
            - If `delegate` is an active orchestrator
                - `Voter(delegate).nonVoteStake += voter.voteStake`
    - Update the poll tally
        - Reset the poll tally
            - `poll.tally.yes = 0`
            - `poll.tally.no = 0`
        - For each voter in the poll:
            - If `voter.choice == PollChoice.Yes`
                - `poll.tally.yes += (voter.voteStake - voter.nonVoteStake)`
            - If `voter.choice == PollChoice.No`
                - `poll.tally.no += (voter.voteStake - voter.nonVoteStake)`

**Design Rationale**

- The design described only updates the poll tally and the voting stake of voters at the beginning of each round
    - This means that the frontend will only refresh the poll tally and the voter's voting stake after the initialization of a round
- The design describes will not update the poll tally and the voting stake of voters until the first round is initialized after a poll is created
    - This means that the frontend will not be able to show a poll tally and the voter's voting stake until the first round is initialized after a poll is created

It is worth mentioning that the current definition of active stake is:
- Stake delegated to an orchestrator in the active set in the current round
- The above value is "locked in" for the duration of the round
- Only active stake is eligible for rewards in the round
- Any rewards earned during the round are added to one's active stake for the *next round*

So, refreshing the poll tally and the voting stake of voters at the beginning of each round actually aligns with the current definition of active stake. 

That being said, I can see why refreshing the poll tally and the voting stake of voters only once per round might not be ideal from a UI/UX POV. Open to suggestions and happy to discuss alternatives.

## Implementation Tasks and Considerations

- Write the `PollCreator` and `Poll` contracts
- Update the subgraph

## Testing Tasks and Considerations

- Unit tests for the contracts
- We could test the subgraph indexing logic by creating sample polls on a development chain (i.e. Ganache)
    - The poll tally should be correct after completing at the beginning of each round
    - The end poll tally should not change after the end round of a poll
    - The voting stake of each voter should be correct at the beginning of each round

## Alternatives

- We could try to modify the subgraph indexing logic to allow a refresh of the poll tally and the voter's voting stake after any update that affects either the poll tally or a voter's voting stake. This will be more complicated, but might be possible - I aired on the side of simplicity for this initial design

**Comment by dob** [comment]
Looks great. Couple thoughts...

1) Why use approve/transferFrom instead of having the value of the contract creation function be equal to the poll creation cost?

2) Should the endRound be included in the poll, rather than the poll ending at the initializiation of the endRound?

3) Another alternative is to just periodically update stake for the poll tallys at an interval that is more frequent than once/round, but not at every update. The frontend could just showcase the "last update date", whether this is 1x/hour or 1x/15 mins, etc.

**Comment by adamsoffer** [comment]
> `@param _proposal The IPFS multihash for the proposal.`

Any thoughts around the proposal form inputs and storage format? A simple `title`, `description`, and `link` that we store as JSON in ipfs?

**Comment by kyriediculous** [comment]
> Any thoughts around the proposal form inputs and storage format? A simple title, description, and link that we store as JSON in ipfs?

Yes that's how I'd do it. 

I would want to add one thing. The process of uploading to IPFS then submitting the IPFS Multihash on-chain is not an atomic process. But there's ways to tackle this. 

1. Run our own gateway and unpin the uploaded document if the transaction fails
2. Compute the IPFS multihash before upload (`--only-hash` option in the CLI when using `ipfs add`, but there should be an API method or option for it too), we can do this because we know the pre-image. Then submit the transaction first and upload the document after the transaction has been submitted. If uploading fails we can retry at very little cost (bandwith only). 

We might also want to run our own IPFS gateway for this (necessary for option 1 regardless I think). 

> Why use approve/transferFrom instead of having the value of the contract creation function be equal to the poll creation cost?

I agree. Additionally, tokenholders are likely to be delegates or orchestrators (especially those actively participating in governance) I assume most of them don't have liquid LPT so that would require them to either (1) unbond and wait 7 rounds before opening their proposal or (2) acquire LPT on Polo (depending on location) or Uniswap (low liquidity)

Instead what about making a UX tradeoff for a slightly higher gas cost: 
We can have the deposit for creating a proposal be paid in ETH. When the `Poll` contract is instantiated with  the deposit, the deposit can be converted into LPT using Uniswap from the contract directly. Then the LPT can be burned. 
- ETH is more liquid 
- No need for two transactions
- User doesn't need both LPT and ETH (gas)
- After the ETH is deposited the Uniswap liquidity for acquiring the ETH doesn't matter to  the user, as it will be burnt regardless

**Comment by kyriediculous** [comment]
I'm not sure if _quorum_ and _treshold_ should be values decided by the user ? 

This allows the opening of proposals with a very low quorum and treshold required. The poll would signal approvement of the proposal but the signal would not be representative.

**Comment by dob** [comment]
> I'm not sure if *quorum* and *treshold* should be values decided by the
user ?

I think the idea here is that the contracts are a self-deployable,
re-usable mechanism for any type of poll that someone wanted to run. But
that the "social contract" or convention of the process that the community
adheres to for its governance instill conventions around what constitutes a
valid poll that the community would adhere to.

**Comment by kyriediculous** [comment]
User as in poll creator.

If the validity of a poll is decided by a social contract/construct then we don't need a quorum and treshold defined in the proposal. We can just let people vote and the front end can display what the eventual voter turnout is in terms of token weight as well as support for either side, then the social contract determines if it is valid based upon that data (turnout -> quorum , result -> treshold).

The alternative (and a system that is more extensible to binding votes changing contract params) is to define quorum and treshold parameters upon Factory genesis, these parameters can then be altered by governance itself but the initial params are decided by Livepeer Inc.

**Comment by yondonfu** [comment]
Thanks for all the feedback!

> Why use approve/transferFrom instead of having the value of the contract creation function be equal to the poll creation cost?

@dob 

The approach of sending value with the `createPoll()` only works if the poll creation cost is denominated in ETH. If the poll creation cost is denominated in LPT, then `createPoll()` needs to call `transferFrom()` so that the LPT can be transferred to the contract and burned in a single atomic transaction. 

I think the poll creation cost should be denominated in LPT because a poll is an ask for the time/attention of LPT holders. There will be some more friction in acquiring non-staked LPT for poll creation, but I don't see that as a bad thing given that creating a poll places a time/attention cost on all LPT holders.

> Should the endRound be included in the poll, rather than the poll ending at the initializiation of the endRound?

@dob

I lean towards defining the end of the poll at the start of the `endRound` because this is consistent with how the end of time periods is handled in other protocol contracts:

- An unbonding lock can be withdrawn starting at its `withdrawRound` instead of after its `withdrawRound`
- A PM ticket expires on-chain starting at `creationRound + ticketValidityPeriod` instead of starting at `creationRound + ticketValidityPeriod + 1`

This question made me realize a flaw in using round numbers to determine the end of a poll: if a poll is started immediately upon creation then it might not be active for the full poll period because it is started in the middle of a round. So, a poll that is supposed to last 10 rounds may only last 9.2 rounds. This issue can be resolved by one of the following solutions:

1. Start the poll at the beginning of the next round after the round in which it is created. So, if a poll is created in round N, it starts in round N + 1.
2. Allow a poll creator to specify the start round for a poll. This is an extension of solution 1. If the poll is created in round N, the poll creator could specify any start round in the future (including N + 1).
3. Use block numbers to determine the end of a poll. If the poll period is supposed to be M rounds, the corresponding # of blocks in M rounds can be set as the value.

I lean towards solution 3 because the poll can be started immediately upon creation. This also simplifies the contracts even more because they do not need to be internally aware of rounds and any other contracts besides the LivepeerToken contract.

> I'm not sure if quorum and treshold should be values decided by the user ?

@kyriediculous

I'm actually thinking of defining the quorum and threshold as constants in `PollCreator` and including them in the `PollCreated()` event without keeping those values in contract storage. As long as the quorum and threshold are included in the `PollCreated()` event, the subgraph can store those values off-chain. Anyone can deploy a new `PollCreator` contract with different values for the quorum and threshold (the `PollCreator` contract would be immutable after deployment), but a primary `PollCreator` contract (along with the quorum and threshold values defined) can be identified as the one the majority of the community chooses to use.

> When the Poll contract is instantiated with the deposit, the deposit can be converted into LPT using Uniswap from the contract directly.

@kyriediculous

This could be a nice way to make it easier to acquire the LPT needed for poll creation, but in the interest of modularity, I think the swap functionality should be in a separate contract that interacts with the `PollCreator`. Then, a user could send ETH into the swap contract that will atomically swap the ETH for the required LPT and then call `createPoll()` on the `PollCreator()`. 

A challenge with implementing a contract that atomically swaps ETH for LPT is that the amount of ETH required to swap for the LPT required for the poll creation cost will be variable. One might be able to address this by estimating the required ETH X, asking the user for X + some % to ensure that sufficient ETH will be sent to cover the required LPT, swap for the required LPT and refund any extra ETH back to the sender.

An alternative is to define the poll creation cost as "$X of LPT" and allow the user to send a stablecoin (i.e. Dai) which is swapped for an equivalent amount of LPT which is burned. The ETH gas cost could be abstracted away via meta-transactions.

I'm interested in the described alternative, but given the additional complexity of the swap + meta-transactions in order to reduce the # of tokens the user needs to be aware of to 1, I'm currently inclined to start with the simple LPT burn model as the MVP and different ways to handle the cost could be introduced in follow on iterations.

**Comment by yondonfu** [comment]
Posted an updated version of this spec in livepeer/LIPs#16 since this spec will be included in a draft LIP. Any additional feedback and discussion should occur in the thread for that issue.

**Comment by yondonfu** [comment]
Closing this because this is now implemented and this spec is also captured by [LIP-16](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-16.md).
