### ISSUE TITLE
Pre-fill claimRewards transaction object with gas price

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/livepeer-monorepo#597]
**What's the problem? (required)**
Metamask sometimes incorrectly calculates the gasPrice for `claimRewards` causing very high gas being sent with the transaction. In [this](https://github.com/livepeer/protocol/issues/372) case even the block gas limit 

**What's the current behavior? (required)**
Metamask calculates the gas needed

**Describe a possible solution you've considered (optional)**
We can prefill the transaction object being sent to the web3 provider with a gas amount 

The gas cost for `claimRewards` should be linear with the amount of rounds to claim for, more specifically `O(1 + n)`

so if we can figure out the gas cost for 1 round we can multiply it by the number of rounds to claim through. We already apply an overhead because the amount we multiply includes the cost to invoke a transaction as well as the constant gas cost for the execution up until the loop in `claimRewards`. 

**Additional context (optional)**
https://github.com/livepeer/protocol/issues/372

**Comment by glints** [comment]
Guys I'm a full stack dev (php, python, js), if you need help, or could give some pointers regarding this issue where and how to solve it I could provide some time to take a look at it... because I really need this; I have several accounts where I want to add LPT to stake, but I can't because I first need to claim my earnings, which isn't working (starting from the second tx in the batch, metamask is throwing an exception error - and no matter how I adjust gas limit or gas price, it won't go away)

**Comment by kyriediculous** [comment]
Can you DM me on discord ( NicoV) perhaps we can resolve your issue without having to necessarily implement this first. 

If you want to take a shot at this issue I can provide implementation details, it would require working knowledge of react and web3js/ethersjs. Let me know if this is something you would like to do.

**Comment by glints** [comment]
I wrote a tiny web app that solves my problem for now:

https://github.com/glints/tinylivepeer

I've tried to download the Livepeer js package, but ran into quite a bit of dependency issues, mostly node related, and since I didn't really have the time to properly setup the environment, this seemed like the fastest solution.

I can now claim 100 rounds for ~ 0.50 $

**Comment by yondonfu** [comment]
> so if we can figure out the gas cost for 1 round we can multiply it by the number of rounds to claim through.

Looks like the `batchClaimEarnings()` function used does not estimate the gas required for a single `claimEarnings()` call (see [relevant code](https://github.com/livepeer/livepeerjs/blob/13985955728433aa2df2259932cff0621d4aa485/packages/explorer-2.0/apollo/resolvers/Mutation.tsx#L69)). Seems like this could be solved by making a gas estimation call ([example](https://github.com/livepeer/livepeerjs/blob/13985955728433aa2df2259932cff0621d4aa485/packages/explorer-2.0/apollo/resolvers/Mutation.tsx#L38)) and using that value in each tx? Then you'd just need to estimate the gas for the maximum # of rounds in a single `claimEarnings()` call in the batch.

**Comment by kyriediculous** [comment]
We can't do that because the estimation will always be based off of the last claim round on-chain.

`claimEarnings(uint256 _endRound)` only takes in an end round, so only the estimation for the first call will actually be correct as it compounds thereafter because we are not actually changing state. 

eg. 325 rounds to claim for
- first estimate:  100 rounds
- Second estimate: 200 rounds (-> Block gas limit error)
- Third estimate - 300 rounds (-> Block gas limit error)
- Fourth estimate - 325 rounds (-> Block gas limit error)

Therefore we need to either implement the strategy I mentioned or 

- estimate the gas for the first 100 rounds , add a safety margin and use that for each claim that is for that size
- for the remainder use a gas limit that is proportional to the amount of rounds to claim for based on the gas limit for 100 rounds. 

But since it's quite unlikely that the gas cost is that different in between users it could be reasonably to employ a constant gas limit for 1 round here so we don't have to do a remote call to an ethereum node.

**Comment by yondonfu** [comment]
> estimate the gas for the first 100 rounds , add a safety margin and use that for each claim that is for that size

👍 Yep this is the option that I was suggesting in [this comment](https://github.com/livepeer/livepeerjs/issues/597#issuecomment-614681560). A single gas estimation call for the first tx for the max # of rounds that will be claimed in a single tx should do the trick.

**Comment by kyriediculous** [comment]
Oh sorry, I misread then. My bad !
