### ISSUE TITLE
New Explorer Has HUGE DESIGN PROBLEM

### ISSUE THREAD

**Issue by gm12395** [livepeer/livepeer-monorepo#598]
The old Livepeer explorer was so much better in terms of design (https://classic.explorer.livepeer.org/).
But with the new one it doesn't even show who I'm staked to on the home page. The old one showed who I was staked to, my amount staked, and showed that the transcoder was operating successfully, all from the home page. I COULD TELL THAT I WAS ACTIVELY STAKED AND RECEIVING STAKING REWARDS, ALL FROM THE HOME PAGE. 
I miss that green box around my transcoder.
With the current version, it looks like I'm not staked to anyone when I'm on the home page. It's pretty unsettling. I navigate through the "my account" page and I'm still not sure if I'm receiving rewards or not. It's hard for me to see where/when my latest staking rewards came. It shows I'm staked but I have no idea if I'm receiving daily rewards and if the transcoder is receiving all the reward calls. It would be nice to have a display that showed me my reward history (even if not claimed yet) and the transcoder's missed calls, all from the "Staking" tab. 

Also, for unstaking, does it really have to put my number in the format 1.551e+4? Can't it just display 15,000?

I am not going to be checking back here to reply to your responses. I don't use Github often. But I am an old school crypto user and the UX here is massively problematic. I have tens of thousands of LPT and I have been staking for over a year. If I'm having problems I can only imagine the user experience for a novice.

**Comment by adamsoffer** [comment]
Thanks @gm12395. So to summarize:

> As a user, I want to see my current staked balance as soon as I connect my wallet so that I immediately know I'm actively staked without having to navigate to "My Account".

> As a user, I want to see a historical view of my earnings, so that I know I'm actively receiving rewards and fees each round.

> As a user, I want to see how my delegate is performing without having to navigate to its campaign page, because this is important information and should be one of the first things I see when I connect my wallet.

Thanks for the valuable feedback. These things will 100% be addressed in a future release.
