### ISSUE TITLE
Intelligently Check # of Unclaimed Rounds During "Bond"

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#61]
#### Expected Behavior 

During a "bond" action from an account that already has bonded tokens, if # of unclaimed rounds is less than 20, we shouldn't require the user to explicitly "claim".  This is because the "bond" transaction will automatically do the "claim".  This change will also save gas since it'll save the user an extra transaction.

#### Current Behavior 

The explorer asks the user to explicitly call "claim" if there are any unclaimed rounds when a user calls "bond".

#### Possible Solution 

The explorer can check the number of unclaimed rounds first.  If the number is less than 20, don't prompt the user to call "claim"

#### 🐞Steps to Reproduce

1. Bond toward a transcoder
2. After first bond succeeds, wait for a round, and try to bond additional tokens from the same address
3. Explorer will ask you to claim first

**Comment by jozanza** [comment]
I started addressing this issue yesterday. To start off, the explorer will now skip approval transactions for bonds where the amount is omitted. ([view commit](https://github.com/livepeer/livepeerjs/commit/ecd9805866caac8a96f1f2d3100ee591242b5ae9#diff-b2aec6fea59b33ff264b168f768feb39R57))
