### ISSUE TITLE
Unable to re-bond

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#62]
#### Expected Behavior 

Delegators should be able to bond to another transcoder without having to go through the unbonding waiting period. The unbonding waiting period is only there in the scenario of delegators want to withdraw the tokens and "get liquidity".

#### Current Behavior 

Delegators cannot bond to a different transcoder until they go through the unbonding period and withdraw.

#### Possible Solution 

Allow delegator to call "bond" to other transcoder, keep the "unbond" option to only the currently bonded transcoder.

#### 🐞Steps to Reproduce

1. Bond to a transcoder
2. Try to bond to a different transcoder

**Comment by jozanza** [comment]
@adamsoffer's PR should take care of this one 🎉
