### ISSUE TITLE
Player is buffering content but not playing it

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#63]
I have loaded the player using Chromium in Ubuntu, the stream plays for a little while, but then stops playing.

The content keeps buffering, but I am unable to play it.

See screenshots to show problem:

1:47 of buffered content - unable to play, stuck on 00:57 and pressing pause / play doesn't fix it:

![image](https://user-images.githubusercontent.com/2212651/39664124-e680bc14-507e-11e8-93eb-bca379f4c876.png)

2:45 of buffered content - unable to play:

![image](https://user-images.githubusercontent.com/2212651/39664126-fe93fece-507e-11e8-9e6b-99312b0c80d9.png)

3:46 of buffered content - unable to play, still stuck at 00:57:

![image](https://user-images.githubusercontent.com/2212651/39664132-2771fda0-507f-11e8-8903-83029340d376.png)

4:24 of buffered content - still stuck at 00:57, unable to play, even if I press pause then play

![image](https://user-images.githubusercontent.com/2212651/39664143-4cd458f4-507f-11e8-86f2-97688f350307.png)

**Comment by jozanza** [comment]
@chrishobcroft do you mind updating your initial comment to match the bug report [ISSUE_TEMPLATE](https://github.com/livepeer/livepeerjs/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)?

**Comment by jozanza** [comment]
I'm going to close this issue. Reopen if this is still a bug and you've updated the issue description to fit the [bug report issue template](https://raw.githubusercontent.com/livepeer/livepeerjs/master/.github/ISSUE_TEMPLATE/Bug_report.md)
