### ISSUE TITLE
Can only claim one round of earnings at a time

### ISSUE THREAD

**Issue by tnels79** [livepeer/livepeer-monorepo#633]
**Describe the bug (required)**

**Expected behavior (required)**

**To Reproduce (required)**

**Device (required):**
 - Device: [e.g. MacBook Pro, iPhone6]
 - OS: [e.g. iOS, Linux]
 - Browser [e.g. Chrome, Safari]
 
**Screenshots (optional)**

**Console logs (optional)**
```
Paste related logs and/or error messages from the console here.
Network issues, such as the cURL output from failing requests, can also be pasted here.
```

**Additional context (optional)**

**Comment by adamsoffer** [comment]
This has been fixed. This was an issue on the classic explorer which was moved into a separate repo [here](https://github.com/livepeer/explorer-classic). 
![image](https://user-images.githubusercontent.com/555740/79822172-8cc35f00-835e-11ea-9079-b56b05b78eb1.png)
