### ISSUE TITLE
Player not starting on Brave/Chrome on Android

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/livepeer-monorepo#64]
#### Expected Behavior

When I load a channel via http://media.livepeer.org/channels/0x... using either Brave browser or Chrome browser on Android, I expect that it should play the content being streamed.

Smartphone: Google Pixel XL running Android 8.1.0 (latest)
Network Types: 4G LTE; DSL Wifi

#### Current Behavior

Instead of the expected behaviour, I experience that it doesn't play the content being streamed.

What happens instead is that the player loads, but shows 0:00:00, which I presume indicates that there is no content to play.

#### Context

This issue stops me from being able to test the viewing of any content using my smartphone.
...

#### Possible Solution 

Perhaps this is something with connection to the CDN?

#### 🐞Steps to Reproduce

I tested this when also successfully watching content through Brave browser on Ubuntu.

1. Load up www.livepeer.tv using either Chrome or Brave on Android.
2. Browser redirects to https://media.livepeer.org/channels/0x0dDB225031cCB58fF42866f82D907F7766899014
3. Player loads and shows "L O A D I N G..."
4. Player shows play button in the middle
5. I click on play button in the middle of the player
6. Speaker symbol appears in the top left (usually indicating that something is playing back audio) - see screenshot below.
7. Player shows black screen, and 0:00:00 - see screenshot below.

#### 🐞Your Environment

Android 8.1.0 running on Google Pixel XL build OPM2.171019.029
Chrome 66.0.3359.126
Brave 1.0.44 Chromium 65.0.3325.109

**Comment by chrishobcroft** [comment]
![screenshot_20180505-161812](https://user-images.githubusercontent.com/2212651/39664238-8b2897a4-5080-11e8-91e4-bb2e239f2251.png)

**Comment by jozanza** [comment]
Closed by c4fe82cb3527549eaa8858b19cc9312ac8999b9d
