### ISSUE TITLE
"Unlock Livepeer tokens for staking" link doesn't do anything

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#662]
**Describe the bug (required)**

When I try clicking the "Unlock Livepeer tokens for staking" link nothing happens.

**Expected behavior (required)**

I expect clicking the "Unlock Livepeer tokens for staking" link to bring up a Metamask confirmation dialog to unlock my tokens.

**To Reproduce (required)**
1. Create a fresh Metamask account with some LPT
2. Go to the campaign view for an O
3. Type in a non-zero value in the "Input" field of the staking widget on the right hand side of the screen
4. Observe a "Unlock Livepeer tokens for staking" appear at the bottom of the widget
5. Try clicking the link and observe that nothing happens

**Device (required):**
 - Device: Macbook Pro
 - OS: OSX
 - Browser: Chrome
 - Version: https://polling.livepeerorg.now.sh/
 
**Screenshots (optional)**

![Screen Shot 2020-04-30 at 1 23 16 PM](https://user-images.githubusercontent.com/5933273/80740402-05a48280-8ae6-11ea-9104-f03bde161e7c.png)

**Comment by adamsoffer** [comment]
Addressed by #652
