### ISSUE TITLE
polling: Total support % breaks margin used in the rest of the display box

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#663]
**Describe the bug (required)**

When the total support % in the poll detail view has many decimal places, the decimals break the margin in the display box on the right.

**Expected behavior (required)**

The last decimal in the total support % to not break the margin used by the text below it.

**To Reproduce (required)**
1. Make sure that the total support % for a poll includes many decimals
2. Go to the poll detail view and observe the total support % display box

**Device (required):**
 - Device: Macbook Pro
 - OS: OSX
 - Browser: Chrome
 - Version: https://polling.livepeerorg.now.sh/voting/0xbf790e51fa21e1515cece96975b3505350b20083
 
**Screenshots (optional)**

![Screen Shot 2020-04-30 at 1 32 03 PM](https://user-images.githubusercontent.com/5933273/80741716-1e159c80-8ae8-11ea-806f-7126791dfcf3.png)

**Comment by adamsoffer** [comment]
Fixed in latest
