### ISSUE TITLE
polling: Total participation needed does not match quorum defined in PollCreator

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#664]
**Describe the bug (required)**

The parameter values for the PollCreator on Rinkeby can be found [here](https://rinkeby.etherscan.io/address/0xbe892721530686124546622fe2c63ce3aefeb44a#readContract). The total participation needed shown in the poll detail view is 33% which is different from the quorum value in PollCreator. 

Side note: The quorum value in the PollCreator on Rinkeby is actually wrong right now, so we'll need to deploy an updated version with the right value as well.

**Expected behavior (required)**

The total participation needed displayed in the poll detail view to be the same as the quorum value defined in the deployed PollCreator.

**Device (required):**
 - Device: Macbook Pro
 - OS: OSX
 - Browser: Chrome
 - Version: https://polling.livepeerorg.now.sh/voting/0xbf790e51fa21e1515cece96975b3505350b20083
 
**Screenshots (optional)**

![Screen Shot 2020-04-30 at 1 41 16 PM](https://user-images.githubusercontent.com/5933273/80742129-df341680-8ae8-11ea-8861-84d0a055a3eb.png)

![Screen Shot 2020-04-30 at 1 45 41 PM](https://user-images.githubusercontent.com/5933273/80742145-e9561500-8ae8-11ea-885b-a2a723dbe977.png)

**Comment by adamsoffer** [comment]
Fixed. Now pulls from quorum field subgraph.
