### ISSUE TITLE
polling: Unbonding as an O increases No vote stake

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#665]
**Describe the bug (required)**

Start state for the poll detail view:
- Yes vote stake = 13.74m
- No vote stake = ~105
- My O votes Yes

My O unbonded 1m and the Yes vote stake dropped to 12.74m, but the No vote stake was set to 13.74m. 

**Expected behavior (required)**

I expect the No vote stake to be unchanged when my O unbonds - the unbonded LPT no longer contributes to my O's Yes vote, but it should not contribute to the No vote stake for the poll either.

**Device (required):**
 - Device: Macbook Pro
 - OS: OSX
 - Browser: Chrome
 - Version: https://polling.livepeerorg.now.sh/voting/0xbf790e51fa21e1515cece96975b3505350b20083
 
**Screenshots (optional)**

![Screen Shot 2020-04-30 at 1 56 18 PM](https://user-images.githubusercontent.com/5933273/80743083-6209a100-8aea-11ea-9b11-fc61207d6528.png)

**Comment by yondonfu** [comment]
Rebonding 1m with that same O set the No vote stake back to ~105, but the Yes vote stake went up to 27.49m

![Screen Shot 2020-04-30 at 2 29 55 PM](https://user-images.githubusercontent.com/5933273/80745997-291ffb00-8aef-11ea-8726-3a5c8397593a.png)

**Comment by adamsoffer** [comment]
Looking into this now. I've added an integration test for unbonding with an O and confirmed there's a bug in the `updatePollTallyOnUnbond` subgraph handler.

**Comment by adamsoffer** [comment]
Fixed
