### ISSUE TITLE
polling: Unlocked LPT for poll creation but can't click "Create Poll"

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#666]
**Describe the bug (required)**

In the create poll view, I clicked "Unlock LPT for Poll Creation" and confirmed an [approval tx](https://rinkeby.etherscan.io/tx/0xb98d1fe9c1c24de8d5d41c40aa223b4cd5f9de782d7d21819618ba24a819f3bb). The account has 100 LPT https://rinkeby.etherscan.io/address/0x3034e8a8f9172fa4e960f095c8a90bc52eaac27e. But, even after I refresh the page the "Create Poll" button is still grayed out and the "Unlock LPT for Poll Creation" button is still active.

**Expected behavior (required)**

I expect to be able to click the "Create Poll" button because I submitted an approval tx and have 100 LPT.

**Device (required):**
 - Device: Macbook Pro
 - OS: OSX
 - Browser: Chrome
 - Version: https://polling.livepeerorg.now.sh/voting/create-poll
 
**Screenshots (optional)**

![Screen Shot 2020-04-30 at 2 09 48 PM](https://user-images.githubusercontent.com/5933273/80744206-5028fd80-8aec-11ea-8c8d-a382c5bc4d0d.png)

![Screen Shot 2020-04-30 at 2 09 58 PM](https://user-images.githubusercontent.com/5933273/80744218-53bc8480-8aec-11ea-9b97-19b77dcb385a.png)

**Comment by adamsoffer** [comment]
Fixed.
