### ISSUE TITLE
Changing vote in the polling UX does not reflect the update in the status views

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#667]
**Describe the bug (required)**
I changed the vote of an account from Yes to No. The "Do you support..." area of the page updated with the latest tally, but the Total Support and Total Participation Tabs did not update. See the screenshot which shows over 100% participation:

![Screen Shot 2020-04-30 at 3 36 47 PM](https://user-images.githubusercontent.com/10389/80752635-d1d35800-8af9-11ea-9430-670925ce4fff.png)

**Expected behavior (required)**
Those two panels need to reflect the fact that it was a changed vote, rather than a new vote.

**To Reproduce (required)**
1. Go to a poll
2. Vote yes
3. Vote no
4. Observe that the numbers in the panel are now incorrect.

**Device (required):**
 - Device: Macbook Pro
 - OS: iOS
 - Browser Chrome

**Comment by adamsoffer** [comment]
Fixed by #652
