### ISSUE TITLE
Change stream to accommodate RTMP ingest

### ISSUE THREAD

**Issue by wohlner** [livepeer/livepeer-monorepo#673]
### Vocabulary:
`stream key` and `stream id`  used interchangeably - string id that is used to uniquely identify incoming RTMP stream (used as part of the RTMP ingest URL). Generated by Livepeer API.
`playback id` - string id that is used to identify outgoing stream. Used as a part of URL used to play transcoded stream.

### Implementation:
- add parentId, playbackId, streamKey fields to the stream object.
- workflow will work this way:
  - user creates new `stream` object using `/api/stream` endpoint. Fields `playbackId` and `streamKey` are generated by API, `parentId` is empty.
  - RTMP stream hits Mist server with URL like rtmp://mist.host/live/streamKey
  - Mist sends this RTMP url to `mist-api-connector`. Connector gets `stream` object from API (by `streamKey` and creates new 'stream' inside Mist instance, setting API URL for this stream to be `http://livepeeer.api/api/stream/streamObjectId`. That way, when Mist will start transcoding it will use `http//livepeer.api/api/stream/streamObjectId/stream` endpoint to create new stream object when transcoding starts. Handler for that endpoint will create new `stream` object with it `parentId` set to `streamObjectId` and `streamKey` and `playbackId` set to be empty.
  - The API will also need to handle requests for broadcasters at `http//livepeer.api/api/stream/streamObjectId/broadcaster`

In the UI we will show objects that has set `parentId` in the separate table called `Stream Sessions`. `lastSeen` field from the most recent `Stream Session` will also be shown on the parent `stream` object.

### Changes to Model:
We want to shows most recent sessions first, so we need a way to sort results we get from database. Currently our db returns results in ascending order, so we need to add option to sort in descending order.
So we will change
`Model.query(kind, queryObj, cursor, limit, cleanWriteOnly)` to

```
Model.query({
  kind: "user",
  query: {email: "eli@iame.li"},
  cursor,
  limit,
  desc: true
});
```

---
Old task, left here for historical purposes

Mist has two options to make separate URLs for streaming and playing back.
1. In stream configuration add 'password'. Without password urls looks like these:
    - rtmp://mist.host/live/stream_name
    - http://mist.host/hls/stream_name/index.m3u8
    When password added, URLs looks like:
    - rtmp://mist.host/password/stream_name
    - http://mist.host/hls/stream_name/index.m3u8
2. Use Mist trigger that allows us to check and rewrite (for internal purposes) RTMP url - allows us to write any logic around RTMP URLs we want

Will be implementing first option as it requires less work.

Currently, when `stream` object created through API, user gives name to the stream, and automatically generated ID assigned to the stream. `name` field currently not used anywhere and id is used as stream_name in URLs.
For example, user creates steam using this request:
```json
{ "name": "test_stream", "presets": ["P240p30fps16x9"] }
```
and in response gets:
```json
{ "id": "fa644ea8-fa66-4285-83af-7e030b92ee51"}
```
So now URLs will be:
    - rtmp://mist.host/live/fa644ea8-fa66-4285-83af-7e030b92ee51
    - http://mist.host/hls/fa644ea8-fa66-4285-83af-7e030b92ee51/index.m3u8

My proposal is to use user-provided stream name as playback ID and stream object's id as password, so URLs will be:

    - rtmp://mist.host/fa644ea8-fa66-4285-83af-7e030b92ee51/test_stream
    - http://mist.host/hls/test_steam/index.m3u8

Implementation tasks:
 - [ ] Check that stream name is unique upon creation
 - [ ] Show stream name in streams list in UI
 - [ ] Change mist-controller to create proper configuration in Mist when creating streams inside Mist server

**Comment by iameli** [comment]
@darkdarkdragon  I like this! One additional checkbox: I think the existing definition of `name` allows for any string at all to be used. If we're going to use that name in URLs, we should probably verify that name is URL-safe... I feel like allowing people to name their streams something like `"😬😆🛳"` will be trouble — even if we handle it correctly, we'd need us, Mist, and the TLS terminator (nginx/traefik) to all handle the URLs in the same way, and that sounds messy.

**Comment by wohlner** [comment]
I like how you are thinking of this. A couple notes/questions.

1. In the existing http workflow, the user provides the stream name. In the UI for the rtmp ingest workflow, is anything stopping us from providing the stream name string for them? That would obviate the need to check for duplicates and URL safe characters.

1. I like using the password as part of authenticating for ingest. In the UI and UX, let's refer to that as the `stream key` instead of the password. There is still the requirement that we have a single ingest URL for all users in a given region (one for US and one for EU). I can't tell if you proposal misses that requirement.

1. In the UX for the rtmp ingest workflow, I'd like what we are now calling the stream name to be the a `live stream id.` For more context, the related endpoints and responses could be something like this for the user:
`/live-stream-ids`
GET: all live stream ids created by this user (or maybe should it be for a given API key?)
`/stream-status`
GET: a list of stream statuses based on the list of live-stream-ids
`/stream`
GET: the properties of a stream (playback id, playback url, stream-status, ingest URL, stream key, created)

Thoughts / feedback? @iameli @darkdarkdragon

**Comment by darkdarkdragon** [comment]
@wohlner 
1. Can you elaborate on that? I'm not sure I understand.
2. It was called `password` in Mist's documentation - and here I'm describing how our internals will connect to Mist's internal. But surely, let's call it `stream key` for us. 
  > here is still the requirement that we have a single ingest URL for all users in a given region
  
This one lives on a different level from this proposal. This proposal describes authentication mechanism for each Mist instance, and given that we have global database each instance will authenticate against same data. And it doesn't matter at which actual URL Mist serves - we're checking only `stream key`/`stream id` part of the URL.

3. For now I don't see any need for separate `/live-stream-ids` and `/stream-status` endpoints. Stream status currently is just three field of the `stream` object.  We do have endpoint that returns all user's streams and endpoint that returns stream by id. That's all the information we have now, don't see need to divided it.

> (or maybe should it be for a given API key?)

Good question. Right now we don't track by what key stream was created. Maybe we should?

**Comment by wohlner** [comment]
Thanks for explaining. 

1. Instead of users defining their stream name, let's generate and give them a string. Let's tell them what the `name` is instead of letting them pick. The playback URL won't be pretty, but that's fine. 

1. Cool, makes sense.

1. Yes, we should have the ability to get all streams of an api key. It's ok if we don't do that yet. It's out of scope for this proposal. But we should do it soon.

**Comment by wohlner** [comment]
Let’s say the RTMP ingest URL for is rtmp://theingesturl/
And the let’s say the stream key (you referred to it as password in your PR) is mystreamkey123

The Livepeer API product should accept a user sending a video to rtmp://theingesturl/mystreamkey123 or sending it to rtmp://theingesturl/ and inputting their stream key, mystreamkey123, like how it is done in the OBS UI.

I don't understand why you are suggesting the name in the ingest URL.

**Comment by darkdarkdragon** [comment]
We have two technical options to implement this (I've described them in beginning).
URL structure `rtmp://host/password/name` is what Mist gives us for first option.
If we go with second option then we can make URL to look like anything we want.

Initially I've thought that implementing first option will require less work, but after looking into it more thoroughly - amount of work will be same, so I'll proceed with the second option.

**Comment by wohlner** [comment]
Sounds good. Thanks @darkdarkdragon for writing this up and explaining everything to make sure we are picking the right implementation. I'm glad option 2 is the same amount of work and not more.

**Comment by darkdarkdragon** [comment]
@wohlner Another UX question - do we want ability to change `stream key`? If we're using internal steam object id field as `stream key` - then user can't change it, only delete stream and create new one. If we want ability to change `stream key` without deleting stream - then we need to add new field to database.

**Comment by wohlner** [comment]
Good question. No, we do not need the ability to change a stream key in the UI. It will be a string we provide to the user.

**Comment by wohlner** [comment]
@darkdarkdragon, @iameli and I are talking on a call. When you are back from the Ukraine holiday, check in with us before continuing to build this out.

**Comment by j0sh** [comment]
For what it's worth, we've had a similar thought process in go-livepeer around attempting to improve how we present and communicate certain concepts to users. Example: https://github.com/livepeer/go-livepeer/issues/871

> My proposal is to use user-provided stream name as playback ID and stream object's id as password, so URLs will be:

My two cents on this, following the line of thinking outlined in https://github.com/livepeer/go-livepeer/issues/871. For user supplied values, it might help to refer to them as "names" . So in this case, for a user-provided stream name it  might be a "playback name" rather than a "playback ID". If a value is supplied by us, especially auto-generated values, then calling it an "ID" makes more sense.

I see that we're leaning towards supplying the name now, so "playback ID" would be fine in that case. Anyway, that's just my thought process here with respect to nomenclature.

**Comment by darkdarkdragon** [comment]
@wohlner I've finished adding changes to mist connector - now it works with multiple bitrates (with latest Mist server) and handles stream key/id as was described here.
I've also commited my changes API (https://github.com/livepeer/livepeerjs/pull/688) - it works, just misses unit tests and some UI improvements.

**Comment by wohlner** [comment]
Ok great! That's awesome. We will talk when you get back, just minor possible tweaks
