### ISSUE TITLE
Explorer: Display transcoder workload

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#68]
**What is this discussion about? (required)**
Delegators should see some indication about how much work a transcoder has performed when deciding whom to delegate towards.

**What do you hope to learn by the end of this discussion? (required)**
This is one of three useful pieces of information that I think delegators need right now. In priority order:

1. Does a transcoder consistently call reward? See #66 
2. Has a transcoder performed adequate work? (this issue)
3. Has a transcoder been slashed for a fault? 

This one is tricky because the explorer needs to efficiently read data from the blockchain and perform calculations without having access to an indexed DB of the entire history of work for a transcoder. It's also tricky because you don't necessarily know how much work a transcoder *should* be doing based upon their pricing and stake.

One idea is to just display the # of segments claimed last round for each transcoder. The # of segments claim should be in rough proportion to their stake if they are price competitive. That's it. It's a simple proxy that doesn't encapsulate everything, but it's a good start.

**Additional context**
I also think that since the transcoder page/reward cycle is kind of like a game right now, what gets displayed prominently is what people are competing for. If we display # of segments claimed, then people will compete to do work and have something to show for it.

Also, if you're worried about people claiming segments that they didn't actually encode, then this would be addressed by the next issue I'll file - displaying instances of slashing.

**Comment by jozanza** [comment]
Since this requires aggregating onchain data, let's wait for Supermax's API.
