### ISSUE TITLE
www. Stream list UI (new page)

### ISSUE THREAD

**Issue by wohlner** [livepeer/livepeer-monorepo#692]
1. Create stream 
1. Delete stream(s)
1. Table list of streams
    - Live stream id
    - Created
    - Status

There are dependencies on API parent-child decisions.

**Comment by darkdarkdragon** [comment]
@wohlner 
 `Created` field - it is date at which stream was created? Right now we don't save creation date for any of our objects. Probably we should add it for all of the objects.
