### ISSUE TITLE
Player - StreamID gets truncated

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#7]
Right now we display the streamID on the player, but it's too long and gets truncated. When people end up wanting to share a specific streamID, we'll need to display the full version. We could either wrap, or use a smaller font for it.

https://cl.ly/3N0G2N1x2F1C

**Comment by saskakol** [comment]
How about letting it get truncated, but adding some css to the element so it wraps on hover?

**Comment by jozanza** [comment]
Good question. It does get truncated. And double-clicking still copies the entire stream id. It’s an edge case that someone would even need to do this anyways. The stream id is also available in the explorer. I’ll just close this one out.
