### ISSUE TITLE
Channel Player Not Working In Chrome

### ISSUE THREAD

**Issue by rayj00** [livepeer/livepeer-monorepo#70]
**Describe the bug (required)**
Browsing to an active stream using the channels player does not work.
The browser continuously shows "LOADING.....  LOADING....., etc."

**Expected behavior (required)**
Browsing to the channel player should display the stream based on the Eth Adr.

**To Reproduce (required)**
Browse to an active stream on the network: example: https://media.livepeer.org/channels/0x35e01199F8137077346FDD476191f1967A52BDb5 

**Device (required):**
  - Browser: Chrome
  - Version 66.0.3359.139 (Official Build) (64-bit)
 
**Screenshots (optional)**

**Console logs (optional)**
```
There are no obvious error messages in the LP console.
```

**Additional context (optional)**
The player just shows the "LOADING...." over and over.
The Stream Viewer works fine in Chrome.

**Comment by jozanza** [comment]
It seems like this issue may have been caused by the browser caching the old response for the playlist you were requesting. I'm going to close this one.

**Comment by rayj00** [comment]
Ok, I made a change to the following Chrome flag: chrome://flags/#autoplay-policy
Original value: DEFAULT(edited)
New Value: No User Gesture Required.
That seemed to fix it.   I don't know why this wasn't an issue previously?   I have never messed with any of the Chrome flags before.

**Comment by jozanza** [comment]
I have a feeling this is the route of the problem:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> Chrome's autoplay policies will change in April of 2018 and I'm here to tell you why and how this is going to affect video playback with sound. Spoiler alert: users are going to love it!
![screen shot 2018-05-08 at 4 12 59 pm](https://user-images.githubusercontent.com/740794/39780801-75ebce62-52db-11e8-93f4-be1ccdd9abb6.png)
> Chrome's autoplay policies are simple:
> - Muted autoplay is always allowed.
> - Autoplay with sound is allowed if:
>    - User has interacted with the domain (click, tap, etc.).
>    - On desktop, the user's Media Engagement Index threshold has been crossed, meaning the user has previously play video with sound.
>    - On mobile, the user has added the site to his or her home screen.
> - Top frames can delegate autoplay permission to their iframes to allow autoplay with sound.

It may also be the same problem causing #64

**Comment by jozanza** [comment]
Closed by c4fe82cb3527549eaa8858b19cc9312ac8999b9d
