### ISSUE TITLE
api: add `endpoint` API object

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-monorepo#710]
Use case:

1. I configure an RTMP endpoint and stream into Mist. Mist creates a stream object using its internal key. I want to see the status of _that_ stream, even though it's not the initial stream definition I created.
2. I created an RTMP endpoint and put my stream key in lots of places. Now, I want to change my bitrate ladder for this stream, without deleting and recreating the stream key.

Proposal:

* New object: `endpoint`.
* Fields: id, key, profiles
* `profiles` field is the same as it is on `stream`
* New field on `stream`: `endpointId`. Either `null`, or the name of the endpoint that created us

Behavior:

* User creates a endpoint `{id: "354a8a3c-ebb9-4560-8dd9-03fc02e9a8a9", key: "vs6f-oqwk-h83m", profiles: [... 720p, 360p, 240p ... ]}`
* User streams to `rtmp://server/live/vs6f-oqwk-h83m`
* `mist-api-connector` reads the endpoint and populates the renditions in Mist
* Mist creates a stream. That stream (TODO: how?) gets a `endpointId` of `354a8a3c-ebb9-4560-8dd9-03fc02e9a8a9`.
* A user on the front-end can query `GET /api/stream?endpointId=354a8a3c-ebb9-4560-8dd9-03fc02e9a8a9` and get the status for the streams corresponding to their templates.
* This HLS stream can then be played back through a CDN at `https://CDN-URL/stream/354a8a3c-ebb9-4560-8dd9-03fc02e9a8a9.m3u8` or some such

**Comment by wohlner** [comment]
We are missing the `playback-id` and the human readable `name`. Both on the `stream-template` object.

**Comment by wohlner** [comment]
It's probably ok to use the `stream-template`'s `id` as the `playback-id`.

**Comment by iameli** [comment]
Closed in favor of the "stream cloning" spec defined here https://github.com/livepeer/livepeerjs/issues/673
