### ISSUE TITLE
add 'secondsTranscoded' field to 'stream' object

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/livepeer-monorepo#715]
In `stream-info-service` parse segment's lengths  and update `secondsTranscoded` field of `stream` object

**Comment by darkdarkdragon** [comment]
@wohlner @iameli Should we add lengths of each renditions?
i.e., if one segment of 2 sec length was transcoded to three renditions, should `secondsTranscoded` be six?

**Comment by wohlner** [comment]
Do both of these please:
`sourceSecondsTranscoded`
`totalSecondsTranscoded`

Look at the length of one transcoded segment to confirm the length of the source segment.
