### ISSUE TITLE
Add "Pending Stake" to the explorer

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#72]
**What's the problem? (required)**
"Pending Stake" is not viewable in the explorer. Users want to know how much token they've earned that they're entitled to when they claim(). 

**What's the current behavior? (required)**
It's not visible anywhere.

**Describe a possible solution you've considered (optional)**
The CLI shows a "Pending Stake" value, which I assume does some quick calculation based off of on chain data. Perhaps we replicate this logic and display this value in the explorer on the delegation page.

**Comment by jozanza** [comment]
Yeah we really need this one. I want to see this constantly.

**Comment by saskakol** [comment]
Just looked through some of the go-livepeer code, and it looks like getting the pendingStake is the job of the bondingManager contract. 
> // PendingStake is a free data retrieval call binding the contract method 0x9d0b2c7a.

It should be relatively simple to just retrieve the data, but i couldn't find out what address the contract is deployed to on the network.

**Comment by saskakol** [comment]
Okay, found the contract addresses. Looks like it wants the _delegatorAddress and _endRound values to get the pending stake. Delegator address should be pretty simple (just get the web3 account the user is using, right?), but i'm not sure about endRound. I guess it is available somewhere in the explorer code. Will take a look at that later 👍

**Comment by dob** [comment]
@iSasFTW it should be the current round, which is available in the RoundsManager contract via the `currentRound()` function.

**Comment by jozanza** [comment]
@iSasFTW you should familiarize yourself with the graphql-sdk package. The documentation clearly describes the schemas available via graphql queries, and most of the required info should already be in the scope of the Transcoders view.
