### ISSUE TITLE
Primer is showing zero for round length and inflation

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#755]
**Describe the bug (required)**
See this tweet reporting the issued at https://livepeer.org/primer/

https://twitter.com/_libertyhound/status/1271593724968153094

The values in the primer in the inflation and rounds section are showing zero. There may be other bugs as well along these lines, but didn't go through the entire thing.

**Comment by adamsoffer** [comment]
@dob thanks, will push up a fix today.

**Comment by adamsoffer** [comment]
@dob - this is now fixed if you want to take a look. There was an issue with the api the primer relies on to fetch that data.

**Comment by dob** [comment]
Excellent. Thanks. Looks good to me.
