### ISSUE TITLE
Archive Chroma in favor of @livepeer/ui

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-monorepo#773]

**Comment by iameli** [comment]
@adamsoffer Does anything use `@livepeer/ui`? The player uses stuff from chroma but it could probably just move into the player package itself.

**Comment by iameli** [comment]
Or the player and chroma could get archived together.

**Comment by adamsoffer** [comment]
@iameli nothing uses `@livepeer/ui` at the moment, but the new `livepeer.org` will. Here's the latest `@livepeer/ui` [styleguide](https://livepeer.modulz.app/) created using modulz. I'm waiting for modulz to support github integration at which point I'll push the modulz generated source code to this repository for source control & version history.

Yea agreed for now I think it makes sense to just move the `VideoPlayer` component from Chroma (this is the only component exported from that package) into the Player package and archive Chroma. I think down the road the player can be rebuilt using `@livepeer/ui`. 

<img width="860" alt="Screen Shot 2020-07-13 at 12 11 05 PM" src="https://user-images.githubusercontent.com/555740/87327382-01430f80-c502-11ea-9e64-d6bd33a37ab4.png">
