### ISSUE TITLE
Add profiles field to stream config API

### ISSUE THREAD

**Issue by j0sh** [livepeer/livepeer-monorepo#785]
**What's the problem? (required)**

Support for H.264 profiles was added to go-livepeer in https://github.com/livepeer/go-livepeer/pull/1542 . This needs to be added to the stream config API.

The format is:
```
"profiles":<string>
```

Up to you whether to explicitly enumerate / check the supported profiles within the API. The current supported profiles are: "h264baseline" , "h264main" , "h264high" , "h264constrainedhigh"

**Comment by iameli** [comment]
`profile` rather than `profiles`, yeah?

Looks like the values are capitalized in those docs but lower-case here - does it matter which? I'll probably match the docs
