### ISSUE TITLE
Player Does't Use Latest Stream

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#8]
(Correct me if I'm wrong) I think the current player implementation takes the first available video for an Eth address and makes that the stream for the channel.

Because of the way our p2p network works, there is a problem with that - a new video stream will not be on the gateway node (exit node hooked up to the CDN), and therefore initially appear like it's not available.  So if someone stops an old stream and immediately starts a new one, the old stream will appear to be still available in the CDN, and the new stream will appear to be unavailable.

One possible work-around is to always try and show the video with the highest JobID.

p.s - The stream usually becomes available after 5-15 seconds.

**Comment by jozanza** [comment]
It should show the video with the highest jobId if it's on the CDN. The current player doesn't know anything about the p2p network and has no way of loading videos if they aren't on the CDN.

**Comment by dob** [comment]
I believe this is fixed as per the latest player updates which autoplay the latest video after verifying that it is still receiving new content and hence "live"
