### ISSUE TITLE
Document @livepeer/graphql-sdk with guideline on how to add/modify new queries and mutations

### ISSUE THREAD

**Issue by jozanza** [livepeer/livepeer-monorepo#81]
**What's the problem? (required)**
https://github.com/livepeer/livepeerjs/tree/master/packages/graphql-sdk has no documentation for how to add new queries and mutations to existing types

**What's the current behavior? (required)**
The README has pretty good type documentation, but no guidance on how to contribute new code as a developer.

**Do you have any personal experiences dealing with this problem? (optional)**
Explaining the package to every contributor can be time-consuming and it's best practice on Github to put any critical info into READMEs.

**Describe a possible solution you've considered (optional)**
Update README.md with instructions on how to add queries and mutations by modifying types and resolvers, covering updates with tests, and building.

**Comment by adamsoffer** [comment]
Closing since the `graphql-sdk` package has been archived in favor of the Livepeer subgraph.
