### ISSUE TITLE
Unbonding

### ISSUE THREAD

**Issue by tnels79** [livepeer/livepeer-monorepo#811]
I am trying to unbond my tokens and it has been over a week, on the main page it says I can unbond in approximatly 5 years? what gives, it is supposed to be 7 days

**Comment by adamsoffer** [comment]
Hey @tnels79 - please make sure you're using the [new explorer](https://explorer.livepeer.org). The classic explorer is no longer maintained and is bug prone.

**Comment by tnels79** [comment]
Thank you  Adam, that worked
