### ISSUE TITLE
Rinkeby explorer still uses Alchemy API

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#816]
**Describe the bug (required)**

rinkeby.explorer.livepeer.org uses the Alchemy API. I'm seeing a bunch of failed requests to `https://eth-rinkeby.alchemyapi.io/v2/...`. 

As a result, the home page of the site is:

<img width="399" alt="Screen Shot 2020-08-11 at 5 18 13 PM" src="https://user-images.githubusercontent.com/5933273/89949967-b0a0fe00-dbf6-11ea-86c3-1236380e6911.png">

**Comment by adamsoffer** [comment]
ah yeah the rinkeby deployment was out of sync. I redeployed and it's working now.
