### ISSUE TITLE
"My Account" Does not update

### ISSUE THREAD

**Issue by RaffiSapire** [livepeer/livepeer-monorepo#82]
**Amount of Livepeer doesn't update**
When I switch between wallet accounts, the amount of LPT doesn't update until refreshing a few times

**Livepeer Account Amount Updates**
I would expect LPT amount to change when I refresh the page 

**To Reproduce (required)**
1. Go to Metamask and change from one account with some livepeer to another with a different or no amount
2. Go back to my account
3. See error

**Device (required):**
 - Device: MacBook
 - OS: iOS
 - Browser: Chrome
 
**Screenshots (optional)**
<img width="1263" alt="screen shot 2018-05-16 at 6 11 54 pm" src="https://user-images.githubusercontent.com/14640410/40146763-c1daf82a-5934-11e8-99cc-f98613243ac8.png">

**Comment by jozanza** [comment]
If you switch accounts while on "My Account" page, it doesn't update the address in the url, so actually, you're still viewing your previous "My Account" page. This is different from past behavior, however, where it would automatically redirect the user back to their account page. We should restore that redirect behavior 👍

**Comment by hugomarisco** [comment]
I can work on this if no one else is already on it.

I'm trying to check how to detect when a redirection to `/me` should be triggered. The `AccountView` is a stateless component so I can't use `componentWillReceiveProps` to compare the new/old `userAddress` and redirect.

Another way is to actually render the `Account` view when accessing the route `/me` and don't rely on redirections at all (refactoring the component to support that).

@jozanza do you have any pointers on the best way to achieve this?

**Comment by jozanza** [comment]
Yeah you'll want to take a look at this callback: https://github.com/livepeer/livepeerjs/blob/master/packages/explorer/src/index.js#L103
