### ISSUE TITLE
Update minter address in sdk

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-monorepo#822]
**Describe the bug (required)**
The sdk is still pointing to the old minter contract address.

**Expected behavior (required)**
Since LIP-40 passed and the contract was updated, the sdk should point to the new address.

**Comment by kyriediculous** [comment]
This is fixed by https://github.com/livepeer/livepeerjs/pull/824 , right ? Feel free to re-open if not.

**Comment by adamsoffer** [comment]
yup thanks
