### ISSUE TITLE
See how much I have earned by participating

### ISSUE THREAD

**Issue by RaffiSapire** [livepeer/livepeer-monorepo#83]
**Can't see how much LPT I've earned as a delegator**
I'm unable to see how much token I have earned - both fees or LPT - from participating, and how much I will earn, and at what rate  

**Claim Rounds**
Currently, on delegator tab it says "claim rounds" but not how much is there 

**Do you have any personal experiences dealing with this problem? (optional)**
I want to know if its worth delegating every day, or if its worth unbonding to use some LPT, how much I'll miss out on inflation.

**Show Amount of LPT earned per round**
I would like to be able to see for each of the rounds I have not claimed, how much I earned

**Comment by jozanza** [comment]
This issue is already being tracked in https://github.com/livepeer/livepeerjs/issues/72. I believe @iSasFTW is already taking the lead on it as well 🎉
