### ISSUE TITLE
Error when trying to unbond

### ISSUE THREAD

**Issue by madbum** [livepeer/livepeer-monorepo#837]
Trying to unbond.  After submitting in MetaMask, I get a pop-up error: "Failed - There was an error submitting your transaction. See error message below for more details:
{
  "receipt": {
    "blockHash": "0xc1127e032c506dbbe8a9f5e88d07ed8e842b4d089f89d10b21c444c7067763b4",
    "blockNumber": "a6fc71",
    "contractAddress": null,
    "cumulativeGasUsed": "442571",
    "from": "0xaf00f59b6295be33ae1d5b12786b5f5a5be8dbbb",
    "gasUsed": "63060",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x0",
    "to": "0x511bc4556d823ae99630ae8de28b9b80df90ea2e",
    "transactionHash": "0xb3e94073e00d187e8482fbd4364dcf69f8d5aaaf53334f59cf4e1a6fba6d0b96",
    "transactionIndex": "22"
  },
  "transaction": {
    "blockHash": "0xc1127e032c506dbbe8a9f5e88d07ed8e842b4d089f89d10b21c444c7067763b4",
    "blockNumber": "a6fc71",
    "from": "0xaf00f59b6295be33ae1d5b12786b5f5a5be8dbbb",
    "gas": "200b20",
    "gasPrice": "c570bd7b3",
    "hash": "0xb3e94073e00d187e8482fbd4364dcf69f8d5aaaf53334f59cf4e1a6fba6d0b96",
    "input": "0x27de9e320000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "7a",
    "r": "0x7bb14f7462607d070a1dd2a7ea42c30432f8488fb12d1e7fc2ee85ecf43a5372",
    "s": "0x23610fb9595e981c3f7837809473ce3f0afe2b641f773fc158c27a43a5c3b177",
    "to": "0x511bc4556d823ae99630ae8de28b9b80df90ea2e",
    "transactionIndex": "22",
    "v": "0x25",
    "value": "0"
  }
}

Could someone assist?  What am I doing wrong?  Thanks.

**Comment by adamsoffer** [comment]
Hey, thanks for reporting. Which wallet are you using? Also, what are you entering when attempting to unbond? The reason I ask is because I'm seeing the following error in etherscan: "Fail with error 'unbond amount must be greater than 0k'"

**Comment by madbum** [comment]
Using MetaMask.  I've tried "0", i've tried the full amount, still getting the same errors.  Haven't tried an amount less than my total, maybe like 75% so I'll give that a shot.

**Comment by madbum** [comment]
Okay, looks like it worked this time.  Instead of full amount, I left a few LPT and it worked okay.  Thanks for the help Adam.

**Comment by adamsoffer** [comment]
@madbum - Glad you got it working. That actually sounds like a bug. You should be able to unstake your entire stake by clicking your staked balance. Thanks for reporting. If, however, you were manually entering your stake and it was over by a decimal and then it would make sense that the tx failed.
