### ISSUE TITLE
explorer: LIP text overflows box

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#849]
**Describe the bug (required)**

Looks like some of the text body of a LIP can overflow the surrounding box.

I observed this for LIP-25 https://explorer.livepeer.org/voting/0xbc2ea5527586346bde95136c3ea99d699d55443c

<img width="1074" alt="Screen Shot 2020-11-18 at 12 36 54 PM" src="https://user-images.githubusercontent.com/5933273/99566437-e5adb100-299a-11eb-8894-11f48d27162f.png">

**Comment by kyriediculous** [comment]
We could gitcoin this perhaps? 

I've seen us use it for smaller issues a long time ago

**Comment by kyriediculous** [comment]
Should be fixed by #853 , closing for now.
