### ISSUE TITLE
Performance changing from 1D to 1W and back again refetches data and shows loading spinner

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/livepeer-monorepo#860]
**Describe the bug (required)**
When switching timeframes in the performance tab from 1D to 1W and then back to 1D a loading spinner is shown indicating that the data is being refetched but shouldn't this ideally already be cached ? 

**Expected behavior (required)**
Switching back to 1D after already loading that data when loading the page should not incur a refetch. 

**To Reproduce (required)**
1. Go to explorer orchestrator overview performance tab
2. Change timeframe to 1W 
3. Change timeframe back to 1D
4. Observe loading spinner

**Comment by adamsoffer** [comment]
The timeframe filter has been removed so closing this issue.
