### ISSUE TITLE
explorer: null 3Box profile ID when linking external account

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#864]
**Describe the bug (required)**

I tried to link an external account after going through the 3Box profile setup flow. But, the profile ID displayed in the message that is supposed to be signed in livepeer_cli is null.

![Screen Shot 2020-12-09 at 6 54 51 PM](https://user-images.githubusercontent.com/5933273/101703550-c7dee380-3a50-11eb-9ff2-c302b337befc.png)

**Comment by adamsoffer** [comment]
Pretty sure this was due to a breaking change by 3box. I just downgraded to a previous version which should fix this issue. https://github.com/livepeer/livepeerjs/pull/917
