### ISSUE TITLE
Reduce lines of code in packages/explorer/src/components/TranscoderCard.js

### ISSUE THREAD

**Issue by jozanza** [livepeer/livepeer-monorepo#87]
**What is this discussion about? (required)**
Refactoring the TranscoderCard

**What do you hope to learn by the end of this discussion? (required)**
I want to find an approach for reducing the lines of code in the module.

**Additional context**

File `TranscoderCard.js` has 318 lines of code (exceeds 250 allowed). Consider refactoring.

https://codeclimate.com/github/livepeer/livepeerjs/packages/explorer/src/components/TranscoderCard.js#issue_5afdc45e4252a20001000136

**Comment by jozanza** [comment]
We can probably move the Tooltip component into its own module

**Comment by eswarasai** [comment]
- Create `props` directory at `src/` and have all the props as individual JS files which can be imported. Example: `TranscoderCardProps.js`, `TranscoderStatProps.js`
- Create `TranscoderStat.js` as a separate component file and import it
- Create `TranscoderCard.styles.js` and import `styles` in the component

Let me know what you think of these suggestions :)

**Comment by jozanza** [comment]
@eswarasai Sure! Feel free to make a PR for this, and we can review it.

**Comment by j0sh** [comment]
I'd also say that "250 lines of code allowed per file" is rather arbitrary and doesn't make sense in a lot of contexts. Scattering code across dozens of files has its own cost too. YMMV 🤷‍♂️

**Comment by jozanza** [comment]
That’s fair. But we’re gonna roll with it.
