### ISSUE TITLE
Player sometimes displays non-live segments

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-monorepo#9]
See: https://github.com/livepeer/go-livepeer/issues/228

I know this may be tricky to fix because it's tied to the CDN caching policy, but often the player shows a single segment that is non live instead of showing that the broadcaster is offline. I'd imagine there's some frontend UX tests we can do to try and determine, such as count the # of segments included in the m3u8 playlist and using heuristics to guess if the broadcast is actually live or not.

**Comment by jozanza** [comment]
I'd definitely be interested in exploring the CDN caching policy.

**Comment by jozanza** [comment]
@ericxtang can confirm this, but I believe this is an issue with LPMS holding onto segment for too long. So I think we might want to address the issue in that project.

**Comment by dob** [comment]
Fixed as per: https://github.com/livepeer/livepeerjs/commit/f955277bca880b959fab4cf1f74464fb89cbadf5

Approach is to poll the playlist file to see if new segments are added, and after 4 attempts if no new segments are added consider the stream dead. This works, but introduces latency before the stream can begin autoplaying. In reality we'd like to fix this in the media server so that the playlist isn't even served if the stream is no longer live. A short CDN TTL on the playlist would also help this.
