### ISSUE TITLE
Transcoders page doesn't show content when MetaMask is connected to private network

### ISSUE THREAD

**Issue by arthurk** [livepeer/livepeer-monorepo#92]
Hi,

the Transcoders page at https://explorer.livepeer.org/transcoders doesn't show any content when MetaMask is connected to a private local network.

Steps to reproduce:

1. Switch MetaMask Network to "Localhost 8545"
2. Reload the page

There is just a blank page, it would be nice if there was an error.

**Comment by veox** [comment]
I'm experiencing this with `parity-ethereum` v2.0.6. I.e., the issue is still present.

@arthurk What node/version are/were you using?..

**Comment by Randy1Burrell** [comment]
@arthurk and @veox could you give me some more details about this? For example, what was your chrome console's log output, were you connecting to a local Blockchain or was this a middleman private net to Ethereum's actual network etc.

**Comment by arthurk** [comment]
Sorry but I can't do it. I reported the bug in May and don't have the details anymore.

**Comment by veox** [comment]
@Randy1Burrell, the "blank transcoders page" no longer happens to me. The only thing I can _reliably_ reproduce now is https://github.com/livepeer/livepeerjs/issues/244.

**Comment by veox** [comment]
I've extracted the above comment into a separate issue.

**Comment by Randy1Burrell** [comment]
@arthurk thanks for reporting this in May and your response to my request.

@veox thanks for the details in the new issue. 

I am closing this now because it no longer affects you. If it pops up again we can always reopen it.
