### ISSUE TITLE
subgraph: active field for Transcoder entity should not be set in TranscoderActivated/Deactivated event handlers

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monorepo#929]
**Describe the bug (required)** A clear and concise description of what the bug
is.

At the moment, for the Transcoder entity, the active field field is set to true when the [TranscoderActivated](https://github.com/livepeer/livepeerjs/blob/bbe439701dea7b798ab08d41ce4b5f739d2b7653/packages/subgraph/src/mappings/bondingManager.ts#L526) event is emitted and to false when the [TranscoderDeactivated](https://github.com/livepeer/livepeerjs/blob/bbe439701dea7b798ab08d41ce4b5f739d2b7653/packages/subgraph/src/mappings/bondingManager.ts#L558) event is emitted. However, a transcoder only becomes active in the round *after* the TranscoderActivated event is emitted and inactive in the round *after* the TranscoderDeactivated event is emitted (this is a bit confusing...I know :/). As a result, if someone sends a GraphQL query with `where: { active: true }` expecting to get only active transcoders, they might receive transcoders that are actually still inactive (i.e. pending activation).

I think this could be resolved by setting the active field in the [NewRound](https://github.com/livepeer/livepeerjs/blob/bbe439701dea7b798ab08d41ce4b5f739d2b7653/packages/subgraph/src/mappings/roundsManager.ts#L54) handler. As the handler loops through the on-chain transcoder pool, it can check if the transcoder's activation round <= currentRound < transcoder's deactivation round and if so set active = true, else set active = false.

**Comment by adamsoffer** [comment]
ah that's right. I'll submit a PR with a fix. Sounds like a straight forward fix.
