### ISSUE TITLE
Dynamically detect protocol is paused, and put up "protocol paused" modal

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-monorepo#97]
**What's the problem? (required)**
Currently the protocol explorer doesn't know when the protocol is paused.  When users use the explorer during protocol pause, all transactions fail.

**What's the current behavior? (required)**
Not able to detect paused protocol

**Describe a possible solution you've considered (optional)**
Protocol explorer can detect when the protocol is paused, warn users, and stop them from doing actions that will trigger a transaction.

**Comment by jozanza** [comment]
@ericxtang What contract / method would be used to query for whether or not the protocol is paused?

**Comment by yondonfu** [comment]
The Controller contract has a `paused()` getter that will return `true` if the system is paused and `false` if the system is not paused.
