### ISSUE TITLE
Trying to unstake from an orchestrator that is shutting down

### ISSUE THREAD

**Issue by gutoskey** [livepeer/livepeer-monorepo#987]
My transaction seems to be in a loop and never finishes.

**Comment by adamsoffer** [comment]
Hey @gutoskey - can you share the tx on etherscan?

**Comment by gutoskey** [comment]
Here it is but I get a message that the transaction hash cannot be located. The orchestrator that is shutting down is:
0x481efb669b423cfaffa49890205427dea9b3d693

Ethereum Transaction Hash (Txhash) Details | Etherscan


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Ethereum Transaction Hash (Txhash) Details | Etherscan

Ethereum (ETH) detailed transaction info for txhash 0xb0dc05c39c6125a4c6398e9b3424b5eeecdb7bcbbed6f13b4404af627f...
 |

 |

 |




    On Monday, May 3, 2021, 04:24:04 PM EDT, Adam Soffer ***@***.***> wrote:  
 
 


Hey @gutoskey - can you share the tx on etherscan?

**Comment by adamsoffer** [comment]
You most likely need to resubmit the transaction with a higher gas price. The gas price just went up from 20 GWEI to over 90 GWEI. https://www.gasnow.org/

If you're using MetaMask here are instructions on how to do that. https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction

**Comment by gutoskey** [comment]
Thanks for your help. I am trying to cancel several transactions I have out there and then submit an unstaking trx with a higher gas fee. I appreciate the help.
    On Monday, May 3, 2021, 05:03:27 PM EDT, Adam Soffer ***@***.***> wrote:  
 
 


You most likely need to resubmit the transaction with a higher gas price. The gas price just went up from 20 GWEI to over 90 GWEI. https://www.gasnow.org/

If you're using MetaMask here are instructions on how to do that. https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction
